#ifndef Header
#define Header

// declare histograms here
// jet pT
#define NOMINAL // WEIGHTSYSTEMATICS, SHAPESYSTEMATICS , NOMINAL
#ifdef NOMINAL
TH1F* h_lep1_pt_basic;
TH1F* h_lep1_pt_basic_dphi;
TH1F* h_lep1_pt_basic_dphi_drap;
TH1F* h_lep1_pt_basic_dphi_drap_btag;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_lep1_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_lep2_pt_basic;
TH1F* h_lep2_pt_basic_dphi;
TH1F* h_lep2_pt_basic_dphi_drap;
TH1F* h_lep2_pt_basic_dphi_drap_btag;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_lep2_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;

TH1F* h_lep1_eta_basic;
TH1F* h_lep1_eta_basic_dphi;
TH1F* h_lep1_eta_basic_dphi_drap;
TH1F* h_lep1_eta_basic_dphi_drap_btag;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_lep1_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_lep2_eta_basic;
TH1F* h_lep2_eta_basic_dphi;
TH1F* h_lep2_eta_basic_dphi_drap;
TH1F* h_lep2_eta_basic_dphi_drap_btag;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_lep2_eta_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_delta_R_leplep_basic;
TH1F* h_delta_R_leplep_basic_dphi;
TH1F* h_delta_R_leplep_basic_dphi_drap;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_delta_R_leplep_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_delta_R_lep1jet_basic;
TH1F* h_delta_R_lep1jet_basic_dphi;
TH1F* h_delta_R_lep1jet_basic_dphi_drap;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_delta_R_lep1jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_delta_R_lep2jet_basic;
TH1F* h_delta_R_lep2jet_basic_dphi;
TH1F* h_delta_R_lep2jet_basic_dphi_drap;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_delta_R_lep2jet_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;

TH1F* h_sum_pt_basic;
TH1F* h_sum_pt_basic_dphi;
TH1F* h_sum_pt_basic_dphi_drap;
TH1F* h_sum_pt_basic_dphi_drap_btag;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_met_basic;
TH1F* h_met_basic_dphi;
TH1F* h_met_basic_dphi_drap;
TH1F* h_met_basic_dphi_drap_btag;
TH1F* h_met_basic_dphi_drap_btag_iso;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_met_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_inv_mass_basic;
TH1F* h_inv_mass_basic_dphi;
TH1F* h_inv_mass_basic_dphi_drap;
TH1F* h_inv_mass_basic_dphi_drap_btag;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass;
TH1F* h_inv_mass_basic_dphi_drap_btag_iso_pt1_pt2_j1pt_j2pt_ptbal_mjj_nji_zcen_mass_ptl;


TH1F* h_lep1_phi_basic;
TH1F* h_lep1_phi_basic_cuts;
TH1F* h_lep1_phi_basic_cuts_ptl;


TH1F* h_lep2_phi_basic;
TH1F* h_lep2_phi_basic_cuts;
TH1F* h_lep2_phi_basic_cuts_ptl;


TH1F* h_Z_pt_truth_basic;
TH1F* h_Z_pt_truth_basic_cuts;
TH1F* h_Z_pt_truth_basic_cuts_ptl;


TH1F* h_jet_n_basic;
TH1F* h_jet_n_basic_cuts;
TH1F* h_jet_n_basic_cuts_ptl;


TH1F* h_n_bjets_basic;
TH1F* h_n_bjets_basic_cuts;
TH1F* h_n_bjets_basic_cuts_ptl;


TH1F* h_lep_iso_basic;
TH1F* h_lep_iso_basic_cuts;
TH1F* h_lep_iso_basic_cuts_ptl;


TH1F* h_delta_phi_basic;
TH1F* h_delta_phi_basic_cuts;
TH1F* h_delta_phi_basic_cuts_ptl;


TH1F* h_Z_pt_reco_basic;
TH1F* h_Z_pt_reco_basic_cuts;
TH1F* h_Z_pt_reco_basic_cuts_ptl;


TH1F* h_delta_y_basic;
TH1F* h_delta_y_basic_cuts;
TH1F* h_delta_y_basic_cuts_ptl;


TH1F* h_Z_centrality_basic;
TH1F* h_Z_centrality_basic_cuts;
TH1F* h_Z_centrality_basic_cuts_ptl;


TH1F* h_pt_bal_basic;
TH1F* h_pt_bal_basic_cuts;
TH1F* h_pt_bal_basic_cuts_ptl;


TH1F* h_mass_jj_basic;
TH1F* h_mass_jj_basic_cuts;
TH1F* h_mass_jj_basic_cuts_ptl;


TH1F* h_n_jets_interval_basic;
TH1F* h_n_jets_interval_basic_cuts;
TH1F* h_n_jets_interval_basic_cuts_ptl;


TH1F* h_ljet0_pt_basic;
TH1F* h_ljet0_pt_basic_cuts;
TH1F* h_ljet0_pt_basic_cuts_ptl;


TH1F* h_ljet1_pt_basic;
TH1F* h_ljet1_pt_basic_cuts;
TH1F* h_ljet1_pt_basic_cuts_ptl;


TH1F* h_ljet2_pt_basic;
TH1F* h_ljet2_pt_basic_cuts;
TH1F* h_ljet2_pt_basic_cuts_ptl;


TH1F* h_gap_jet_pt_basic;
TH1F* h_gap_jet_pt_basic_cuts;
TH1F* h_gap_jet_pt_basic_cuts_ptl;

TH1F* h_ljet0_eta_basic;
TH1F* h_ljet0_eta_basic_cuts;
TH1F* h_ljet0_eta_basic_cuts_ptl;


TH1F* h_ljet1_eta_basic;
TH1F* h_ljet1_eta_basic_cuts;
TH1F* h_ljet1_eta_basic_cuts_ptl;


TH1F* h_ljet2_eta_basic;
TH1F* h_ljet2_eta_basic_cuts;
TH1F* h_ljet2_eta_basic_cuts_ptl;


TH1F* h_gap_jet_eta_basic;
TH1F* h_gap_jet_eta_basic_cuts;
TH1F* h_gap_jet_eta_basic_cuts_ptl;


TH1F* h_vec_sum_pt_jets_basic;
TH1F* h_vec_sum_pt_jets_basic_cuts;
TH1F* h_vec_sum_pt_jets_basic_cuts_ptl;


TH1F* h_ratio_zpt_sumjetpt_basic;
TH1F* h_ratio_zpt_sumjetpt_basic_cuts;
TH1F* h_ratio_zpt_sumjetpt_basic_cuts_ptl;
#endif

TH1F* h_delta_phi;
TH1F* h_delta_y;
TH1F* h_n_bjets;
TH1F* h_lepiso;
TH1F* h_lep1_pt;
TH1F* h_lep2_pt;
TH1F* h_ljet0_pt;
TH1F* h_ljet1_pt;
TH1F* h_pt_bal;
TH1F* h_mass_jj;
TH1F* h_n_jets_interval;
TH1F* h_Z_centrality;
TH1F* h_inv_mass;

#ifdef WEIGHTSYSTEMATICS 
TH1F* h_mass_jj_elec_0_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_1_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_0_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_1_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_0_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_1_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_1_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_1_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_0_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_1_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_0_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_1_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_1_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_PRW_DATASF_1down_pileup_combined_weight;
TH1F* h_mass_jj_PRW_DATASF_1up_pileup_combined_weight;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1down_central_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1down_central_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1up_central_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1up_central_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1down_forward_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1down_forward_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1up_forward_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1up_forward_jets_global_ineffSF_JVT;
#endif

#endif
