executable              = RunAnalysis.py
output                  = output/$(ClusterId).$(ProcId).out
error                   = error/$(ClusterId).$(ProcId).err
log                     = log/$(ClusterId).log
on_exit_remove   = (ExitBySignal == False) && (ExitCode == 0)
max_retries      = 3
requirements     = Machine =!= LastRemoteHost
transfer_input_files    = Analysis.C,Analysis.h,backend/,../../AnalysisCommons/
+JobFlavour = "microcentury"
