#ifndef Header
#define Header

#define NOMINAL // In previous versions of the code there was... SHAPESYSTEMATICS, WEIGHTSYSTEMATICS. But I decided to completely separate it.
#ifdef NOMINAL
histogramContainer elecnu_ptContainer;
histogramContainer muonnu_ptContainer;
histogramContainer elec_etaContainer;
histogramContainer muon_etaContainer;
histogramContainer delta_R_muonelecContainer;
histogramContainer delta_R_elecjetContainer;
histogramContainer delta_R_muonjetContainer;
histogramContainer sum_ptContainer;
histogramContainer metContainer;
histogramContainer moreCentralJetContainer;
histogramContainer lessCentralJetContainer;
histogramContainer normPtDifferenceContainer;
histogramContainer metToDilepnuRatioContainer;
histogramContainer metToDilepRatioContainer;
histogramContainer delta_phijjContainer;
histogramContainer nuElecPtContainer;
histogramContainer nuMuonPtContainer;
histogramContainer nuPtAssummetryContainer;
histogramContainer massElecClosestJetContainer;
histogramContainer massMuonClosestJetContainer;
histogramContainer massElecFurthestJetContainer;
histogramContainer massMuonFurthestJetContainer;
histogramContainer flavourJet1Container;
histogramContainer flavourJet2Container;
histogramContainer nLightJetsContainer;

histogramContainer elec_phiNotFullContainer;
histogramContainer muon_phiNotFullContainer;
histogramContainer jet_nNotFullContainer;
histogramContainer Z_pt_reco_iNotFullContainer;
histogramContainer Z_pt_reco_oNotFullContainer;
histogramContainer ljet2_ptNotFullContainer;
histogramContainer ljet3_ptNotFullContainer;
histogramContainer gap_jet_ptNotFullContainer;
histogramContainer ljet0_etaNotFullContainer;
histogramContainer ljet1_etaNotFullContainer;
histogramContainer ljet2_etaNotFullContainer;
histogramContainer gap_jet_etaNotFullContainer;
histogramContainer trans_mass_elecNotFullContainer;
histogramContainer trans_mass_muonNotFullContainer;
histogramContainer vec_sum_pt_jetsNotFullContainer;
histogramContainer ratio_zpt_sumjetptNotFullContainer;
histogramContainer Z_pt_truth_iNotFullContainer;
histogramContainer Z_pt_truth_oNotFullContainer;

histogramContainer delta_phiContainer;
histogramContainer delta_yContainer;
histogramContainer n_bjetsContainer;
histogramContainer isoContainer;
histogramContainer elec_ptContainer;
histogramContainer muon_ptContainer;
histogramContainer ljet0_ptContainer;
histogramContainer ljet1_ptContainer;
histogramContainer pt_balContainer;
histogramContainer mass_jjContainer;
histogramContainer n_jets_intervalContainer;
histogramContainer Z_centralityContainer;
histogramContainer omegaContainer;
histogramContainer reco_mass_iContainer;
histogramContainer reco_mass_oContainer;
histogramContainer reco_massContainer;
histogramContainer recoVisibleMassRatioContainer;


#endif

#endif
