#ifndef Header
#define Header

#define NOMINAL // NOMINAL , SHAPESYSTEMATICS, WEIGHTSYSTEMATICS
#ifdef NOMINAL
TH1F* h_lep_pt_basic;
TH1F* h_lep_pt_basic_dphi;
TH1F* h_lep_pt_basic_dphi_drap;
TH1F* h_lep_pt_basic_dphi_drap_btag;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_lep_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_lepnu_pt_basic;
TH1F* h_lepnu_pt_basic_dphi;
TH1F* h_lepnu_pt_basic_dphi_drap;
TH1F* h_lepnu_pt_basic_dphi_drap_btag;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_lepnu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_tau_pt_basic;
TH1F* h_tau_pt_basic_dphi;
TH1F* h_tau_pt_basic_dphi_drap;
TH1F* h_tau_pt_basic_dphi_drap_btag;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_tau_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_taunu_pt_basic;
TH1F* h_taunu_pt_basic_dphi;
TH1F* h_taunu_pt_basic_dphi_drap;
TH1F* h_taunu_pt_basic_dphi_drap_btag;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_taunu_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;

TH1F* h_lep_eta_basic;
TH1F* h_lep_eta_basic_dphi;
TH1F* h_lep_eta_basic_dphi_drap;
TH1F* h_lep_eta_basic_dphi_drap_btag;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_lep_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_tau_eta_basic;
TH1F* h_tau_eta_basic_dphi;
TH1F* h_tau_eta_basic_dphi_drap;
TH1F* h_tau_eta_basic_dphi_drap_btag;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_tau_eta_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_delta_R_taulep_basic;
TH1F* h_delta_R_taulep_basic_dphi;
TH1F* h_delta_R_taulep_basic_dphi_drap;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_delta_R_taulep_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_delta_R_lepjet_basic;
TH1F* h_delta_R_lepjet_basic_dphi;
TH1F* h_delta_R_lepjet_basic_dphi_drap;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_delta_R_lepjet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_delta_R_taujet_basic;
TH1F* h_delta_R_taujet_basic_dphi;
TH1F* h_delta_R_taujet_basic_dphi_drap;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_delta_R_taujet_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_sum_pt_basic;
TH1F* h_sum_pt_basic_dphi;
TH1F* h_sum_pt_basic_dphi_drap;
TH1F* h_sum_pt_basic_dphi_drap_btag;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_sum_pt_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_met_basic;
TH1F* h_met_basic_dphi;
TH1F* h_met_basic_dphi_drap;
TH1F* h_met_basic_dphi_drap_btag;
TH1F* h_met_basic_dphi_drap_btag_iso;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_met_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_reco_mass_i_basic;
TH1F* h_reco_mass_i_basic_dphi;
TH1F* h_reco_mass_i_basic_dphi_drap;
TH1F* h_reco_mass_i_basic_dphi_drap_btag;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_reco_mass_i_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_reco_mass_o_basic;
TH1F* h_reco_mass_o_basic_dphi;
TH1F* h_reco_mass_o_basic_dphi_drap;
TH1F* h_reco_mass_o_basic_dphi_drap_btag;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_reco_mass_o_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_tau_matched_1p_basic;
TH1F* h_tau_matched_1p_basic_dphi;
TH1F* h_tau_matched_1p_basic_dphi_drap;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_tau_matched_1p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_tau_matched_3p_basic;
TH1F* h_tau_matched_3p_basic_dphi;
TH1F* h_tau_matched_3p_basic_dphi_drap;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_tau_matched_3p_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_omega_basic;
TH1F* h_omega_basic_dphi;
TH1F* h_omega_basic_dphi_drap;
TH1F* h_omega_basic_dphi_drap_btag;
TH1F* h_omega_basic_dphi_drap_btag_iso;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco;
TH1F* h_omega_basic_dphi_drap_btag_iso_rnn_ptl_j1pt_j2pt_ptbal_mjj_nji_zcen_omega_mlt_ebdt_mreco_tpt;


TH1F* h_lep_phi_basic;
TH1F* h_lep_phi_basic_cuts;
TH1F* h_lep_phi_basic_cuts_tpt;


TH1F* h_tau_phi_basic;
TH1F* h_tau_phi_basic_cuts;
TH1F* h_tau_phi_basic_cuts_tpt;


TH1F* h_tau_nprongs_basic;
TH1F* h_tau_nprongs_basic_cuts;
TH1F* h_tau_nprongs_basic_cuts_tpt;


TH1F* h_trans_lep_mass_basic;
TH1F* h_trans_lep_mass_basic_cuts;
TH1F* h_trans_lep_mass_basic_cuts_tpt;


TH1F* h_Z_pt_truth_i_basic;
TH1F* h_Z_pt_truth_i_basic_cuts;
TH1F* h_Z_pt_truth_i_basic_cuts_tpt;


TH1F* h_Z_pt_truth_o_basic;
TH1F* h_Z_pt_truth_o_basic_cuts;
TH1F* h_Z_pt_truth_o_basic_cuts_tpt;


TH1F* h_rnn_score_1p_basic;
TH1F* h_rnn_score_1p_basic_cuts;
TH1F* h_rnn_score_1p_basic_cuts_tpt;


TH1F* h_rnn_score_3p_basic;
TH1F* h_rnn_score_3p_basic_cuts;
TH1F* h_rnn_score_3p_basic_cuts_tpt;


TH1F* h_jet_n_basic;
TH1F* h_jet_n_basic_cuts;
TH1F* h_jet_n_basic_cuts_tpt;


TH1F* h_n_bjets_basic;
TH1F* h_n_bjets_basic_cuts;
TH1F* h_n_bjets_basic_cuts_tpt;


TH1F* h_lep_iso_basic;
TH1F* h_lep_iso_basic_cuts;
TH1F* h_lep_iso_basic_cuts_tpt;


TH1F* h_delta_phi_basic;
TH1F* h_delta_phi_basic_cuts;
TH1F* h_delta_phi_basic_cuts_tpt;


TH1F* h_Z_pt_reco_i_basic;
TH1F* h_Z_pt_reco_i_basic_cuts;
TH1F* h_Z_pt_reco_i_basic_cuts_tpt;


TH1F* h_Z_pt_reco_o_basic;
TH1F* h_Z_pt_reco_o_basic_cuts;
TH1F* h_Z_pt_reco_o_basic_cuts_tpt;


TH1F* h_n_fake_tracks_basic;
TH1F* h_n_fake_tracks_basic_cuts;
TH1F* h_n_fake_tracks_basic_cuts_tpt;


TH1F* h_n_core_tracks_basic;
TH1F* h_n_core_tracks_basic_cuts;
TH1F* h_n_core_tracks_basic_cuts_tpt;


TH1F* h_n_iso_tracks_basic;
TH1F* h_n_iso_tracks_basic_cuts;
TH1F* h_n_iso_tracks_basic_cuts_tpt;


TH1F* h_n_tracks_basic;
TH1F* h_n_tracks_basic_cuts;
TH1F* h_n_tracks_basic_cuts_tpt;


TH1F* h_delta_y_basic;
TH1F* h_delta_y_basic_cuts;
TH1F* h_delta_y_basic_cuts_tpt;


TH1F* h_Z_centrality_basic;
TH1F* h_Z_centrality_basic_cuts;
TH1F* h_Z_centrality_basic_cuts_tpt;


TH1F* h_pt_bal_basic;
TH1F* h_pt_bal_basic_cuts;
TH1F* h_pt_bal_basic_cuts_tpt;


TH1F* h_mass_jj_basic;
TH1F* h_mass_jj_basic_cuts;
TH1F* h_mass_jj_basic_cuts_tpt;


TH1F* h_n_jets_interval_basic;
TH1F* h_n_jets_interval_basic_cuts;
TH1F* h_n_jets_interval_basic_cuts_tpt;


TH1F* h_ljet0_pt_basic;
TH1F* h_ljet0_pt_basic_cuts;
TH1F* h_ljet0_pt_basic_cuts_tpt;


TH1F* h_ljet1_pt_basic;
TH1F* h_ljet1_pt_basic_cuts;
TH1F* h_ljet1_pt_basic_cuts_tpt;


TH1F* h_ljet2_pt_basic;
TH1F* h_ljet2_pt_basic_cuts;
TH1F* h_ljet2_pt_basic_cuts_tpt;


TH1F* h_ljet3_pt_basic;
TH1F* h_ljet3_pt_basic_cuts;
TH1F* h_ljet3_pt_basic_cuts_tpt;

TH1F* h_gap_jet_pt_basic_cuts_tpt;

TH1F* h_ljet0_eta_basic;
TH1F* h_ljet0_eta_basic_cuts;
TH1F* h_ljet0_eta_basic_cuts_ptl;


TH1F* h_ljet1_eta_basic;
TH1F* h_ljet1_eta_basic_cuts;
TH1F* h_ljet1_eta_basic_cuts_ptl;


TH1F* h_ljet2_eta_basic;
TH1F* h_ljet2_eta_basic_cuts;
TH1F* h_ljet2_eta_basic_cuts_ptl;


TH1F* h_gap_jet_eta_basic;
TH1F* h_gap_jet_eta_basic_cuts;
TH1F* h_gap_jet_eta_basic_cuts_ptl;

TH1F* h_trans_mass_lep_basic;
TH1F* h_trans_mass_lep_basic_cuts;
TH1F* h_trans_mass_lep_basic_cuts_tpt;


TH1F* h_vec_sum_pt_jets_basic;
TH1F* h_vec_sum_pt_jets_basic_cuts;
TH1F* h_vec_sum_pt_jets_basic_cuts_tpt;


TH1F* h_ratio_zpt_sumjetpt_basic;
TH1F* h_ratio_zpt_sumjetpt_basic_cuts;
TH1F* h_ratio_zpt_sumjetpt_basic_cuts_tpt;

#endif

TH1F* h_delta_phi;
TH1F* h_delta_y;
TH1F* h_n_bjets;
TH1F* h_lepiso;
TH1F* h_rnn_score_1p;
TH1F* h_rnn_score_3p;
TH1F* h_lep_pt;
TH1F* h_ljet0_pt;
TH1F* h_ljet1_pt;
TH1F* h_pt_bal;
TH1F* h_mass_jj;
TH1F* h_n_jets_interval;
TH1F* h_Z_centrality;
TH1F* h_omega;
TH1F* h_leptau_mass;
TH1F* h_eBDT;
TH1F* h_reco_mass_i;
TH1F* h_reco_mass_o;
TH1F* h_reco_mass;
TH1F* h_tau_pt;


#ifdef WEIGHTSYSTEMATICS
TH1F* h_mass_jj_elec_0_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_0_EL_EFF_ID_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_TightLLH_d0z0_v13;
TH1F* h_mass_jj_elec_0_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Iso_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_Isolation_TightLLH_d0z0_v13_FCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_0_EL_EFF_Reco_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_offline_RecoTrk;
TH1F* h_mass_jj_elec_0_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1down_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_elec_0_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR_1up_EleEffSF_SINGLE_E_2015_e24_lhmedium_L1EM20VH_OR_e60_lhmedium_OR_e120_lhloose_2016_2018_e26_lhtight_nod0_ivarloose_OR_e60_lhmedium_nod0_OR_e140_lhloose_nod0_TightLLH_d0z0_v13_isolFCTight;
TH1F* h_mass_jj_PRW_DATASF_1down_pileup_combined_weight;
TH1F* h_mass_jj_PRW_DATASF_1up_pileup_combined_weight;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1down_central_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1down_central_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1up_central_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_JvtEfficiency_1up_central_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1down_forward_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1down_forward_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1up_forward_jets_global_effSF_JVT;
TH1F* h_mass_jj_jet_JET_fJvtEfficiency_1up_forward_jets_global_ineffSF_JVT;
TH1F* h_mass_jj_tau_0_TAUS_TRUEELECTRON_EFF_ELEBDT_STAT_1down_TauEffSF_LooseEleBDT_electron;
TH1F* h_mass_jj_tau_0_TAUS_TRUEELECTRON_EFF_ELEBDT_STAT_1up_TauEffSF_LooseEleBDT_electron;
TH1F* h_mass_jj_tau_0_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1down_TauEffSF_LooseEleBDT_electron;
TH1F* h_mass_jj_tau_0_TAUS_TRUEELECTRON_EFF_ELEBDT_SYST_1up_TauEffSF_LooseEleBDT_electron;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RECO_TOTAL_1down_TauEffSF_reco;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RECO_TOTAL_1up_TauEffSF_reco;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT2025_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT2025_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT2530_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT2530_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT3040_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPT3040_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPTGE40_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_1PRONGSTATSYSTPTGE40_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT2025_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT2025_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT2530_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT2530_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT3040_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPT3040_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPTGE40_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_3PRONGSTATSYSTPTGE40_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_HIGHPT_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_HIGHPT_1up_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_SYST_1down_TauEffSF_JetRNNmedium;
TH1F* h_mass_jj_tau_0_TAUS_TRUEHADTAU_EFF_RNNID_SYST_1up_TauEffSF_JetRNNmedium;
#endif

#endif
