// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold4
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Tue Apr 21 21:45:32 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 34501
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold4Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold4Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold4Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold4Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold4Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold4Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold4Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.751773,0.0503547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238708,-0.0522584) , 
5, 19.0218, 1, 0, 0.691731,0.191731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386381,-0.0227237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0665438,-0.0866912) , 
5, 15.5171, 1, 0, 0.291712,-0.208288) , 
2, 0.0407384, 1, 0, 0.507257,0.00725699)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465596,-0.0103515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798692,0.0556491) , 
1, 3.63061, 1, 0, 0.712947,0.192805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444242,-0.0102182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0939832,-0.0740107) , 
5, 14.5409, 1, 0, 0.343322,-0.14228) , 
2, 0.0296232, 1, 0, 0.50925,0.00814231)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776628,0.0469034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351316,-0.0313432) , 
5, 14.7884, 1, 0, 0.711042,0.172595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455557,-0.00668814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152,-0.0597461) , 
5, 9.97315, 1, 0, 0.313873,-0.15505) , 
2, 0.0314746, 1, 0, 0.495022,-0.00561117)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531071,-0.00104406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827276,0.0531142) , 
1, 3.86773, 1, 0, 0.730144,0.173133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257296,-0.0414038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482861,0.0033749) , 
0, 1665.73, 1, 0, 0.308815,-0.153713) , 
2, 0.0277717, 1, 0, 0.479121,-0.0215978)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700469,0.033174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381979,-0.0297843) , 
3, 0.308633, 1, 0, 0.634474,0.0981141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394247,-0.0141147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14977,-0.0555637) , 
5, 5.51656, 1, 0, 0.223806,-0.208399) , 
2, 0.0610978, 1, 0, 0.497466,-0.00414473)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79156,0.0407017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427945,-0.00785785) , 
2, 0.0277619, 1, 0, 0.594109,0.0681345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0974041,-0.0633146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271599,-0.0334019) , 
0, 1464.89, 1, 0, 0.143578,-0.26061) , 
5, 15.4542, 1, 0, 0.495117,-0.00409853)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727934,0.030906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314776,-0.0297197) , 
5, 14.2655, 1, 0, 0.641337,0.0867594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369419,-0.0161758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112279,-0.0535425) , 
5, 10.1768, 1, 0, 0.246103,-0.158461) , 
2, 0.0536584, 1, 0, 0.49186,-0.00598307)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691992,0.0260131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267111,-0.03253) , 
2, 0.0869611, 1, 0, 0.61764,0.0746015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2545,-0.0310733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0781789,-0.0614089) , 
5, 23.8244, 1, 0, 0.182677,-0.196487) , 
5, 13.9303, 1, 0, 0.503393,0.00339729)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808896,0.0374399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306749,-0.0287314) , 
5, 17.1461, 1, 0, 0.745139,0.132264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288326,-0.0280727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513839,0.0123289) , 
0, 1524.13, 1, 0, 0.348628,-0.0802765) , 
2, 0.0240559, 1, 0, 0.497898,-0.00026362)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900324,0.0534506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497325,0.00318561) , 
2, 0.0240688, 1, 0, 0.672301,0.112419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246844,-0.0346002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566055,0.0176413) , 
1, 5.48253, 1, 0, 0.285579,-0.125334) , 
5, 9.51061, 1, 0, 0.517348,0.0171557)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510751,-0.00520205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73334,0.0327723) , 
0, 1244.82, 1, 0, 0.623082,0.0631184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372358,-0.011153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104493,-0.048501) , 
5, 7.82593, 1, 0, 0.215284,-0.141757) , 
2, 0.0703172, 1, 0, 0.505812,0.00420276)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452747,-0.0176842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728722,0.0268199) , 
1, 3.86777, 1, 0, 0.641472,0.0559298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325482,-0.0167111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0479423,-0.054456) , 
5, 15.2658, 1, 0, 0.236965,-0.119668) , 
2, 0.0573747, 1, 0, 0.497362,-0.0066285)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414214,-0.0186655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635367,0.0173293) , 
1, 4.13665, 1, 0, 0.544714,0.0106215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.038714,-0.0617402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15172,-0.0399205) , 
4, 0.0201643, 1, 0, 0.0909324,-0.207127) , 
5, 21.6065, 1, 0, 0.482977,-0.0190031)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696685,0.0237589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316646,-0.0169377) , 
5, 10.2352, 1, 0, 0.556514,0.0411312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261452,-0.0420567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450832,-0.011943) , 
0, 1266.22, 1, 0, 0.3174,-0.149325) , 
3, 0.308603, 1, 0, 0.507435,0.00203963)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782093,0.0288869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477264,-0.0241128) , 
3, 0.308579, 1, 0, 0.720813,0.0763026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455401,-0.00434435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181483,-0.0318557) , 
5, 8.95358, 1, 0, 0.31965,-0.0746059) , 
2, 0.0277568, 1, 0, 0.482063,-0.0135097)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20977,-0.0461429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37858,-0.0155374) , 
1, 3.12774, 1, 0, 0.340525,-0.0981239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662215,0.0212432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0792186,-0.0537249) , 
5, 22.5882, 1, 0, 0.597124,0.0598739) , 
0, 997.376, 1, 0, 0.510596,0.00659505)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620316,0.011406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34758,-0.0325854) , 
4, 1.03905, 1, 0, 0.58063,0.0212776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.078463,-0.047815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173934,-0.0291358) , 
1, 4.58806, 1, 0, 0.112333,-0.151372) , 
5, 18.0136, 1, 0, 0.502953,-0.00736005)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644754,0.0149294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204691,-0.0239412) , 
5, 13.9306, 1, 0, 0.540624,0.028967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306308,-0.0544463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189633,-0.0324049) , 
2, 0.0330844, 1, 0, 0.252791,-0.198501) , 
3, 0.376472, 1, 0, 0.506191,0.00175563)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73394,0.0251491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298322,-0.010353) , 
2, 0.0555239, 1, 0, 0.579249,0.0535251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302739,-0.0307822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560312,0.00157005) , 
0, 1247.63, 1, 0, 0.412475,-0.0733424) , 
3, 0.154324, 1, 0, 0.489861,-0.014474)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531975,0.000297155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793431,0.0339974) , 
1, 5.16528, 1, 0, 0.593252,0.0336899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193439,-0.023226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127218,-0.0520898) , 
4, 0.998242, 1, 0, 0.179611,-0.118796) , 
2, 0.0795842, 1, 0, 0.495726,-0.0022625)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808728,0.029918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471981,-0.0179206) , 
3, 0.339382, 1, 0, 0.749777,0.0834895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394934,-0.00921273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163808,-0.0489327) , 
3, 0.401153, 1, 0, 0.37632,-0.0535381) , 
2, 0.0185174, 1, 0, 0.490269,-0.0117285)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658878,0.0131993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146572,-0.0316093) , 
5, 21.3991, 1, 0, 0.591762,0.0339631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397108,0.00109514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120214,-0.037803) , 
5, 4.59582, 1, 0, 0.181966,-0.104708) , 
2, 0.0795694, 1, 0, 0.492469,0.000363157)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715159,0.0211908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487511,-0.0143733) , 
4, 0.913362, 1, 0, 0.630893,0.0331616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34859,-0.0137466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152697,-0.0590834) , 
4, 0.621391, 1, 0, 0.332746,-0.0690098) , 
5, 7.82973, 1, 0, 0.49118,-0.0147165)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357572,-0.0220084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820632,0.0303177) , 
4, 0.109099, 1, 0, 0.767102,0.0933505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465437,-0.00141335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0721064,-0.0441007) , 
5, 16.5939, 1, 0, 0.36651,-0.039334) , 
2, 0.0203692, 1, 0, 0.504012,0.00620954)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682546,0.0138343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350088,-0.0302224) , 
4, 1.04508, 1, 0, 0.624965,0.0242558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219717,-0.0279809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494709,0.00777045) , 
0, 1900.53, 1, 0, 0.266459,-0.0794144) , 
5, 9.64307, 1, 0, 0.477636,-0.0183476)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693423,0.00889838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300439,-0.0138363) , 
2, 0.0240727, 1, 0, 0.446007,-0.0219129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9414,0.0534121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453721,0.00349733) , 
2, 0.0369948, 1, 0, 0.732178,0.114649) , 
1, 5.16536, 1, 0, 0.505615,0.00653216)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413755,-0.0112696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643648,0.0128383) , 
1, 3.74117, 1, 0, 0.57911,0.0234549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20447,-0.0162874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0928614,-0.0447632) , 
3, 0.234015, 1, 0, 0.159368,-0.0994794) , 
2, 0.0925725, 1, 0, 0.496634,-0.000700541)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827925,0.0286268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384193,-0.00286036) , 
2, 0.0240168, 1, 0, 0.552233,0.0320541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349628,-0.0132809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302476,-0.0443192) , 
4, 0.777137, 1, 0, 0.33333,-0.101923) , 
3, 0.283905, 1, 0, 0.496181,-0.00225179)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343885,-0.0353906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691345,0.0171664) , 
1, 2.84674, 1, 0, 0.66593,0.0534273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393736,-0.0054359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220807,-0.0486553) , 
4, 0.68797, 1, 0, 0.372614,-0.0412838) , 
5, 5.94617, 1, 0, 0.493636,-0.00220616)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606399,0.0175558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464655,-0.018469) , 
4, 0.954833, 1, 0, 0.580297,0.0401908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383594,-0.0056519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367144,-0.0332923) , 
4, 0.798208, 1, 0, 0.378194,-0.0601916) , 
3, 0.216048, 1, 0, 0.502629,0.00161421)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70285,0.0158998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467236,-0.0143558) , 
4, 0.935371, 1, 0, 0.625386,0.0224737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298834,-0.0130311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274943,-0.0380701) , 
4, 0.4665, 1, 0, 0.294083,-0.0668114) , 
5, 8.32169, 1, 0, 0.471182,-0.0190839)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647042,0.00960809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324386,-0.0191802) , 
2, 0.00740319, 1, 0, 0.366422,-0.0611508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627815,0.016388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269109,-0.0331097) , 
3, 0.364195, 1, 0, 0.597525,0.0452555) , 
1, 4.03022, 1, 0, 0.504951,0.00263175)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476686,-0.00321581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781458,0.0316892) , 
0, 2316.7, 1, 0, 0.510871,0.00203994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113897,-0.0502503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38755,-0.0203612) , 
1, 3.67012, 1, 0, 0.312902,-0.114305) , 
4, 1.0424, 1, 0, 0.488693,-0.0109937)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832037,0.0285396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44521,-0.0160635) , 
3, 0.357916, 1, 0, 0.78216,0.0770701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562326,0.00685641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281466,-0.0140209) , 
5, 5.53193, 1, 0, 0.390023,-0.0195193) , 
2, 0.0185174, 1, 0, 0.509258,0.00985003)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791747,0.018984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370966,-0.0334685) , 
3, 0.388804, 1, 0, 0.750288,0.0437002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422803,1.10954e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295359,-0.0190533) , 
3, 0.160482, 1, 0, 0.355355,-0.0393004) , 
2, 0.0203588, 1, 0, 0.481786,-0.0127292)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713306,0.0230043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18622,-0.0207246) , 
5, 14.8011, 1, 0, 0.584385,0.0506445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267001,-0.0269993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474038,-0.00336666) , 
0, 912.938, 1, 0, 0.418296,-0.0371149) , 
3, 0.154324, 1, 0, 0.496261,0.00408047)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153238,-0.0270177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512473,0.0020373) , 
4, 0.0886075, 1, 0, 0.455922,-0.00523334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814782,0.0932524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685191,0.0114299) , 
0, 1360.29, 1, 0, 0.700022,0.0741825) , 
1, 4.94207, 1, 0, 0.526105,0.0176001)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693291,0.00993838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345815,-0.00867937) , 
5, 7.96072, 1, 0, 0.517293,0.00355308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578352,0.00261012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211415,-0.0378695) , 
5, 2.06357, 1, 0, 0.305107,-0.109408) , 
4, 1.04341, 1, 0, 0.491888,-0.00997146)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172362,-0.0439546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362297,-0.012749) , 
1, 3.01302, 1, 0, 0.317065,-0.0735218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764591,0.0253718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502499,0.00175084) , 
5, 3.56703, 1, 0, 0.572129,0.0301213) , 
0, 914.371, 1, 0, 0.511439,0.00546028)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180057,-0.0544293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649401,0.00827464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320703,-0.0110982) , 
5, 7.93875, 1, 0, 0.496437,-0.000351966) , 
1, 2.39779, 1, 0, 0.487174,-0.00678244)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397179,-0.0152843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678185,0.0122403) , 
1, 3.29946, 1, 0, 0.63078,0.0268763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236079,-0.00593287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17669,-0.0318132) , 
4, 0.954355, 1, 0, 0.22078,-0.0456901) , 
2, 0.0629593, 1, 0, 0.499163,0.00358128)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130038,-0.0292685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529734,0.00342171) , 
4, 0.0447978, 1, 0, 0.475851,0.00102682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716965,0.0119312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.833018,0.0552858) , 
3, 0.0855369, 1, 0, 0.78794,0.125964) , 
0, 2296.24, 1, 0, 0.509571,0.0145258)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473164,0.00415617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0790015,-0.0351821) , 
2, 0.0262529, 1, 0, 0.156041,-0.06739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614876,0.0119718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271861,-0.0216044) , 
4, 1.10671, 1, 0, 0.58228,0.0329611) , 
4, 0.0670481, 1, 0, 0.516401,0.017451)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686174,0.0116781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260222,-0.0147393) , 
5, 11.8879, 1, 0, 0.551606,0.0140052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344106,-0.0117203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37938,-0.0551209) , 
1, 5.28572, 1, 0, 0.350077,-0.0728903) , 
3, 0.234586, 1, 0, 0.483121,-0.015524)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379197,-0.00115515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428025,-0.0188113) , 
4, 0.777142, 1, 0, 0.395385,-0.0280664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.851602,0.0357491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500235,-0.000471029) , 
5, 4.62878, 1, 0, 0.617393,0.0396716) , 
1, 4.33204, 1, 0, 0.503578,0.0049447)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251961,-0.0457519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0777661,-0.0228979) , 
2, 0.0333031, 1, 0, 0.134176,-0.0899361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589307,0.00502516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295292,-0.0206864) , 
3, 0.376529, 1, 0, 0.555899,0.00741715) , 
4, 0.0448581, 1, 0, 0.507354,-0.00378914)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478772,-0.00078017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424907,-0.0160557) , 
4, 0.909595, 1, 0, 0.466684,-0.0163484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.914875,0.0390862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509562,0.00336289) , 
2, 0.0294801, 1, 0, 0.730707,0.0638396) , 
0, 2069.29, 1, 0, 0.504752,-0.00478663)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775686,0.0214861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471943,-0.00107468) , 
5, 4.28617, 1, 0, 0.570518,0.0221894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358592,-0.00770589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393914,-0.0312098) , 
1, 5.24478, 1, 0, 0.363862,-0.0431006) , 
3, 0.253046, 1, 0, 0.50478,0.00142035)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793089,0.0335807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333719,-0.00435921) , 
5, 8.13938, 1, 0, 0.437589,0.0164444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628791,-0.00389475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356021,-0.0477244) , 
5, 4.77162, 1, 0, 0.549075,-0.059715) , 
4, 0.666188, 1, 0, 0.486492,-0.0169625)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399773,-0.00921223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649225,0.00730595) , 
1, 3.8654, 1, 0, 0.566331,0.00536295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150313,-0.0125197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182561,-0.0317182) , 
4, 0.622546, 1, 0, 0.164069,-0.0719505) , 
2, 0.0962089, 1, 0, 0.498333,-0.00770607)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549428,0.0044603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652756,-0.0256299) , 
1, 5.97868, 1, 0, 0.560505,0.00602739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0528572,-0.0453679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0496874,-0.0335907) , 
3, 0.252751, 1, 0, 0.0517015,-0.0947258) , 
5, 23.7751, 1, 0, 0.502328,-0.00549272)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554787,0.00409301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13501,-0.0314462) , 
2, 0.118394, 1, 0, 0.514515,0.00362387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411715,-0.0140929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235748,-0.0386976) , 
3, 0.22191, 1, 0, 0.338704,-0.0909017) , 
4, 0.998618, 1, 0, 0.488383,-0.0104261)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629696,0.00502915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0928695,-0.0291235) , 
5, 23.9074, 1, 0, 0.576877,0.00962143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239011,-0.00582721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0908321,-0.0374207) , 
3, 0.196238, 1, 0, 0.171137,-0.0603979) , 
2, 0.0925872, 1, 0, 0.497942,-0.00400057)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389154,-0.0409642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218531,-0.00671014) , 
2, 0.0429505, 1, 0, 0.311453,-0.102305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644072,0.0180546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490995,-0.00332661) , 
3, 0.104944, 1, 0, 0.542768,0.0129119) , 
0, 820.534, 1, 0, 0.517671,0.000411236)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394459,-0.0271768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255981,-0.0112853) , 
5, 5.69164, 1, 0, 0.316047,-0.0695309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591983,0.0101213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350358,-0.0197983) , 
4, 1.04318, 1, 0, 0.562075,0.0212462) , 
0, 869.157, 1, 0, 0.517036,0.00462827)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505982,-0.000528413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124054,-0.0274247) , 
2, 0.120363, 1, 0, 0.473239,-0.00831351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979028,0.0944008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712166,0.0136312) , 
0, 2903.16, 1, 0, 0.796992,0.109984) , 
0, 2475.83, 1, 0, 0.504473,0.00309932)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793424,0.0218958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406922,-0.00584436) , 
3, 0.314456, 1, 0, 0.713898,0.0533336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434555,0.00247729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499856,-0.0147887) , 
4, 0.643572, 1, 0, 0.455873,-0.0116927) , 
5, 2.37809, 1, 0, 0.500282,-0.000500989)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68038,0.0111553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499612,-0.00863142) , 
4, 0.888881, 1, 0, 0.621299,0.0169365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205407,-0.0055193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19813,-0.0321561) , 
4, 0.222232, 1, 0, 0.203591,-0.0395833) , 
5, 13.6608, 1, 0, 0.510561,0.00195266)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280464,-0.00329776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282781,-0.0351245) , 
4, 0.645179, 1, 0, 0.281474,-0.0677814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667345,0.0268237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510502,0.000858949) , 
3, 0.0679559, 1, 0, 0.544408,0.0210566) , 
1, 3.19305, 1, 0, 0.508138,0.00880228)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449808,-0.00639211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689768,0.0111002) , 
1, 3.9086, 1, 0, 0.610244,0.0174367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0978959,-0.027929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392347,0.00261018) , 
0, 1818.28, 1, 0, 0.151612,-0.0535591) , 
5, 15.0175, 1, 0, 0.504385,0.00104979)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77831,0.0138163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339062,-0.0237444) , 
3, 0.413466, 1, 0, 0.744257,0.0320691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291919,-0.0127007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58106,0.0213769) , 
0, 1997.2, 1, 0, 0.328258,-0.029567) , 
2, 0.0277762, 1, 0, 0.499668,-0.00417024)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506349,0.0106965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663927,-0.00294621) , 
1, 4.53237, 1, 0, 0.575761,0.0174885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249195,0.00178094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109519,-0.0248035) , 
3, 0.148126, 1, 0, 0.164141,-0.0369372) , 
2, 0.0962907, 1, 0, 0.504793,0.00810493)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648739,-0.000488726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529746,0.0119139) , 
3, 0.203667, 1, 0, 0.604564,0.0158747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104825,-0.011134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17528,-0.0243745) , 
0, 1203.31, 1, 0, 0.134911,-0.0451424) , 
5, 17.0595, 1, 0, 0.511944,0.00384157)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289834,-0.0165805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487321,0.00611218) , 
1, 2.99859, 1, 0, 0.464557,0.011563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683925,-0.00694874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468378,-0.0388883) , 
3, 0.265299, 1, 0, 0.6386,-0.0484929) , 
0, 1982.71, 1, 0, 0.497574,0.000170054)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765669,0.00804357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386568,-0.00837863) , 
2, 0.0185174, 1, 0, 0.512217,-0.0117866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566225,-0.00854536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182906,-0.0381194) , 
5, 2.38421, 1, 0, 0.32367,-0.0942139) , 
4, 1.02046, 1, 0, 0.487102,-0.022766)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617718,0.00120206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510021,0.0227919) , 
3, 0.246877, 1, 0, 0.589174,0.0252415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157682,-0.00448211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174557,-0.0226248) , 
4, 0.64359, 1, 0, 0.164961,-0.0387656) , 
2, 0.0962414, 1, 0, 0.510537,0.0133764)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638264,0.00313578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.993419,0.0637915) , 
1, 5.84568, 1, 0, 0.674517,0.0265709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424983,-3.25937e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358824,-0.0345778) , 
4, 0.688378, 1, 0, 0.413004,-0.0210154) , 
5, 4.47451, 1, 0, 0.500863,-0.00502816)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706842,0.0103781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386966,-0.0141062) , 
3, 0.345187, 1, 0, 0.654642,0.0198604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352028,-0.00413729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302657,-0.02526) , 
4, 0.577419, 1, 0, 0.345149,-0.0226825) , 
5, 7.13318, 1, 0, 0.499409,-0.00147793)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205222,-0.0388704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461245,0.00699434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589008,-0.0103018) , 
1, 4.66778, 1, 0, 0.511223,0.00175327) , 
1, 2.48768, 1, 0, 0.500762,-0.00280623)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412203,-0.00477061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167021,-0.0356629) , 
3, 0.450519, 1, 0, 0.396826,-0.0235013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633282,0.0360165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619056,0.00249408) , 
1, 4.51136, 1, 0, 0.620589,0.0194884) , 
1, 4.3549, 1, 0, 0.509053,-0.00194014)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193618,-0.036738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716821,0.0204817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489259,-0.0015462) , 
5, 1.13921, 1, 0, 0.505918,0.000641274) , 
1, 2.48739, 1, 0, 0.4949,-0.00386272)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667091,0.0053762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270441,-0.00794735) , 
2, 0.0481377, 1, 0, 0.514057,0.00106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669275,0.00431311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354267,-0.0264178) , 
5, 0.772619, 1, 0, 0.433391,-0.0674434) , 
4, 0.932181, 1, 0, 0.497083,-0.0133545)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366432,0.00329207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368628,-0.0136631) , 
1, 3.42929, 1, 0, 0.367611,-0.0205295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753209,0.018991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35405,-0.00601021) , 
5, 9.28796, 1, 0, 0.606236,0.0319704) , 
1, 4.06761, 1, 0, 0.510724,0.0109568)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786462,0.0241226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566376,-0.00137752) , 
4, 0.906718, 1, 0, 0.690098,0.0429359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557466,-0.0205165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256072,0.0028552) , 
2, 0.0296279, 1, 0, 0.377236,-0.0247657) , 
5, 5.68662, 1, 0, 0.499497,0.00169081)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544299,-0.00405313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856954,0.0333712) , 
1, 4.33169, 1, 0, 0.701853,0.040268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419229,0.000869981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387319,-0.0227104) , 
4, 0.643572, 1, 0, 0.411976,-0.0147326) , 
5, 4.4743, 1, 0, 0.500814,0.00212328)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731434,0.00310655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.02317,0.0997733) , 
2, 0.0137776, 1, 0, 0.766209,0.0422072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332029,0.0345767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401345,-0.00577077) , 
1, 2.62199, 1, 0, 0.398138,-0.0143845) , 
2, 0.0166572, 1, 0, 0.49336,0.000255989)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818528,0.0290923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454705,-0.00578746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74435,0.0183144) , 
1, 5.71928, 1, 0, 0.485262,-0.0111849) , 
2, 0.00370349, 1, 0, 0.499172,-0.0069173)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452426,-0.0152981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20328,0.0088539) , 
2, 0.070311, 1, 0, 0.376623,-0.0330444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689191,0.0112419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125134,-0.0233487) , 
5, 21.4002, 1, 0, 0.613238,0.0237882) , 
0, 1107.45, 1, 0, 0.511201,-0.000719919)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589337,0.00376008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444508,-0.0311812) , 
3, 0.158424, 1, 0, 0.56269,-0.0098049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548946,0.0170077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136923,-0.0194817) , 
2, 0.0832275, 1, 0, 0.448981,0.033582) , 
3, 0.197492, 1, 0, 0.516863,0.00768089)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525236,0.00245601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467901,-0.0132064) , 
4, 0.909589, 1, 0, 0.51258,-0.00374861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431315,0.0470054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330917,0.0088344) , 
3, 0.446488, 1, 0, 0.385778,0.0994323) , 
3, 0.388874, 1, 0, 0.502366,0.00456234)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435702,-0.0108724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559633,-0.0535433) , 
1, 5.94399, 1, 0, 0.442094,-0.0433301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692527,-0.0124053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786806,0.0265146) , 
1, 5.9808, 1, 0, 0.748855,0.0272744) , 
0, 2564.02, 1, 0, 0.46709,-0.037577)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535567,0.00496941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27729,-0.017148) , 
3, 0.370315, 1, 0, 0.504749,0.00708062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607492,-0.0478004) , 
1, 6.5469, 1, 0, 0.510006,-0.000377341)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477655,-0.00767781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403065,0.00622287) , 
3, 0.203681, 1, 0, 0.447531,-0.00736755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73688,0.00787951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655672,0.0682184) , 
3, 0.257222, 1, 0, 0.723735,0.0561605) , 
1, 5.08548, 1, 0, 0.514111,0.00794613)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67335,-0.00291336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46286,-0.0156883) , 
3, 0.234545, 1, 0, 0.602934,-0.0258406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527458,0.0293853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19006,0.000903999) , 
5, 5.08874, 1, 0, 0.278364,0.0337729) , 
2, 0.0555435, 1, 0, 0.493251,-0.00569526)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762385,0.0170764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8104,-0.0358743) , 
1, 5.54535, 1, 0, 0.771808,0.0316242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339402,-0.00236386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404668,-0.019741) , 
4, 0.731343, 1, 0, 0.364202,-0.0332086) , 
2, 0.018508, 1, 0, 0.485154,-0.0139702)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459249,0.0111304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482196,-0.00629499) , 
4, 0.79931, 1, 0, 0.466096,0.0190648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666411,-0.0037125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335969,-0.0372764) , 
3, 0.282285, 1, 0, 0.607765,-0.033427) , 
1, 4.99389, 1, 0, 0.508219,0.00345728)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367695,-0.00860421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60049,0.00199864) , 
0, 988.31, 1, 0, 0.525857,-0.0050442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106749,-0.0310123) , 
2, 0.120302, 1, 0, 0.491017,-0.0114021)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207241,-0.0297134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442666,0.00638629) , 
1, 2.707, 1, 0, 0.415992,0.00840725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673159,-0.0173054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298235,0.00259362) , 
2, 0.0573589, 1, 0, 0.554894,-0.0331779) , 
1, 4.38564, 1, 0, 0.48495,-0.0122376)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659812,0.00887963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.983042,0.0660065) , 
1, 5.8719, 1, 0, 0.694978,0.0466406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401519,-0.00276896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570503,-0.0329854) , 
1, 5.97879, 1, 0, 0.414728,-0.0169621) , 
5, 4.55423, 1, 0, 0.502963,0.00306284)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263941,-0.0265645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584043,0.00641103) , 
1, 2.94574, 1, 0, 0.558078,0.0115292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309569,-0.0143922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298245,-0.0794267) , 
0, 2050.47, 1, 0, 0.308182,-0.0800228) , 
3, 0.283944, 1, 0, 0.495055,-0.0115602)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431329,4.67882e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56199,-0.0132557) , 
1, 4.70646, 1, 0, 0.473155,-0.0135836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798484,0.042051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.756196,0.00978893) , 
0, 2910.86, 1, 0, 0.775915,0.0745656) , 
1, 6.05982, 1, 0, 0.493966,-0.00752437)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8037,0.0198044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608467,-0.000394265) , 
4, 0.843066, 1, 0, 0.672292,0.0190194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415748,-0.000993116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302143,-0.038204) , 
4, 0.686994, 1, 0, 0.394335,-0.0248355) , 
5, 4.55589, 1, 0, 0.487204,-0.0101829)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575127,0.00898126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107856,-0.0143788) , 
5, 22.5879, 1, 0, 0.497937,0.0212603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341601,-0.0218969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627752,-0.00372966) , 
0, 1034.42, 1, 0, 0.521416,-0.0362146) , 
4, 0.798964, 1, 0, 0.505364,0.00307936)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784018,0.0481145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82655,0.00683309) , 
4, 0.420728, 1, 0, 0.814209,0.0653615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687271,-0.0235578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437687,-0.000101971) , 
2, 0.0126896, 1, 0, 0.468081,-0.00877624) , 
2, 0.00740698, 1, 0, 0.505458,-0.000770284)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333956,-0.0160082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325638,0.0129942) , 
4, 0.972328, 1, 0, 0.332711,-0.0410222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724012,0.0183789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284486,-0.00352131) , 
5, 12.5224, 1, 0, 0.600016,0.040523) , 
1, 3.82029, 1, 0, 0.514265,0.0143635)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479302,0.00392438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641402,-0.0201442) , 
1, 5.97865, 1, 0, 0.49438,0.00580945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587862,-0.00617735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3417,-0.0257082) , 
3, 0.265434, 1, 0, 0.521498,-0.0395971) , 
4, 0.798209, 1, 0, 0.503023,-0.00866136)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747288,0.0156779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326827,-0.0057635) , 
5, 8.3316, 1, 0, 0.483159,0.0078277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838092,0.0126558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415757,-0.0165046) , 
2, 0.0147979, 1, 0, 0.515312,-0.0357359) , 
4, 0.7982, 1, 0, 0.493591,-0.00630595)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561448,-0.0334619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321223,0.00449382) , 
2, 0.014814, 1, 0, 0.383111,-0.0196439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601078,0.0106553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715435,-0.0226847) , 
0, 2377.66, 1, 0, 0.615478,0.0247805) , 
4, 0.511079, 1, 0, 0.509745,0.00456618)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708409,-0.00374872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507157,0.0143009) , 
2, 0.0271449, 1, 0, 0.635159,0.0128317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309467,-0.0301206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200233,-0.00265112) , 
5, 3.67679, 1, 0, 0.224241,-0.0338811) , 
2, 0.0610763, 1, 0, 0.49949,-0.00259109)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496413,0.00441356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208931,-0.0259259) , 
3, 0.42586, 1, 0, 0.475784,0.00723866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53822,-0.0553337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695084,-0.00524698) , 
0, 2101.14, 1, 0, 0.641729,-0.072344) , 
1, 5.64004, 1, 0, 0.499387,-0.00408055)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896677,0.0472797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501282,-0.00115049) , 
2, 0.00369948, 1, 0, 0.515344,0.00119303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232884,-0.00992485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226873,-0.0419971) , 
1, 4.02177, 1, 0, 0.230302,-0.0865464) , 
3, 0.407292, 1, 0, 0.494903,-0.00509919)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291359,-0.028844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0718364,-0.0221243) , 
5, 19.071, 1, 0, 0.131376,-0.0564083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504389,0.0397725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568176,-0.000341148) , 
4, 0.142113, 1, 0, 0.564521,0.00666771) , 
4, 0.0665586, 1, 0, 0.506486,-0.00178367)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535044,0.00156453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235473,-0.0307203) , 
4, 1.09853, 1, 0, 0.518607,-0.000781451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396288,0.0523532) , 
4, 1.24088, 1, 0, 0.51421,0.00435605)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760546,-0.010942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720233,0.0195653) , 
3, 0.141945, 1, 0, 0.739744,0.0207104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298826,-0.00145403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335263,-0.0198505) , 
4, 0.776786, 1, 0, 0.31174,-0.0290355) , 
2, 0.0277762, 1, 0, 0.483277,-0.00909814)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610913,0.0124816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0906468,-0.019474) , 
5, 20.2105, 1, 0, 0.478462,0.022727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630406,0.000811327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318457,-0.0293539) , 
5, 5.00677, 1, 0, 0.551278,-0.019337) , 
4, 0.68797, 1, 0, 0.509088,0.00503528)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653779,-0.0033142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476906,0.0225321) , 
2, 0.0443925, 1, 0, 0.635352,-0.00070967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303909,0.0143176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210214,-0.015191) , 
3, 0.049398, 1, 0, 0.222419,-0.0349853) , 
2, 0.053692, 1, 0, 0.474248,-0.0140821)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398665,-0.00294236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499438,-0.0286453) , 
1, 4.95994, 1, 0, 0.408993,-0.0182427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65736,0.00322848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630908,0.0304312) , 
3, 0.25926, 1, 0, 0.652098,0.0275638) , 
0, 1489.63, 1, 0, 0.486971,-0.00354985)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542291,0.00371839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.812931,0.0300724) , 
1, 5.65455, 1, 0, 0.582886,0.0228311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450607,-0.0311588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412816,-0.00289865) , 
3, 0.197079, 1, 0, 0.421498,-0.0309165) , 
3, 0.154308, 1, 0, 0.497838,-0.00549297)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827311,0.0337736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412167,0.000240125) , 
5, 5.68833, 1, 0, 0.486622,0.0196025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727439,0.0305582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470003,-0.0139852) , 
5, 0.771042, 1, 0, 0.510965,-0.0228741) , 
4, 0.797895, 1, 0, 0.494651,0.00559211)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172468,-0.043212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0958494,0.00166893) , 
2, 0.0371963, 1, 0, 0.125381,-0.0531211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645779,-0.00446041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530648,0.00973605) , 
5, 3.8871, 1, 0, 0.569675,0.0166497) , 
4, 0.0447061, 1, 0, 0.511017,0.00743815)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475915,-0.00679387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751566,0.0134948) , 
1, 5.32373, 1, 0, 0.536833,-0.00867449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369221,0.00263352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601676,0.0487089) , 
1, 4.81894, 1, 0, 0.417679,0.0416658) , 
3, 0.240738, 1, 0, 0.501174,0.00639087)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430117,-0.00886264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737651,0.0135531) , 
1, 5.46683, 1, 0, 0.477734,-0.0178207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583588,0.018005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261832,-0.022078) , 
3, 0.339437, 1, 0, 0.527007,0.0339117) , 
4, 0.865583, 1, 0, 0.489427,-0.00554383)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574384,0.00203295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449913,-0.0175467) , 
3, 0.149373, 1, 0, 0.532714,-0.0149475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58066,0.0340068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257572,-0.0104435) , 
5, 6.78244, 1, 0, 0.380869,0.0304355) , 
3, 0.246919, 1, 0, 0.489194,-0.0019405)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735844,0.00804639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629075,0.0391712) , 
3, 0.24039, 1, 0, 0.705814,0.0586252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426918,0.000421468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580001,-0.0263651) , 
1, 5.3398, 1, 0, 0.455952,-0.0146677) , 
5, 2.37831, 1, 0, 0.499788,-0.00180925)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435903,0.00436589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588927,0.0226353) , 
4, 0.710736, 1, 0, 0.491469,0.036804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732023,0.0120059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535081,-0.0268656) , 
3, 0.122181, 1, 0, 0.619605,-0.034817) , 
1, 5.00429, 1, 0, 0.529215,0.0157059)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482452,-0.0079837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394366,0.00743346) , 
3, 0.178995, 1, 0, 0.439488,-0.00190589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765531,0.0114865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538628,0.0663727) , 
5, 14.6511, 1, 0, 0.733471,0.0606349) , 
0, 1574.58, 1, 0, 0.525918,0.0164808)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516872,0.00687747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441757,-0.00771439) , 
4, 0.909981, 1, 0, 0.499195,0.010891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618031,-0.0268679) , 
1, 6.49071, 1, 0, 0.504883,0.0065543)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182807,-0.0361751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529283,-0.001856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253646,-0.017438) , 
3, 0.37653, 1, 0, 0.499112,-0.0117404) , 
1, 2.47322, 1, 0, 0.487297,-0.0157823)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58696,0.00281654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0586894,-0.0384378) , 
5, 28.4294, 1, 0, 0.553456,0.00322065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327844,-0.00436609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325033,-0.0323535) , 
4, 0.683211, 1, 0, 0.326669,-0.0526025) , 
3, 0.259255, 1, 0, 0.486547,-0.0132489)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658981,0.00841898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370061,-0.00396698) , 
5, 5.94446, 1, 0, 0.489525,0.0046569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519827,-0.0549349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8355,0.0304771) , 
0, 2902.45, 1, 0, 0.636655,-0.0816429) , 
1, 5.97857, 1, 0, 0.503614,-0.0036066)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341337,-0.0075642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535822,0.0125546) , 
1, 3.87746, 1, 0, 0.450841,0.0116683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441841,-0.0405192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643644,-0.00437211) , 
0, 1796.16, 1, 0, 0.604286,-0.0380768) , 
0, 1653.99, 1, 0, 0.494165,-0.00237683)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563071,-0.00140054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445684,-0.0421851) , 
3, 0.0777411, 1, 0, 0.541665,-0.0293209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464187,0.00222309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.835825,0.040137) , 
0, 2540.39, 1, 0, 0.49018,0.0138198) , 
3, 0.0925972, 1, 0, 0.505825,0.000709819)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282832,-0.0279498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501419,0.00462158) , 
0, 788.693, 1, 0, 0.485711,0.00690175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81243,-0.01453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722978,0.0349768) , 
5, 4.0115, 1, 0, 0.756565,0.054673) , 
0, 2316.66, 1, 0, 0.516947,0.012411)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569339,-0.000161061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128682,-0.0276398) , 
2, 0.118418, 1, 0, 0.531233,-0.00722154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329766,0.00863241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683665,0.0401185) , 
0, 1564.11, 1, 0, 0.384343,0.0466456) , 
3, 0.302408, 1, 0, 0.501332,0.0037439)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460809,0.0021453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612948,-0.0155826) , 
4, 0.737063, 1, 0, 0.508576,-0.0116369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637847,0.0430188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165927,0.00565545) , 
5, 4.41473, 1, 0, 0.38003,0.0837239) , 
4, 1.10852, 1, 0, 0.499425,-0.00484879)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
