// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold4
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:09 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 40690
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold4Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold4Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold4Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold4Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold4Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold4Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold4Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold4Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold4Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797026,0.0594051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422447,-0.0155107) , 
5, 13.6522, 1, 0, 0.720878,0.220878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397547,-0.0204906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0817218,-0.0836556) , 
5, 14.7691, 1, 0, 0.302591,-0.197409) , 
2, 0.0314797, 1, 0, 0.492367,-0.0076331)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766995,0.0482643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374225,-0.0230341) , 
5, 13.6627, 1, 0, 0.702332,0.181987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430654,-0.0118254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129017,-0.0674469) , 
5, 11.9998, 1, 0, 0.306227,-0.173039) , 
2, 0.0370163, 1, 0, 0.505698,0.00574512)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73319,0.0397948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281895,-0.0369327) , 
5, 17.0214, 1, 0, 0.665828,0.140394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365602,-0.0236738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0956795,-0.0692299) , 
5, 11.2942, 1, 0, 0.247059,-0.215613) , 
2, 0.0481454, 1, 0, 0.489506,-0.00950246)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676427,0.0278371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240951,-0.0448303) , 
2, 0.090721, 1, 0, 0.600152,0.0741457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118936,-0.0615586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344244,-0.0179786) , 
0, 1823.11, 1, 0, 0.164896,-0.254808) , 
5, 14.7991, 1, 0, 0.493924,-0.00613787)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774915,0.0400839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252454,-0.0377313) , 
5, 17.0626, 1, 0, 0.705257,0.144042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429852,-0.0116767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0910414,-0.0606227) , 
5, 15.2658, 1, 0, 0.332822,-0.122506) , 
2, 0.0277717, 1, 0, 0.492156,-0.00847192)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769847,0.0360511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282981,-0.0277309) , 
5, 17.058, 1, 0, 0.704126,0.131396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480197,-3.49296e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195594,-0.0424689) , 
5, 8.29726, 1, 0, 0.330498,-0.104847) , 
2, 0.0314746, 1, 0, 0.508261,0.0075514)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431825,-0.0196571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693864,0.0298313) , 
1, 3.89927, 1, 0, 0.608483,0.0654005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158635,-0.0516232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307658,-0.0218411) , 
1, 4.46521, 1, 0, 0.219188,-0.187534) , 
2, 0.0666104, 1, 0, 0.492098,-0.0102174)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517972,-0.00757098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78728,0.0399775) , 
1, 3.86762, 1, 0, 0.701657,0.116999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447092,-0.00324518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128523,-0.0495133) , 
5, 8.94814, 1, 0, 0.281098,-0.123445) , 
2, 0.0407384, 1, 0, 0.50294,0.00338779)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769142,0.0335722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408349,-0.0402483) , 
3, 0.364133, 1, 0, 0.726629,0.114934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389843,-0.0118463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0467087,-0.0614144) , 
5, 20.132, 1, 0, 0.323082,-0.0960943) , 
2, 0.0277622, 1, 0, 0.491851,-0.00783923)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60712,0.00259263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863162,0.0483529) , 
1, 4.45315, 1, 0, 0.736426,0.115941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398821,-0.009757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167901,-0.0412525) , 
2, 0.097065, 1, 0, 0.329536,-0.0877161) , 
2, 0.0277425, 1, 0, 0.500396,-0.00219736)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445448,-0.021976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766323,0.0305798) , 
1, 3.38048, 1, 0, 0.711709,0.0968403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236419,-0.0305073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405105,0.00340783) , 
0, 1483.66, 1, 0, 0.281613,-0.0970665) , 
2, 0.0388804, 1, 0, 0.495615,-0.000584567)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420948,-0.0189804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676874,0.0242085) , 
0, 996.548, 1, 0, 0.593993,0.0461003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102697,-0.0490056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299848,-0.0197875) , 
0, 1693.11, 1, 0, 0.144679,-0.176227) , 
5, 16.6427, 1, 0, 0.498277,-0.00126147)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667553,0.0219886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220215,-0.0263209) , 
2, 0.0759215, 1, 0, 0.561771,0.0487938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41265,-0.0149022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279772,-0.0448898) , 
3, 0.375619, 1, 0, 0.347805,-0.134106) , 
3, 0.290116, 1, 0, 0.510693,0.00513217)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657027,0.0183338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330528,-0.0365743) , 
4, 1.04403, 1, 0, 0.60203,0.0405942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36317,-0.0164117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.092764,-0.0501648) , 
5, 22.3655, 1, 0, 0.266553,-0.116512) , 
5, 10.235, 1, 0, 0.479054,-0.0169962)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612345,6.98893e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841559,0.0400835) , 
0, 1079.83, 1, 0, 0.767293,0.114827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460765,-0.00167163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104757,-0.0408673) , 
5, 14.2475, 1, 0, 0.355662,-0.0502732) , 
2, 0.0240727, 1, 0, 0.511895,0.0123897)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469532,-0.00124515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328799,-0.0266021) , 
3, 0.154317, 1, 0, 0.386174,-0.0715536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703593,0.0251795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241644,-0.0205481) , 
2, 0.0869636, 1, 0, 0.61997,0.0730557) , 
1, 4.37416, 1, 0, 0.500968,-0.000550134)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662183,0.0156034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224962,-0.0243551) , 
2, 0.0648007, 1, 0, 0.526825,0.0152136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154313,-0.0571531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304819,-0.0389384) , 
0, 1008.06, 1, 0, 0.234461,-0.209409) , 
3, 0.370305, 1, 0, 0.488613,-0.0141446)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696203,0.0230502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302984,-0.0185882) , 
5, 10.2479, 1, 0, 0.555369,0.0379597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361531,-0.0150652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257812,-0.0506535) , 
4, 0.594987, 1, 0, 0.306259,-0.154548) , 
3, 0.308633, 1, 0, 0.502239,-0.00309797)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443658,-0.0178667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730904,0.0276194) , 
1, 3.70828, 1, 0, 0.662959,0.0706665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411287,-0.00765149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175392,-0.0559983) , 
4, 0.732644, 1, 0, 0.386627,-0.0539351) , 
5, 5.68641, 1, 0, 0.497461,-0.00395869)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853015,0.0393503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525063,-0.0138211) , 
3, 0.265362, 1, 0, 0.77152,0.103133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436113,-0.000930538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300681,-0.0252468) , 
3, 0.166643, 1, 0, 0.366101,-0.056567) , 
2, 0.0185145, 1, 0, 0.486632,-0.00908816)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562399,0.00271172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290783,-0.0253736) , 
5, 5.47875, 1, 0, 0.390687,-0.0606788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716525,0.0234904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202144,-0.0255543) , 
5, 16.2826, 1, 0, 0.623853,0.0630226) , 
0, 1244.74, 1, 0, 0.497968,-0.00376302)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549371,0.00611176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392517,-0.0168705) , 
3, 0.154303, 1, 0, 0.45986,-0.0294276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.947505,0.0554535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585373,0.0176692) , 
2, 0.0202151, 1, 0, 0.752719,0.134939) , 
0, 2316.65, 1, 0, 0.493536,-0.010527)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338623,-0.0318554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706702,0.0220262) , 
1, 3.10329, 1, 0, 0.658424,0.0609478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364769,-0.00500815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0849159,-0.0380565) , 
5, 10.2674, 1, 0, 0.230905,-0.0699157) , 
2, 0.0610649, 1, 0, 0.514093,0.0167682)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139148,-0.0412687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504641,9.02686e-05) , 
4, 0.0670631, 1, 0, 0.450786,-0.0208711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836012,0.0398234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45661,0.00339527) , 
5, 10.1814, 1, 0, 0.721112,0.112944) , 
1, 5.248, 1, 0, 0.504835,0.00588418)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643694,0.013793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163152,-0.0289381) , 
5, 16.6443, 1, 0, 0.554622,0.0278862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363675,-0.0143434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287032,-0.0401952) , 
4, 0.836964, 1, 0, 0.33724,-0.101099) , 
3, 0.296305, 1, 0, 0.508972,0.000799065)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699851,0.0187651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441122,-0.0210099) , 
4, 0.979554, 1, 0, 0.635818,0.0361386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280599,-0.020661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656008,0.033761) , 
0, 2537.2, 1, 0, 0.307009,-0.0636479) , 
5, 8.57188, 1, 0, 0.492712,-0.00729117)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43982,-0.00872294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0577071,-0.0466437) , 
5, 19.0246, 1, 0, 0.35821,-0.0598752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638827,0.0165585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345762,-0.0324249) , 
4, 1.10459, 1, 0, 0.612398,0.0456946) , 
1, 4.17411, 1, 0, 0.49521,-0.00297616)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454707,-0.0163171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82632,0.0304978) , 
1, 3.29962, 1, 0, 0.769331,0.0843779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453,-0.000677337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166437,-0.0266178) , 
2, 0.0971823, 1, 0, 0.38245,-0.0259067) , 
2, 0.0203692, 1, 0, 0.510476,0.0105884)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588719,0.00766944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0849225,-0.040641) , 
5, 21.6292, 1, 0, 0.506295,0.00609624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449903,-0.0169359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10935,-0.057449) , 
5, 4.60727, 1, 0, 0.322037,-0.136588) , 
4, 1.0212, 1, 0, 0.481294,-0.0132636)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201593,-0.0266886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614635,0.00573602) , 
4, 0.0666776, 1, 0, 0.564211,0.00912667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146443,-0.0186378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171446,-0.0337405) , 
4, 0.64515, 1, 0, 0.15741,-0.0929291) , 
2, 0.0962907, 1, 0, 0.497261,-0.00766929)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369321,-0.00679739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359457,-0.027315) , 
4, 0.799319, 1, 0, 0.366241,-0.0548206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739278,0.0169717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303404,-0.0086764) , 
2, 0.049972, 1, 0, 0.582424,0.0284461) , 
0, 1107.45, 1, 0, 0.491481,-0.00658224)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657706,0.0123171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350023,-0.0245458) , 
4, 1.02009, 1, 0, 0.606592,0.0249037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184142,-0.0187136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11453,-0.0460248) , 
4, 0.266758, 1, 0, 0.170796,-0.0785824) , 
5, 14.2653, 1, 0, 0.49645,-0.00125105)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505467,-0.00553812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.773838,0.0275634) , 
1, 4.13675, 1, 0, 0.668836,0.0542602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408018,-0.00594064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188125,-0.0511793) , 
4, 0.732773, 1, 0, 0.385547,-0.0400091) , 
5, 5.59271, 1, 0, 0.497855,-0.00263673)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628578,0.00898362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139231,-0.0231982) , 
5, 18.2157, 1, 0, 0.543387,0.0172464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265575,-0.00314902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353895,-0.0262703) , 
4, 0.376652, 1, 0, 0.324333,-0.0789656) , 
3, 0.290089, 1, 0, 0.492684,-0.00502327)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329533,-0.0306353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0961356,-0.025996) , 
2, 0.0298909, 1, 0, 0.162765,-0.0848292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599641,0.00863248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307737,-0.0172451) , 
4, 1.07508, 1, 0, 0.562018,0.020728) , 
4, 0.0887332, 1, 0, 0.494267,0.00281539)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531775,0.00250368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831909,0.0423243) , 
0, 2537.2, 1, 0, 0.563731,0.0236142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374322,-0.00749704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369472,-0.0245567) , 
4, 0.774028, 1, 0, 0.372649,-0.054606) , 
3, 0.246891, 1, 0, 0.50565,-0.000161258)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616686,0.0125714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0718108,-0.0369227) , 
5, 23.8808, 1, 0, 0.551108,0.0316031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48061,-0.0091688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14176,-0.0436492) , 
5, 3.50337, 1, 0, 0.310308,-0.100346) , 
4, 1.02055, 1, 0, 0.516664,0.012729)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827565,0.0260121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506005,-0.00986946) , 
3, 0.314766, 1, 0, 0.768006,0.063536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491892,0.00893488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368789,-0.00948145) , 
3, 0.074147, 1, 0, 0.398955,-0.018793) , 
2, 0.0166657, 1, 0, 0.49951,0.00363909)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762356,0.0230735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.928141,0.0471735) , 
4, 0.623779, 1, 0, 0.845327,0.119385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52341,0.00322287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281222,-0.0230468) , 
3, 0.29007, 1, 0, 0.46334,-0.0128875) , 
2, 0.00740115, 1, 0, 0.506997,0.00222962)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640245,0.008785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257098,-0.020478) , 
2, 0.0166657, 1, 0, 0.357316,-0.0461495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67332,0.0104459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184815,-0.0198154) , 
2, 0.0943647, 1, 0, 0.589128,0.0198989) , 
1, 4.06775, 1, 0, 0.494647,-0.00702086)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27074,-0.037533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0864955,-0.0250916) , 
2, 0.0296027, 1, 0, 0.133785,-0.0828243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596949,0.00761674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338395,-0.0193866) , 
4, 1.00851, 1, 0, 0.55677,0.012747) , 
4, 0.0656563, 1, 0, 0.499005,-0.000304771)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187401,-0.0426155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545542,0.00530156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302985,-0.0169026) , 
3, 0.339495, 1, 0, 0.508102,0.006201) , 
1, 2.55732, 1, 0, 0.494601,-0.000834756)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370228,-0.0227498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721905,0.021955) , 
1, 3.21488, 1, 0, 0.679243,0.0613852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438596,0.00242713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288236,-0.0361742) , 
4, 0.732387, 1, 0, 0.417079,-0.0124587) , 
5, 4.47616, 1, 0, 0.502273,0.0115378)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0871946,-0.0410059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443392,-0.00727254) , 
4, 0.0660255, 1, 0, 0.384183,-0.0419849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70558,0.0155214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245081,-0.0121889) , 
2, 0.087032, 1, 0, 0.621625,0.0363786) , 
0, 1226.62, 1, 0, 0.498326,-0.00431389)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743288,0.0231074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573388,-0.0023187) , 
4, 0.780729, 1, 0, 0.645742,0.0323542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351819,-0.00709502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166728,-0.0540443) , 
4, 0.599624, 1, 0, 0.335063,-0.0393002) , 
5, 7.96905, 1, 0, 0.499812,-0.00130277)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701829,0.0152017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321416,-0.0248433) , 
3, 0.364084, 1, 0, 0.653899,0.0366629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339591,-0.0109571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711557,0.033408) , 
0, 2537.2, 1, 0, 0.369887,-0.0246742) , 
5, 6.83071, 1, 0, 0.500843,0.00360797)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511799,-0.000978038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78003,0.0313144) , 
1, 5.23043, 1, 0, 0.579472,0.0229371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680468,0.00448048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306132,-0.0180853) , 
2, 0.0166657, 1, 0, 0.39912,-0.0451983) , 
3, 0.160498, 1, 0, 0.485825,-0.0124418)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374347,-0.0192528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702791,0.0134727) , 
1, 3.10334, 1, 0, 0.665524,0.0345084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339023,-0.000995832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322231,-0.0312751) , 
4, 0.487955, 1, 0, 0.335948,-0.0230078) , 
5, 7.96076, 1, 0, 0.510544,0.00746206)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302413,-0.0246591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609676,0.00777547) , 
1, 3.1932, 1, 0, 0.570371,0.011189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369375,-0.00480914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424049,-0.0415809) , 
1, 5.40907, 1, 0, 0.376834,-0.0372476) , 
3, 0.22838, 1, 0, 0.499827,-0.00646613)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112032,-0.0420877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144339,-0.0136125) , 
3, 0.1975, 1, 0, 0.125678,-0.0812134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579152,0.00740928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51004,-0.00854571) , 
4, 0.869546, 1, 0, 0.559666,0.0108765) , 
4, 0.0448581, 1, 0, 0.503058,-0.00113546)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876951,0.0295393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609654,-0.00312708) , 
5, 6.8346, 1, 0, 0.751726,0.0408579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380373,-0.00269758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155409,-0.0353236) , 
3, 0.407336, 1, 0, 0.358782,-0.021063) , 
2, 0.0222209, 1, 0, 0.496922,0.000705304)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434843,0.0041671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531577,-0.00908178) , 
4, 0.687265, 1, 0, 0.47399,-0.00505162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828301,0.0113439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630683,0.0382954) , 
2, 0.0346455, 1, 0, 0.761291,0.0741583) , 
0, 2298.91, 1, 0, 0.510393,0.00498478)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57168,0.00575488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.869702,0.037426) , 
1, 4.33322, 1, 0, 0.725503,0.0737797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49535,0.00164403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272158,-0.028359) , 
4, 0.888056, 1, 0, 0.46912,-0.00678409) , 
5, 2.37809, 1, 0, 0.514028,0.00732762)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524983,-0.0132584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.800166,0.0184019) , 
0, 914.432, 1, 0, 0.744848,0.0357537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370798,-0.0169152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320305,8.36601e-06) , 
3, 0.191359, 1, 0, 0.348764,-0.0367341) , 
2, 0.0222209, 1, 0, 0.492345,-0.0104571)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713567,0.0131427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417608,-0.00357367) , 
5, 5.69241, 1, 0, 0.537442,0.01154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113337,-0.0312839) , 
2, 0.120344, 1, 0, 0.501235,0.00257203)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5873,0.00401215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.925996,0.0504879) , 
1, 6.03572, 1, 0, 0.614435,0.0247824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136426,-0.000835678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215212,-0.0206611) , 
4, 0.397213, 1, 0, 0.182744,-0.0461866) , 
2, 0.0814767, 1, 0, 0.514136,0.00829354)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259967,-0.0288193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62557,0.010873) , 
1, 3.00945, 1, 0, 0.594193,0.0235727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394977,-0.00419214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477081,-0.0176152) , 
4, 0.687988, 1, 0, 0.429453,-0.0352257) , 
3, 0.129645, 1, 0, 0.494308,-0.0120777)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2927,-0.0345293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118564,-0.0194894) , 
5, 16.1897, 1, 0, 0.159572,-0.0666898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393639,-0.00978218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62111,0.0111387) , 
0, 832.49, 1, 0, 0.591774,0.0297412) , 
4, 0.110807, 1, 0, 0.513595,0.0122982)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46496,-0.0240409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226035,-0.00477464) , 
2, 0.0371065, 1, 0, 0.331978,-0.0512198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817364,0.0283008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515229,-0.0013331) , 
5, 2.0485, 1, 0, 0.560786,0.00998849) , 
0, 988.301, 1, 0, 0.488041,-0.00947141)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671009,0.00450236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802817,0.0520367) , 
5, 1.74331, 1, 0, 0.70017,0.0538614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473163,-0.00164575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231852,-0.0276585) , 
4, 0.909958, 1, 0, 0.446734,-0.015541) , 
5, 2.27755, 1, 0, 0.490844,-0.00346158)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567413,0.00982642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550055,-0.00906881) , 
4, 0.710559, 1, 0, 0.559378,0.00421503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202007,-0.0266088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0497668,-0.0303285) , 
2, 0.0246927, 1, 0, 0.0868737,-0.0656175) , 
5, 22.5875, 1, 0, 0.496449,-0.00508545)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828392,0.0275874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447395,-0.00352652) , 
2, 0.00555135, 1, 0, 0.477006,-0.004369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813685,0.0365156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747868,0.0100434) , 
0, 2817.04, 1, 0, 0.783944,0.0774041) , 
1, 5.81619, 1, 0, 0.505486,0.00321858)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549859,0.00127743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.990855,0.0675219) , 
1, 4.41304, 1, 0, 0.742044,0.0825101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497316,0.000198937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231195,-0.0268532) , 
4, 0.910269, 1, 0, 0.469148,-0.00911242) , 
5, 2.37831, 1, 0, 0.51345,0.00576181)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294321,-0.0274708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366744,-0.00398184) , 
0, 802.946, 1, 0, 0.331852,-0.0576387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543218,0.00646012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533361,-0.0100496) , 
4, 0.888668, 1, 0, 0.540942,0.00891741) , 
0, 869.155, 1, 0, 0.504107,-0.00280752)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211577,-0.0218572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663942,0.0087353) , 
4, 0.111336, 1, 0, 0.577875,0.0119167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380998,0.0047405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476423,-0.0221302) , 
1, 4.23133, 1, 0, 0.430668,-0.0306115) , 
3, 0.135792, 1, 0, 0.494785,-0.0120879)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787271,0.0222838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56976,1.40104e-05) , 
4, 0.916058, 1, 0, 0.694689,0.0425892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404779,-0.001441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332005,-0.0241499) , 
4, 0.621663, 1, 0, 0.392335,-0.0180099) , 
5, 5.69241, 1, 0, 0.516075,0.00679066)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322484,-0.0304702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352233,-0.00712505) , 
3, 0.0555813, 1, 0, 0.347896,-0.0383637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777175,0.0189258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458996,-0.00419315) , 
5, 5.55065, 1, 0, 0.589452,0.0161989) , 
1, 4.02093, 1, 0, 0.498701,-0.00429978)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679241,0.00120842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761846,0.0406987) , 
5, 0.511406, 1, 0, 0.718743,0.0716298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417573,-0.0085336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656604,0.00820771) , 
1, 5.15145, 1, 0, 0.473017,-0.0168674) , 
5, 1.11911, 1, 0, 0.49141,-0.0102432)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749999,0.0218042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257109,-0.00813031) , 
5, 13.0783, 1, 0, 0.61474,0.0462593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714881,0.0195049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428764,-0.00456096) , 
5, 2.03913, 1, 0, 0.471516,-0.00319701) , 
3, 0.0926026, 1, 0, 0.51152,0.0106166)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50536,0.0053767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.079397,-0.0206763) , 
5, 20.2091, 1, 0, 0.429701,0.00985751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424315,0.0109276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645039,-0.013769) , 
4, 0.200607, 1, 0, 0.60262,-0.0280958) , 
1, 4.62412, 1, 0, 0.500003,-0.00557293)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371217,-0.00603883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586343,0.00622014) , 
1, 4.05872, 1, 0, 0.495551,0.00269623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650408,-0.0327791) , 
1, 6.5077, 1, 0, 0.502185,-0.00144301)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208945,-0.0325675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502812,0.000761182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613386,-0.0281299) , 
1, 6.50576, 1, 0, 0.507967,-0.00160926) , 
1, 2.63632, 1, 0, 0.492155,-0.0076724)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303386,-0.0405228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263208,0.003041) , 
5, 5.36274, 1, 0, 0.280378,-0.0670771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739048,0.0168988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427419,-0.00280368) , 
5, 4.55407, 1, 0, 0.530686,0.0123099) , 
0, 832.189, 1, 0, 0.49882,0.00220347)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659069,0.000889349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66536,0.0280474) , 
5, 6.16439, 1, 0, 0.660228,0.0217156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286817,-0.00240525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366176,-0.0231584) , 
4, 0.354897, 1, 0, 0.314209,-0.033957) , 
5, 8.32169, 1, 0, 0.500872,-0.00392385)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614209,0.00534289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163531,-0.0241431) , 
2, 0.112956, 1, 0, 0.568392,0.00897054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108405,-0.0026295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101345,-0.032741) , 
1, 3.75227, 1, 0, 0.103463,-0.0606587) , 
5, 21.3976, 1, 0, 0.501457,-0.00105381)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790827,0.022494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383676,0.000630489) , 
5, 6.82546, 1, 0, 0.490084,0.0211334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.860083,0.0191886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459129,-0.0125935) , 
2, 0.0147662, 1, 0, 0.549165,-0.0237032) , 
4, 0.777272, 1, 0, 0.510075,0.00596254)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28052,-0.0186151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428783,0.00325204) , 
0, 1069.11, 1, 0, 0.329085,-0.0404269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719485,0.0106493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325002,-0.00712775) , 
5, 10.0156, 1, 0, 0.570063,0.0132455) , 
1, 3.74955, 1, 0, 0.495258,-0.00341559)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486009,-0.00252476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821094,0.0246205) , 
0, 2316.66, 1, 0, 0.521376,-0.000819126) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531162,-0.035684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321274,-0.00653429) , 
4, 1.05284, 1, 0, 0.38568,-0.0537717) , 
4, 0.976112, 1, 0, 0.499388,-0.00939955)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454406,0.00527365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425165,0.059694) , 
3, 0.438206, 1, 0, 0.452691,0.027369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626548,-0.00083268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296184,-0.0396771) , 
3, 0.388821, 1, 0, 0.603229,-0.0131456) , 
0, 1325.27, 1, 0, 0.5198,0.00930784)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57236,0.00164958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522379,-0.0118237) , 
3, 0.057847, 1, 0, 0.536911,-0.0259671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534977,0.00724629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162841,-0.0168852) , 
2, 0.0684588, 1, 0, 0.422987,0.00412455) , 
3, 0.203681, 1, 0, 0.491021,-0.0138458)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150407,-0.0371559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506536,0.00207425) , 
1, 2.4341, 1, 0, 0.493063,0.001986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974925,0.0581206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686147,0.0145597) , 
5, 7.16658, 1, 0, 0.835893,0.0880378) , 
0, 2537.19, 1, 0, 0.521883,0.00921983)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484695,0.00475102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560175,-0.00860417) , 
4, 0.732063, 1, 0, 0.513574,-0.00162724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177333,-0.0496922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227791,-0.013772) , 
5, 7.24597, 1, 0, 0.202907,-0.119757) , 
3, 0.432022, 1, 0, 0.493745,-0.00916705)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438132,0.0101587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574219,-0.00470017) , 
4, 0.289479, 1, 0, 0.547451,-0.00609005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0585336,-0.0227693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102578,-0.031965) , 
0, 1346.96, 1, 0, 0.0752081,-0.0548736) , 
5, 22.5879, 1, 0, 0.487361,-0.0122974)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570445,0.00859311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0953868,-0.0192512) , 
5, 22.5946, 1, 0, 0.476095,0.0168872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525955,-0.0119888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.833169,0.0283991) , 
1, 5.8606, 1, 0, 0.558199,-0.029372) , 
4, 0.732758, 1, 0, 0.507368,-0.000732317)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560109,-0.000877932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445583,0.0117347) , 
3, 0.250137, 1, 0, 0.533338,0.00708983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267983,-0.00355835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260982,-0.0370201) , 
1, 4.03333, 1, 0, 0.264803,-0.0729405) , 
3, 0.413566, 1, 0, 0.512299,0.000819436)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639184,0.00588357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545728,-0.0138216) , 
4, 0.995651, 1, 0, 0.628618,0.0116964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202592,-0.00530236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25578,-0.0308552) , 
0, 1782.72, 1, 0, 0.212675,-0.034997) , 
2, 0.0666522, 1, 0, 0.497275,-0.0030481)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39302,0.015427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533873,-0.000589502) , 
1, 3.18227, 1, 0, 0.515628,0.00538887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211096,-0.0246181) , 
3, 0.444375, 1, 0, 0.501117,0.00113374)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454725,0.00230458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498928,-0.00871161) , 
4, 0.77669, 1, 0, 0.470121,-0.00564771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794044,0.0563902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760678,0.00819061) , 
1, 6.07127, 1, 0, 0.771777,0.0675045) , 
1, 5.73732, 1, 0, 0.505919,0.00303357)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701514,-0.0142595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888581,0.0780103) , 
3, 0.154423, 1, 0, 0.795276,0.111731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499172,-0.00215002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279574,-0.0199909) , 
3, 0.364185, 1, 0, 0.471651,-0.0147922) , 
5, 1.18959, 1, 0, 0.495551,-0.00544842)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0573208,-0.0461274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531784,0.00358153) , 
4, -0.0811619, 1, 0, 0.496919,0.00479075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605097,-0.023501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370217,0.00380346) , 
4, 1.0278, 1, 0, 0.494303,-0.0355621) , 
4, 0.865137, 1, 0, 0.496235,-0.00575828)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190869,-0.0318366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116872,-0.0246143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561737,0.00194618) , 
4, 0.000379536, 1, 0, 0.519114,0.000905066) , 
1, 2.475, 1, 0, 0.50821,-0.00257857)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734408,0.0140565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24435,-0.0106352) , 
2, 0.0925725, 1, 0, 0.655301,0.0333025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283837,0.000714667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32517,-0.0205897) , 
4, 0.376371, 1, 0, 0.293444,-0.0145587) , 
5, 9.51215, 1, 0, 0.510632,0.0141678)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796364,0.00784779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408038,-0.00541504) , 
2, 0.0203588, 1, 0, 0.543631,-0.00471246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491034,0.0214272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10275,-0.0168335) , 
2, 0.0869611, 1, 0, 0.398751,0.0493995) , 
3, 0.302426, 1, 0, 0.513812,0.00642483)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482645,-0.00840438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.826346,0.0173072) , 
4, 0.219419, 1, 0, 0.760227,0.0341215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316307,0.00556902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404837,-0.010343) , 
4, 0.688259, 1, 0, 0.351118,-0.00484071) , 
2, 0.0277619, 1, 0, 0.526138,0.0118277)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498743,-0.00389082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267752,-0.0210221) , 
3, 0.358013, 1, 0, 0.467632,-0.020484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9013,0.0564198) , 
1, 6.45273, 1, 0, 0.484704,-0.0138432)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505402,0.00197795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203654,-0.0279613) , 
3, 0.444367, 1, 0, 0.486312,0.000148264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511222,-0.0542213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78851,0.00784148) , 
4, 0.703147, 1, 0, 0.627397,-0.090328) , 
1, 6.03306, 1, 0, 0.499543,-0.00833685)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477023,0.00101897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926875,0.0642494) , 
1, 5.70871, 1, 0, 0.494699,0.0102576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624402,-0.0317174) , 
1, 6.05976, 1, 0, 0.505344,0.00198888)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45758,-0.0258734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747043,-0.0013251) , 
0, 988.31, 1, 0, 0.666685,-0.0310923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316871,0.0188741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344547,-0.010278) , 
4, 0.665443, 1, 0, 0.329074,0.0142533) , 
2, 0.0351651, 1, 0, 0.498664,-0.00852486)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575827,0.0300703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668629,0.00177925) , 
1, 4.70354, 1, 0, 0.616944,0.06066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441161,-0.00238962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635227,-0.0208987) , 
0, 1923.84, 1, 0, 0.479871,-0.0185051) , 
3, 0.0493901, 1, 0, 0.500622,-0.00652088)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522464,-0.000437409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479645,0.0370232) , 
3, 0.317074, 1, 0, 0.520242,0.00483188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263592,0.0147664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291446,-0.0307608) , 
4, 0.355554, 1, 0, 0.282528,-0.0677686) , 
3, 0.35182, 1, 0, 0.487969,-0.0050245)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711785,0.00998981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253483,-0.00637158) , 
2, 0.0592558, 1, 0, 0.550515,0.0133214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316929,0.00346853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351384,-0.0378222) , 
1, 4.57385, 1, 0, 0.32852,-0.0386434) , 
3, 0.302461, 1, 0, 0.505287,0.00273434)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833634,0.00229547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.799685,0.0395855) , 
3, 0.185401, 1, 0, 0.82047,0.0560957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553784,0.00483106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403074,-0.00744415) , 
3, 0.148153, 1, 0, 0.471801,-0.00628974) , 
2, 0.00555523, 1, 0, 0.499127,-0.00140033)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737939,0.0150028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326005,-0.0218642) , 
3, 0.345632, 1, 0, 0.681487,0.0300364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429109,-0.000621699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457295,-0.0187837) , 
4, 0.643856, 1, 0, 0.437923,-0.0201787) , 
5, 3.00408, 1, 0, 0.490623,-0.00931362)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368065,-0.00086874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345313,-0.0191171) , 
1, 3.42406, 1, 0, 0.357671,-0.032262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794868,0.0242915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501901,0.00461116) , 
5, 4.55507, 1, 0, 0.601871,0.0344164) , 
1, 3.89097, 1, 0, 0.520539,0.0122089)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454674,0.0118655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606229,-0.00688199) , 
0, 1358.56, 1, 0, 0.518387,0.0140061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482733,-0.0142308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300385,0.0295157) , 
4, 1.26693, 1, 0, 0.451427,-0.0272303) , 
4, 0.910245, 1, 0, 0.503331,0.00473373)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738549,-0.00176681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757769,0.0153683) , 
2, 0.0124722, 1, 0, 0.746846,0.0179445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481243,-0.0174965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283728,-0.000854814) , 
2, 0.0427091, 1, 0, 0.341469,-0.0211229) , 
2, 0.0240606, 1, 0, 0.495703,-0.00625897)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753254,0.00273487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.948677,0.0552647) , 
4, 0.814727, 1, 0, 0.801545,0.0398655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664193,-0.0132808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354555,0.000427438) , 
2, 0.0249001, 1, 0, 0.44929,-0.0117453) , 
2, 0.00925226, 1, 0, 0.498932,-0.00447197)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297263,-0.00712289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483854,0.00919772) , 
1, 3.35633, 1, 0, 0.429914,0.014145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597298,0.00591171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598242,-0.0254809) , 
4, 0.729718, 1, 0, 0.597699,-0.021246) , 
1, 4.67965, 1, 0, 0.493653,0.000700581)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47688,-0.0153724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653903,0.00280221) , 
4, 0.7546, 1, 0, 0.538594,-0.0284486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79406,0.0375096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392125,0.00249582) , 
2, 0.00554922, 1, 0, 0.421216,0.0174694) , 
3, 0.19751, 1, 0, 0.490108,-0.0094811)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705635,0.0129955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350298,-0.0112932) , 
2, 0.00752402, 1, 0, 0.381705,-0.0303034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632424,0.0435578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612741,0.00228665) , 
0, 1319.19, 1, 0, 0.614416,0.0186268) , 
0, 1243.1, 1, 0, 0.490647,-0.00739709)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619356,0.00505397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162467,-0.0131714) , 
5, 15.4542, 1, 0, 0.515755,0.00569774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289928,-0.0277603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232613,0.00923812) , 
5, 7.75826, 1, 0, 0.265047,-0.0511499) , 
3, 0.401196, 1, 0, 0.494541,0.000887355)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602205,0.00364956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70842,-0.0141095) , 
4, 0.641196, 1, 0, 0.65508,-0.0144456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552785,0.0328433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286078,0.00410684) , 
2, 0.0492225, 1, 0, 0.310198,0.0232011) , 
2, 0.0425901, 1, 0, 0.504635,0.0019767)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563103,-0.000552415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508405,-0.0298921) , 
3, 0.165737, 1, 0, 0.559695,-0.00803771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411246,0.00596237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725648,0.0329067) , 
0, 1816.33, 1, 0, 0.469782,0.035321) , 
3, 0.179005, 1, 0, 0.519655,0.0112708)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511845,0.00273708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684505,-0.0129086) , 
1, 5.65381, 1, 0, 0.53751,0.00254657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123799,-0.023896) , 
2, 0.120303, 1, 0, 0.499138,-0.00363422)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617082,-0.00225034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52233,-0.0225437) , 
4, 0.975992, 1, 0, 0.604907,-0.0167832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453119,0.0239219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185249,-0.00135999) , 
5, 5.01267, 1, 0, 0.255444,0.0219184) , 
2, 0.0629593, 1, 0, 0.496421,-0.00476881)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704559,-0.0199383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576252,0.00355767) , 
2, 0.00525487, 1, 0, 0.588042,0.00579056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166022,0.0130959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17593,-0.0166061) , 
1, 3.5782, 1, 0, 0.173599,-0.0308933) , 
2, 0.0851667, 1, 0, 0.498719,-0.00211574)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386747,-0.0260152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691084,-0.00344219) , 
0, 832.191, 1, 0, 0.65171,-0.0228263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5874,0.0394507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272555,0.00341177) , 
2, 0.0505617, 1, 0, 0.30606,0.0250196) , 
2, 0.0425901, 1, 0, 0.503007,-0.00224231)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612635,0.00265095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263213,-0.0104498) , 
5, 9.10759, 1, 0, 0.464428,-0.00766827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.800612,0.0322365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764491,0.00536128) , 
1, 6.29425, 1, 0, 0.786853,0.0627025) , 
0, 2283.73, 1, 0, 0.501747,0.000476817)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469201,0.00376203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.811066,0.0337135) , 
4, 0.707704, 1, 0, 0.490048,0.0179814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.882576,0.0261574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44797,-0.0118564) , 
2, 0.014801, 1, 0, 0.547266,-0.0173709) , 
4, 0.754837, 1, 0, 0.510608,0.00527802)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668794,0.0151861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164963,-0.00613237) , 
5, 15.5728, 1, 0, 0.467147,0.0262658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666593,0.00130666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387157,-0.0152116) , 
3, 0.253012, 1, 0, 0.582207,-0.0131563) , 
4, 0.643296, 1, 0, 0.521094,0.00778256)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836709,0.0129899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633271,-0.0126262) , 
5, 2.00764, 1, 0, 0.668321,-0.0275462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680157,0.0490505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307511,0.00153855) , 
2, 0.0391104, 1, 0, 0.333016,0.017172) , 
2, 0.0333314, 1, 0, 0.496526,-0.00463469)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558663,0.011458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716913,-0.0035629) , 
0, 1156.93, 1, 0, 0.648118,0.013009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,0.000219647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369635,-0.0260547) , 
4, 0.421891, 1, 0, 0.340558,-0.0264584) , 
5, 7.13297, 1, 0, 0.491101,-0.00714007)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616918,0.0172844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258404,0.00605585) , 
2, 0.0296279, 1, 0, 0.406943,0.0388352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596058,-0.00645026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47962,0.0138668) , 
3, 0.246876, 1, 0, 0.566626,-0.00253046) , 
1, 3.86773, 1, 0, 0.516217,0.0105278)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79597,0.0118242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347704,-0.00422406) , 
2, 0.0388667, 1, 0, 0.595141,0.0114336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325736,0.00218453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43488,-0.0164422) , 
1, 3.65478, 1, 0, 0.402953,-0.0354252) , 
3, 0.148144, 1, 0, 0.491556,-0.0138224)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37893,-0.0197651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350992,-0.00457085) , 
3, 0.0679719, 1, 0, 0.356633,-0.0257537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568123,0.0248651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588447,-0.0021237) , 
1, 4.4421, 1, 0, 0.584436,0.0104055) , 
1, 4.1113, 1, 0, 0.486918,-0.0050735)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
