// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold2
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:07 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 40834
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold2Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold2Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold2Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold2Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold2Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold2Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold2Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold2Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790678,0.0581356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414246,-0.0171509) , 
5, 13.0766, 1, 0, 0.71006,0.210061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419789,-0.0160422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116519,-0.0766962) , 
5, 11.1864, 1, 0, 0.298016,-0.201984) , 
2, 0.0314746, 1, 0, 0.479703,-0.0202973)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77546,0.0497569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356499,-0.0269933) , 
5, 14.786, 1, 0, 0.710712,0.188801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411804,-0.0151489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0946054,-0.073857) , 
5, 13.8452, 1, 0, 0.314899,-0.164704) , 
2, 0.0314797, 1, 0, 0.502141,0.00252424)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733532,0.0388486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218736,-0.0511004) , 
5, 21.6066, 1, 0, 0.688065,0.152868) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436413,-0.0096086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136725,-0.0609763) , 
5, 10.0665, 1, 0, 0.303245,-0.159748) , 
2, 0.0351545, 1, 0, 0.491566,-0.00676184)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477977,-0.0108309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759586,0.044483) , 
1, 3.78663, 1, 0, 0.675455,0.13731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404173,-0.0151127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122564,-0.0588488) , 
5, 10.0663, 1, 0, 0.276669,-0.169616) , 
2, 0.0444348, 1, 0, 0.495111,-0.00149143)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664512,0.0244162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29821,-0.0315685) , 
2, 0.0740698, 1, 0, 0.581216,0.0567884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403386,-0.0170958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103707,-0.0618587) , 
2, 0.0133205, 1, 0, 0.149521,-0.261381) , 
5, 15.4542, 1, 0, 0.485941,-0.0134321)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752476,0.0341497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191063,-0.0510029) , 
5, 22.5864, 1, 0, 0.707693,0.131484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453477,-0.00656623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167447,-0.0462998) , 
5, 9.23023, 1, 0, 0.319447,-0.118491) , 
2, 0.0277717, 1, 0, 0.485176,-0.0117856)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679551,0.0271413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386296,-0.0313392) , 
3, 0.320941, 1, 0, 0.629118,0.0819912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176474,-0.0478745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368515,-0.00805995) , 
0, 1483.73, 1, 0, 0.224054,-0.179707) , 
2, 0.0592558, 1, 0, 0.494021,-0.00529023)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662229,0.0247356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415144,-0.0205622) , 
3, 0.296193, 1, 0, 0.606794,0.0695908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256146,-0.0282063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0597706,-0.0631831) , 
5, 23.7165, 1, 0, 0.167658,-0.196923) , 
5, 14.9989, 1, 0, 0.500343,0.00498489)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5574,-0.00455627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.83953,0.0475484) , 
1, 4.01882, 1, 0, 0.741805,0.137014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276157,-0.0288941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506087,0.0142839) , 
1, 5.13929, 1, 0, 0.320206,-0.0958089) , 
2, 0.0277543, 1, 0, 0.494339,0.000354025)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552666,-0.00535894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849824,0.0464458) , 
1, 4.06048, 1, 0, 0.737475,0.121353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42547,-0.00780714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.073203,-0.0543461) , 
5, 17.3076, 1, 0, 0.34656,-0.0794881) , 
2, 0.0240522, 1, 0, 0.494697,-0.00337937)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688,0.0227511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256215,-0.0265992) , 
5, 13.6623, 1, 0, 0.589919,0.0553907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11496,-0.0517677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260169,-0.0234087) , 
1, 4.66268, 1, 0, 0.158551,-0.190563) , 
2, 0.087032, 1, 0, 0.500118,0.00418874)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635957,0.0182397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336754,-0.0320117) , 
4, 1.04298, 1, 0, 0.596028,0.0529862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246872,-0.0183008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121894,-0.0460412) , 
3, 0.0988231, 1, 0, 0.159622,-0.155029) , 
5, 17.0579, 1, 0, 0.513608,0.0137002)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663298,0.0218634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357827,-0.0302937) , 
3, 0.314754, 1, 0, 0.603172,0.0516393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391771,-0.00518475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133805,-0.0432595) , 
5, 5.06997, 1, 0, 0.200635,-0.14009) , 
2, 0.0758827, 1, 0, 0.502352,0.00361851)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753605,0.0267997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368871,-0.0118848) , 
2, 0.0592076, 1, 0, 0.638504,0.0675485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257864,-0.031882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494521,0.00594703) , 
0, 1572.25, 1, 0, 0.320845,-0.0916259) , 
5, 8.07653, 1, 0, 0.491261,-0.00623266)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551042,-0.00325337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781552,0.0344674) , 
1, 4.59857, 1, 0, 0.652232,0.0576227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452587,0.00277384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182586,-0.0320347) , 
5, 5.13583, 1, 0, 0.265935,-0.0871246) , 
2, 0.0518081, 1, 0, 0.506051,0.00284791)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644818,0.0140366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332561,-0.0314887) , 
4, 1.04104, 1, 0, 0.601119,0.0337156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446637,-0.0044924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114611,-0.0399959) , 
2, 0.0188892, 1, 0, 0.184018,-0.121216) , 
5, 14.2653, 1, 0, 0.501849,-0.0031583)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324274,-0.0417773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728258,0.0212745) , 
1, 2.96924, 1, 0, 0.68646,0.0627957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186449,-0.0335175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334099,-0.0092111) , 
1, 3.98835, 1, 0, 0.272094,-0.0806622) , 
2, 0.0407319, 1, 0, 0.49334,-0.00406459)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502649,-0.00780463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747006,0.028154) , 
1, 4.1802, 1, 0, 0.643762,0.0551346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311604,-0.0178955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156249,-0.0603945) , 
4, 0.598913, 1, 0, 0.296083,-0.0909578) , 
5, 8.07658, 1, 0, 0.484255,-0.011889)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718705,0.0236496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336962,-0.0112919) , 
5, 10.6991, 1, 0, 0.591361,0.0542155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238959,-0.0165118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0998262,-0.0486276) , 
3, 0.197634, 1, 0, 0.169582,-0.1291) , 
2, 0.0980739, 1, 0, 0.518433,0.0225191)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502866,-0.0159491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73391,0.0244745) , 
0, 996.557, 1, 0, 0.668078,0.0534038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297789,-0.0112347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133216,-0.0385203) , 
2, 0.112432, 1, 0, 0.24781,-0.0778173) , 
2, 0.0518406, 1, 0, 0.504619,0.00236676)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444768,-0.0254327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802159,0.0263956) , 
1, 3.38064, 1, 0, 0.742814,0.0685088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303801,-0.0199683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594406,0.0225752) , 
1, 5.87805, 1, 0, 0.327098,-0.0687421) , 
2, 0.0240606, 1, 0, 0.482458,-0.0174492)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686603,0.0265615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160176,-0.0284773) , 
5, 19.3526, 1, 0, 0.607447,0.0794566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386191,-0.0161523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753858,0.0395396) , 
0, 2466.99, 1, 0, 0.413972,-0.0491197) , 
3, 0.154302, 1, 0, 0.502505,0.00971635)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178819,-0.0319464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0852621,-0.0513255) , 
3, 0.222178, 1, 0, 0.145644,-0.134173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444375,-0.00722912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667737,0.0175358) , 
1, 4.34167, 1, 0, 0.555813,0.020266) , 
4, 0.0668578, 1, 0, 0.498289,-0.00139325)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679654,0.0139996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197186,-0.0241136) , 
5, 16.6428, 1, 0, 0.593919,0.0331662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167659,-0.0233536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165347,-0.0380956) , 
4, 0.821937, 1, 0, 0.166925,-0.108213) , 
2, 0.0907355, 1, 0, 0.512102,0.0060764)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66835,0.0167722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209343,-0.021882) , 
5, 14.267, 1, 0, 0.554265,0.0329277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352311,-0.0137319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266392,-0.0501398) , 
4, 0.818634, 1, 0, 0.324446,-0.108404) , 
3, 0.296288, 1, 0, 0.501198,0.000293249)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708362,0.018079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358476,-0.0112159) , 
5, 8.07958, 1, 0, 0.549924,0.0213618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24916,-0.033356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398863,-0.0125567) , 
0, 1041.75, 1, 0, 0.328254,-0.0919892) , 
3, 0.29626, 1, 0, 0.501425,-0.00343859)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665353,0.00704364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318772,-0.0174138) , 
2, 0.0148036, 1, 0, 0.386249,-0.0491035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664623,0.0223375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43212,-0.0230486) , 
4, 0.997061, 1, 0, 0.632082,0.0608637) , 
0, 1243.09, 1, 0, 0.498966,0.00131776)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63667,0.0117198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13094,-0.0298229) , 
5, 18.2141, 1, 0, 0.539129,0.0207982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443306,-0.0165542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909589,-0.0590659) , 
5, 5.03276, 1, 0, 0.327818,-0.12625) , 
4, 1.04245, 1, 0, 0.51483,0.00388873)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810618,0.0284803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49045,-0.017099) , 
3, 0.376476, 1, 0, 0.774789,0.086344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450197,0.00121593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246925,-0.0225447) , 
3, 0.283945, 1, 0, 0.396405,-0.0190523) , 
2, 0.0185082, 1, 0, 0.513711,0.0136224)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636682,0.00887449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138755,-0.0262753) , 
5, 16.1526, 1, 0, 0.515577,0.00777448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484098,-0.0129665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13697,-0.0533924) , 
5, 3.33054, 1, 0, 0.307561,-0.138397) , 
4, 1.02122, 1, 0, 0.486837,-0.012421)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251684,-0.0439868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400793,-0.0107141) , 
1, 2.52074, 1, 0, 0.388636,-0.0543563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189436,-0.0233125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67755,0.0147226) , 
4, 0.0440619, 1, 0, 0.622708,0.0415908) , 
1, 4.34181, 1, 0, 0.504596,-0.00682383)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445281,-0.0054279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703141,0.0210711) , 
1, 4.02097, 1, 0, 0.607713,0.0421795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230055,-0.0103499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100222,-0.0376053) , 
3, 0.215556, 1, 0, 0.170879,-0.0753833) , 
2, 0.0869636, 1, 0, 0.519839,0.0185304)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290092,-0.0258125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40227,-0.00516354) , 
0, 1072.56, 1, 0, 0.325141,-0.0767835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814294,0.037382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528342,0.00153047) , 
5, 2.02838, 1, 0, 0.571275,0.0262135) , 
1, 3.78643, 1, 0, 0.496515,-0.00507052)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601471,0.00246027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228246,-0.0190707) , 
5, 10.6992, 1, 0, 0.46436,-0.0168458) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95669,0.0552713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649358,0.015761) , 
5, 3.07315, 1, 0, 0.724376,0.0885502) , 
0, 2060.61, 1, 0, 0.505849,-2.83185e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833823,0.0493635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831683,0.0193835) , 
4, 0.608795, 1, 0, 0.83275,0.130119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646633,0.00910193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29697,-0.0139774) , 
5, 8.07674, 1, 0, 0.472182,-0.00576194) , 
2, 0.0074058, 1, 0, 0.508069,0.00776213)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373001,-0.0110189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596285,0.00954727) , 
0, 997.383, 1, 0, 0.52415,0.0101434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475034,-0.0171211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120548,-0.0459424) , 
5, 4.84286, 1, 0, 0.355499,-0.105093) , 
4, 0.998362, 1, 0, 0.498939,-0.0070828)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557691,0.00670952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284351,-0.0252413) , 
3, 0.395028, 1, 0, 0.530235,0.0126199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506778,-0.0108398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221768,-0.0388347) , 
5, 2.43931, 1, 0, 0.333212,-0.113154) , 
4, 1.02055, 1, 0, 0.502877,-0.00484475)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477127,0.00232043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774978,0.0301486) , 
1, 5.30928, 1, 0, 0.533564,0.0272829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639635,-0.00589304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161133,-0.034746) , 
2, 0.0703047, 1, 0, 0.461292,-0.0636794) , 
4, 0.910162, 1, 0, 0.517778,0.00741419)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613502,0.00606924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157806,-0.0186187) , 
5, 16.6427, 1, 0, 0.525079,0.00832228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245688,0.00990273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257625,-0.0458828) , 
4, 0.376674, 1, 0, 0.254159,-0.131457) , 
3, 0.394993, 1, 0, 0.496669,-0.00633574)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125337,-0.0386101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64277,0.0134301) , 
4, 0.0446824, 1, 0, 0.579031,0.0306886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396843,-0.00356446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457533,-0.0181519) , 
4, 0.776043, 1, 0, 0.418864,-0.0340372) , 
3, 0.154317, 1, 0, 0.494882,-0.00331722)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358338,-0.01941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600974,0.00668386) , 
1, 3.18207, 1, 0, 0.569559,0.0114031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772197,-0.040726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110133,-0.0243061) , 
5, 24.9293, 1, 0, 0.0992781,-0.0805951) , 
5, 20.4917, 1, 0, 0.502202,-0.0017734)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256327,-0.03664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379487,-0.0101613) , 
0, 795.672, 1, 0, 0.35005,-0.0609914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702517,0.0147524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268699,-0.0133423) , 
5, 11.888, 1, 0, 0.569469,0.0245609) , 
0, 996.557, 1, 0, 0.495487,-0.00428492)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106972,-0.0357564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523553,0.000380504) , 
4, 0.0663156, 1, 0, 0.461445,-0.0128854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656422,0.000712469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.878715,0.0528465) , 
0, 2274.93, 1, 0, 0.789554,0.0995854) , 
1, 5.72655, 1, 0, 0.500163,0.000386673)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619289,-0.00106934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84487,0.0277004) , 
0, 1226.74, 1, 0, 0.745649,0.0477094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392545,-0.00271621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289055,-0.0244001) , 
4, 0.976739, 1, 0, 0.371303,-0.0275926) , 
2, 0.0203659, 1, 0, 0.494434,-0.00282389)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149363,0.000411267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114292,-0.0344633) , 
1, 3.55886, 1, 0, 0.12367,-0.0663247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564285,0.00891766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548685,-0.00666305) , 
4, 0.781148, 1, 0, 0.558525,0.0116406) , 
4, 0.0224734, 1, 0, 0.508885,0.00274059)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792667,0.0182511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472309,-0.0175589) , 
3, 0.376163, 1, 0, 0.757553,0.0457207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446243,0.00684716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33888,-0.0107865) , 
3, 0.0740815, 1, 0, 0.36451,-0.0238302) , 
2, 0.0222028, 1, 0, 0.503815,0.00082044)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186777,-0.0467948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309858,-0.0183294) , 
1, 2.42239, 1, 0, 0.277763,-0.0990176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636606,0.0156546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493917,-0.00284387) , 
3, 0.1111, 1, 0, 0.544001,0.0125302) , 
1, 3.10329, 1, 0, 0.509416,-0.00195998)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840495,0.0248921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492624,-0.0171151) , 
3, 0.314709, 1, 0, 0.772621,0.0488617) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555535,0.00258569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184515,-0.0199475) , 
5, 10.068, 1, 0, 0.403635,-0.0178992) , 
2, 0.016663, 1, 0, 0.507336,0.000863552)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249655,-0.0324513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612747,0.0038595) , 
1, 2.47312, 1, 0, 0.59797,0.00816332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154496,-0.0163226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210505,-0.0275225) , 
1, 4.78323, 1, 0, 0.171154,-0.0649286) , 
2, 0.0795574, 1, 0, 0.493019,-0.00980954)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328696,-0.0203037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638638,0.0122795) , 
1, 3.29207, 1, 0, 0.602129,0.0281548) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412942,-0.00404491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556244,-0.0300461) , 
1, 5.46667, 1, 0, 0.435877,-0.0294629) , 
3, 0.154312, 1, 0, 0.511676,-0.00319337)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397883,-0.00156108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44276,-0.0159418) , 
4, 0.776786, 1, 0, 0.413483,-0.0254359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766372,0.0174036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26803,-0.0135527) , 
2, 0.0795624, 1, 0, 0.667169,0.0337914) , 
1, 4.7609, 1, 0, 0.499582,-0.00533464)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723722,0.0134362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374286,-0.00158891) , 
5, 9.51041, 1, 0, 0.590468,0.0287648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315766,-0.00171904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0975946,-0.0274975) , 
5, 5.51794, 1, 0, 0.158058,-0.0525833) , 
2, 0.0962754, 1, 0, 0.516835,0.0149124)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215246,-0.0484891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335766,-0.00816147) , 
0, 772.071, 1, 0, 0.312614,-0.0572783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525605,0.00334336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626465,-0.0232781) , 
1, 6.03731, 1, 0, 0.53683,0.00241883) , 
0, 869.164, 1, 0, 0.496739,-0.00825534)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511798,0.000666151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264323,-0.0229668) , 
3, 0.364165, 1, 0, 0.47668,-0.00976726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805308,0.0275167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765322,0.0511795) , 
3, 0.196738, 1, 0, 0.793901,0.110061) , 
0, 2229.24, 1, 0, 0.514541,0.00453457)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458929,-0.00149016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609057,-0.0193525) , 
0, 1943.4, 1, 0, 0.482579,-0.0144565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8713,0.0371083) , 
0, 3108.15, 1, 0, 0.497489,-0.00990793)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61979,0.0107034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0885304,-0.0239789) , 
5, 21.9209, 1, 0, 0.546239,0.0264166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269873,-0.030135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249064,-0.00958672) , 
4, 1.25788, 1, 0, 0.261214,-0.0809537) , 
4, 1.0877, 1, 0, 0.51435,0.014404)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485559,-0.00174428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445302,-0.0149881) , 
4, 0.909981, 1, 0, 0.476726,-0.0168736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860356,0.0416393) , 
0, 3371.32, 1, 0, 0.489415,-0.0123893)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488856,-0.0118064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805172,0.0165505) , 
1, 3.38048, 1, 0, 0.751267,0.0339297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429729,-0.0222437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284442,-0.00179146) , 
2, 0.0430007, 1, 0, 0.315624,-0.0243456) , 
2, 0.0296131, 1, 0, 0.500534,0.000389623)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710245,0.014044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471743,-0.00266224) , 
5, 3.46175, 1, 0, 0.532127,0.00612121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261915,-0.0123698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248158,-0.0520803) , 
1, 4.3663, 1, 0, 0.257632,-0.0896406) , 
3, 0.37034, 1, 0, 0.499646,-0.00521023)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704165,-0.00823179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714295,0.020482) , 
3, 0.0555689, 1, 0, 0.712375,0.0558329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455518,-0.00128076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355795,-0.0229568) , 
4, 0.776786, 1, 0, 0.440976,-0.0152823) , 
5, 3.46352, 1, 0, 0.508815,0.00249369)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655163,0.00796739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0899184,-0.0298227) , 
5, 21.2523, 1, 0, 0.57884,0.0150212) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370426,-0.0068872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51668,-0.0274294) , 
0, 1869.81, 1, 0, 0.398407,-0.0375593) , 
3, 0.185188, 1, 0, 0.496129,-0.00908178)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74727,0.0150596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401798,-0.00747572) , 
2, 0.00740181, 1, 0, 0.434217,-0.0183169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648094,-0.00682407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731511,0.0355162) , 
3, 0.141972, 1, 0, 0.686378,0.0423226) , 
0, 1662.84, 1, 0, 0.499816,-0.00254159)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465977,-0.0273928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260351,0.00121189) , 
2, 0.03156, 1, 0, 0.342544,-0.0425069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749414,0.0196068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475714,2.0644e-06) , 
5, 4.47434, 1, 0, 0.564447,0.0220721) , 
0, 914.921, 1, 0, 0.515509,0.00782993)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777145,0.0224394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486569,-0.00127354) , 
5, 2.38514, 1, 0, 0.518657,0.00438415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278127,-0.0306331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548279,-0.0026471) , 
1, 4.70372, 1, 0, 0.370983,-0.0762823) , 
4, 0.976355, 1, 0, 0.493491,-0.00936238)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559544,0.00463351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441695,-0.00915025) , 
3, 0.104956, 1, 0, 0.479268,-0.016194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.894878,0.0524879) , 
0, 3371.22, 1, 0, 0.491972,-0.0115222)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178552,0.011742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311652,-0.019405) , 
4, 0.197695, 1, 0, 0.282897,-0.0551405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792916,0.0280547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518665,-0.00251415) , 
5, 1.14008, 1, 0, 0.537785,-0.00136053) , 
1, 3.29929, 1, 0, 0.496209,-0.0101328)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659884,0.0148487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581347,-0.00556282) , 
4, 0.59952, 1, 0, 0.607507,0.00495089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183219,-0.00638393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178887,-0.0350302) , 
4, 0.217859, 1, 0, 0.182079,-0.0425189) , 
5, 13.6608, 1, 0, 0.490574,-0.00809657)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134218,-0.0269001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627671,0.00663256) , 
4, 0.0225464, 1, 0, 0.574623,0.0134626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263228,0.00579783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418613,-0.0165239) , 
4, 0.310983, 1, 0, 0.367977,-0.0376261) , 
3, 0.222221, 1, 0, 0.498644,-0.00532159)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786312,0.0252436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321568,-0.0274452) , 
3, 0.314775, 1, 0, 0.685291,0.043261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446431,-0.00141275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574747,-0.0279922) , 
1, 5.97865, 1, 0, 0.458266,-0.0126281) , 
5, 2.27739, 1, 0, 0.49601,-0.00333633)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573269,0.0144339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650534,-0.00287553) , 
4, 0.754265, 1, 0, 0.600446,0.0283242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160471,0.00144692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185237,-0.0239207) , 
0, 1023.66, 1, 0, 0.174441,-0.043255) , 
2, 0.0869884, 1, 0, 0.505931,0.0124435)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435503,-0.00834238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655496,0.0105107) , 
0, 1107.45, 1, 0, 0.571373,0.00935814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35417,-0.00837514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472768,-0.0299611) , 
1, 5.28127, 1, 0, 0.373387,-0.0414521) , 
3, 0.216049, 1, 0, 0.495658,-0.0100731)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844164,0.0226047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402727,0.000475259) , 
2, 0.0259063, 1, 0, 0.580155,0.0263798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251764,0.00960468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463229,-0.00889035) , 
4, 0.155198, 1, 0, 0.422535,-0.0220307) , 
3, 0.160498, 1, 0, 0.497184,0.000896546)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589168,0.00567016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488522,-0.00747462) , 
4, 0.910276, 1, 0, 0.563796,0.00832569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0906156,-0.0146926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.094057,-0.0333438) , 
4, 0.0526473, 1, 0, 0.0917707,-0.048048) , 
5, 22.5864, 1, 0, 0.502386,0.000991563)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718076,-0.0029184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.768086,0.0581957) , 
3, 0.154692, 1, 0, 0.74105,0.0974341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478768,0.00105219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473373,-0.0144089) , 
4, 0.821521, 1, 0, 0.477501,-0.00922423) , 
5, 1.139, 1, 0, 0.497194,-0.00125428)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773189,0.0099693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360332,-0.00372553) , 
2, 0.0240727, 1, 0, 0.521716,0.00388498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348847,0.0385673) , 
3, 0.43208, 1, 0, 0.51371,0.00900916)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794931,0.0020321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733516,0.0263687) , 
3, 0.197476, 1, 0, 0.772777,0.0398943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541299,-0.0145887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297064,0.00343321) , 
2, 0.0446146, 1, 0, 0.39949,-0.0158635) , 
2, 0.0166526, 1, 0, 0.502872,-0.000421311)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688612,0.00823289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281185,-0.00907793) , 
5, 10.2363, 1, 0, 0.528832,0.00719521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458181,-0.0432911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333531,-0.00391789) , 
4, 1.05756, 1, 0, 0.366533,-0.0522926) , 
4, 0.998362, 1, 0, 0.503969,-0.00191771)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73118,0.0159859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291499,-0.0263753) , 
3, 0.376505, 1, 0, 0.689767,0.0391859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4268,-0.00337427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263935,-0.0396141) , 
4, 0.732737, 1, 0, 0.40536,-0.0254247) , 
5, 4.75553, 1, 0, 0.501271,-0.00363587)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209166,-0.0368335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458025,0.00635075) , 
0, 780.67, 1, 0, 0.437768,0.00948465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643091,-0.00509674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506771,-0.0219322) , 
3, 0.154273, 1, 0, 0.573305,-0.044916) , 
0, 1369.76, 1, 0, 0.493563,-0.0129101)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592883,0.000819513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553933,0.0335831) , 
4, 1.15352, 1, 0, 0.591327,0.00786597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150523,-0.00648414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180514,-0.0223596) , 
0, 1046.63, 1, 0, 0.167902,-0.0477927) , 
2, 0.0833285, 1, 0, 0.500112,-0.00412418)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557636,-0.00382137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447226,0.0115985) , 
3, 0.22721, 1, 0, 0.522841,0.00368244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200149,-0.0368104) , 
3, 0.438203, 1, 0, 0.507506,-0.00271171)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726974,0.00770184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334408,-0.00432372) , 
2, 0.0222209, 1, 0, 0.468845,-0.00100825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1.00889,0.0770641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649863,0.00723183) , 
5, 4.22597, 1, 0, 0.787757,0.0842199) , 
1, 5.71917, 1, 0, 0.502459,0.00797503)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747713,0.0244321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295288,-0.00494517) , 
5, 9.59368, 1, 0, 0.447182,0.019471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562798,-0.00706949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137295,-0.0519384) , 
3, 0.42586, 1, 0, 0.533568,-0.0360437) , 
4, 0.664549, 1, 0, 0.485368,-0.00506833)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582795,0.0116396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0888563,-0.0207389) , 
5, 22.8567, 1, 0, 0.494771,0.025836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759009,0.0320408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523895,-0.0104529) , 
3, 0.0371166, 1, 0, 0.548713,-0.0208674) , 
4, 0.776529, 1, 0, 0.512792,0.0102339)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379714,-0.00147616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717423,0.01933) , 
4, 0.483645, 1, 0, 0.518702,0.0255827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529862,-0.0303657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476364,-0.00207423) , 
3, 0.0926006, 1, 0, 0.49062,-0.0332928) , 
4, 0.864919, 1, 0, 0.511484,0.0104493)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474511,-0.00714735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454061,0.0230949) , 
3, 0.178989, 1, 0, 0.4651,0.0213792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62604,-0.0023995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286649,-0.0374729) , 
5, 5.00584, 1, 0, 0.539019,-0.0363659) , 
4, 0.688259, 1, 0, 0.498383,-0.00462115)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294682,-0.0321982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0785294,-0.0177387) , 
2, 0.0299428, 1, 0, 0.137085,-0.0566587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672252,0.0169351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530765,-0.000307172) , 
3, 0.0555617, 1, 0, 0.556676,0.00930293) , 
4, 0.0667708, 1, 0, 0.499306,0.000283994)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86369,0.0307641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504464,-0.00532425) , 
2, 0.00370349, 1, 0, 0.518868,-0.0131882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446691,0.0546516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277141,-0.00529286) , 
3, 0.442369, 1, 0, 0.352869,0.0691911) , 
3, 0.388852, 1, 0, 0.504261,-0.00593904)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63831,0.00125336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697357,0.0410399) , 
5, 7.49979, 1, 0, 0.641668,0.0122486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290781,-0.00136848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33946,-0.0287696) , 
4, 0.377198, 1, 0, 0.304539,-0.0302623) , 
5, 8.32189, 1, 0, 0.487453,-0.00719736)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478792,-0.0024703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789551,0.0395006) , 
1, 5.95149, 1, 0, 0.491369,-0.00287608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675548,-0.0285292) , 
1, 6.38452, 1, 0, 0.502501,-0.00743725)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480099,0.001673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428236,-0.0142276) , 
4, 0.886435, 1, 0, 0.467082,-0.00821324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867508,-0.00108157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714757,0.0467233) , 
2, 0.0276096, 1, 0, 0.80424,0.0710229) , 
1, 5.73722, 1, 0, 0.503533,0.000353275)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495198,-0.00268377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764464,0.0215645) , 
1, 3.98796, 1, 0, 0.669367,0.0398995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398814,-0.00526508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20886,-0.0372268) , 
4, 0.710188, 1, 0, 0.379567,-0.0262414) , 
5, 5.68744, 1, 0, 0.498005,0.000789653)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669704,-0.0086291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340198,0.00176525) , 
2, 0.0356071, 1, 0, 0.523862,-0.0127642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125787,-0.024565) , 
2, 0.120302, 1, 0, 0.487411,-0.0176413)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828485,0.028049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531505,0.000818168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315971,-0.0126287) , 
3, 0.308589, 1, 0, 0.486431,-0.00710164) , 
2, 0.00370349, 1, 0, 0.501161,-0.00331433)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367221,-0.00362187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60773,0.0199237) , 
1, 4.91286, 1, 0, 0.429781,0.0078111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608172,-0.00432308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21376,-0.045518) , 
5, 6.54729, 1, 0, 0.548653,-0.0338649) , 
4, 0.64359, 1, 0, 0.483234,-0.0109293)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566541,0.00765122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166909,-0.0149512) , 
2, 0.094439, 1, 0, 0.500014,0.0137713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830041,0.0156569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387961,-0.0154553) , 
2, 0.0168228, 1, 0, 0.494545,-0.0314692) , 
4, 0.797777, 1, 0, 0.498278,-0.00059217)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279376,-0.0101438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488684,0.00863689) , 
1, 3.11465, 1, 0, 0.45654,0.0185691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677725,-0.00644024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437269,-0.0420397) , 
3, 0.283911, 1, 0, 0.633582,-0.0436532) , 
0, 1739.47, 1, 0, 0.500719,0.00304221)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537327,0.00425446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305663,-0.0156864) , 
3, 0.37145, 1, 0, 0.516839,0.00760507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360771,0.0376504) , 
3, 0.462919, 1, 0, 0.512015,0.0108015)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35915,0.000389401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613879,-0.0120945) , 
4, 0.409175, 1, 0, 0.508659,-0.0240185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603737,0.0325575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187905,-0.00164366) , 
5, 3.78265, 1, 0, 0.346755,0.0461555) , 
4, 1.06535, 1, 0, 0.492432,-0.016985)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198262,-0.0133038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599055,0.00683352) , 
4, 0.111242, 1, 0, 0.522476,0.0121837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264549,0.00212989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295132,-0.0294871) , 
1, 3.91754, 1, 0, 0.280234,-0.0533964) , 
3, 0.376508, 1, 0, 0.494962,0.00473519)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702369,-0.00094419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608774,0.02155) , 
3, 0.203688, 1, 0, 0.667213,0.0285261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350392,-0.0113974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66664,0.020003) , 
0, 2437.39, 1, 0, 0.376178,-0.0272969) , 
5, 5.69257, 1, 0, 0.494079,-0.00468265)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69573,0.00442814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774713,0.0452507) , 
5, 0.514178, 1, 0, 0.737647,0.0929202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523516,0.00528579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290716,-0.0130372) , 
4, 0.953741, 1, 0, 0.493977,0.0091662) , 
5, 1.18938, 1, 0, 0.513265,0.0157959)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563676,0.017685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67582,0.001506) , 
4, 0.666075, 1, 0, 0.613487,0.0319041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358603,-0.00199711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485569,-0.0243874) , 
1, 4.67889, 1, 0, 0.40158,-0.0316782) , 
3, 0.154324, 1, 0, 0.4978,-0.00280759)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233792,-0.0345791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406334,0.00697739) , 
0, 803.762, 1, 0, 0.291147,-0.0675717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596824,0.00533925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.092444,-0.0246151) , 
5, 21.399, 1, 0, 0.525253,0.00800556) , 
0, 832.189, 1, 0, 0.496359,-0.0013224)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788519,0.0266822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.835247,-0.0245541) , 
1, 4.7167, 1, 0, 0.804404,0.0457127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634282,-0.0268918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421115,-0.000359595) , 
2, 0.0144491, 1, 0, 0.454346,-0.0139237) , 
2, 0.00740698, 1, 0, 0.492423,-0.00743683)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221591,-0.0263006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0956413,-0.0302853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542981,0.00595357) , 
4, -0.0886444, 1, 0, 0.52207,0.0157064) , 
1, 2.40414, 1, 0, 0.512577,0.012249)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801987,0.0236401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326007,-0.0152406) , 
2, 0.0701983, 1, 0, 0.701301,0.047189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406363,0.00161885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396913,-0.0224909) , 
4, 0.599341, 1, 0, 0.403972,-0.0148886) , 
5, 4.75553, 1, 0, 0.502532,0.00568929)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486152,0.000302238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586091,-0.0149577) , 
4, 0.687093, 1, 0, 0.528343,-0.0204155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554304,0.0381106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373952,-0.000268826) , 
3, 0.264019, 1, 0, 0.403865,0.0176882) , 
3, 0.234528, 1, 0, 0.486975,-0.00775222)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825336,0.0296857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629792,-0.000407141) , 
4, 0.759911, 1, 0, 0.681833,0.0227343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296902,-0.0007738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453673,-0.0197768) , 
4, 0.355519, 1, 0, 0.364106,-0.0294553) , 
5, 5.94425, 1, 0, 0.498622,-0.00735968)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618543,0.00657254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24901,-0.00602942) , 
5, 10.2372, 1, 0, 0.482095,0.00857524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89914,0.0248128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379356,-0.042185) , 
2, 0.0383186, 1, 0, 0.678025,-0.0367192) , 
1, 5.735, 1, 0, 0.506665,0.00289537)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14326,-0.00999704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491389,0.0191246) , 
4, 0.049976, 1, 0, 0.367003,0.0316471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661274,0.00424504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450573,-0.0191104) , 
5, 5.57323, 1, 0, 0.576692,-0.0176966) , 
4, 0.377508, 1, 0, 0.504234,-0.00064595)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661284,0.00467493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260873,-0.0114716) , 
5, 10.7008, 1, 0, 0.521087,-0.00127523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283188,0.00953755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165742,-0.0458819) , 
1, 3.6595, 1, 0, 0.208972,-0.086958) , 
3, 0.407394, 1, 0, 0.495756,-0.00822925)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266715,-0.018417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501706,0.00455591) , 
0, 815.918, 1, 0, 0.472256,0.00536992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758418,0.00316071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504501,-0.0556329) , 
3, 0.156733, 1, 0, 0.640989,-0.0829642) , 
1, 5.81627, 1, 0, 0.491984,-0.00495802)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335481,0.00089636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346666,0.043683) , 
3, 0.197632, 1, 0, 0.339707,0.0422088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532644,0.00302658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66311,-0.0144529) , 
1, 5.0005, 1, 0, 0.571894,-0.00521712) , 
4, 0.288097, 1, 0, 0.505494,0.00834564)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723844,-0.00128639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410395,-0.0335896) , 
2, 0.0288008, 1, 0, 0.694302,-0.0154116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352347,0.00459078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27274,0.0573936) , 
3, 0.321, 1, 0, 0.339881,0.0338413) , 
2, 0.0333314, 1, 0, 0.509928,0.0102104)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829713,0.0166068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419536,-0.0029744) , 
2, 0.0185174, 1, 0, 0.544922,0.00661199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257577,-0.0208883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532089,0.0235212) , 
0, 1588.64, 1, 0, 0.305825,-0.0429968) , 
3, 0.308633, 1, 0, 0.494561,-0.0038371)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468123,-0.00462101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714559,0.0142339) , 
1, 5.10123, 1, 0, 0.534329,-0.000112923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331628,-0.0456622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204299,-0.00104167) , 
2, 0.0239291, 1, 0, 0.250601,-0.073142) , 
3, 0.364143, 1, 0, 0.495031,-0.0102278)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62317,0.0056708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484992,-0.0337289) , 
3, 0.0187736, 1, 0, 0.549302,-0.0487566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570588,0.00529445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398984,-0.00601719) , 
3, 0.22564, 1, 0, 0.49821,0.000918116) , 
3, 0.0370601, 1, 0, 0.504479,-0.00517703)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428816,-0.00535393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649929,0.00778395) , 
1, 4.58389, 1, 0, 0.521956,-0.000648263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198187,0.00019665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429773,0.0299536) , 
0, 959.824, 1, 0, 0.337001,0.0637687) , 
3, 0.395001, 1, 0, 0.505303,0.00515167)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332152,-0.00410884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448544,0.0499258) , 
3, 0.259486, 1, 0, 0.381088,0.0599843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544494,-0.000340555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143155,-0.0171321) , 
2, 0.120344, 1, 0, 0.506422,-0.00526973) , 
1, 2.8125, 1, 0, 0.497203,-0.000470185)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21769,-0.0265735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48826,-0.00146332) , 
1, 2.63892, 1, 0, 0.473367,-0.00948202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864008,0.0184964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49242,-0.0509711) , 
5, 4.609, 1, 0, 0.616098,-0.0877825) , 
1, 5.97869, 1, 0, 0.48758,-0.0172795)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63577,0.00221406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.978743,0.0634717) , 
1, 5.89617, 1, 0, 0.673377,0.0219976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38255,-0.0120164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295276,0.00550673) , 
3, 0.320984, 1, 0, 0.367992,-0.0279238) , 
5, 5.76914, 1, 0, 0.493319,-0.0074367)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428042,0.00557818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563938,-0.00248237) , 
4, 0.66616, 1, 0, 0.486051,0.0061045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859515,0.0591808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781753,0.00226945) , 
0, 2994.03, 1, 0, 0.830591,0.101885) , 
1, 5.735, 1, 0, 0.52459,0.016818)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590323,0.00270778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474395,-0.0105015) , 
3, 0.127559, 1, 0, 0.524551,-0.0155148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438166,0.029202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261507,-0.00244801) , 
3, 0.44929, 1, 0, 0.352099,0.0479083) , 
3, 0.38268, 1, 0, 0.50975,-0.0100713)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59596,0.0063739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676612,0.0337197) , 
3, 0.139059, 1, 0, 0.603177,0.0266679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36362,-0.00986924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594863,0.00767278) , 
1, 4.82518, 1, 0, 0.430844,-0.0156809) , 
3, 0.154303, 1, 0, 0.507903,0.00325549)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold2::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
