// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold6
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:12 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 40764
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold6Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold6Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold6Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold6Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold6Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold6Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold6Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold6Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold6Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold6Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold6Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold6Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold6Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold6Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold6Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797448,0.0594895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408771,-0.0182458) , 
5, 13.6625, 1, 0, 0.726179,0.226179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414674,-0.0170652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0839659,-0.0832068) , 
5, 14.9989, 1, 0, 0.317531,-0.182469) , 
2, 0.0296232, 1, 0, 0.496586,-0.00341422)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804719,0.055448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430884,-0.013168) , 
5, 12.2837, 1, 0, 0.728038,0.206127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440538,-0.010189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127542,-0.0683302) , 
5, 11.5386, 1, 0, 0.317796,-0.164254) , 
2, 0.0314577, 1, 0, 0.505774,0.00545941)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753292,0.0426721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360652,-0.0225869) , 
5, 14.8008, 1, 0, 0.686809,0.156351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402341,-0.0168196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104976,-0.0667383) , 
5, 11.5378, 1, 0, 0.281976,-0.182511) , 
2, 0.0407038, 1, 0, 0.496812,-0.00268458)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682117,0.0292451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2125,-0.0463139) , 
5, 17.8331, 1, 0, 0.618859,0.0938571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321883,-0.0255363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149131,-0.060022) , 
2, 0.0872394, 1, 0, 0.199004,-0.245659) , 
2, 0.0666628, 1, 0, 0.486493,-0.0131814)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811259,0.045833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460358,-0.00561139) , 
2, 0.0240688, 1, 0, 0.605336,0.0752985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.124152,-0.0575161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3336,-0.016802) , 
0, 1822.56, 1, 0, 0.162917,-0.238151) , 
5, 14.7991, 1, 0, 0.498892,-0.000116171)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607687,0.00589369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837316,0.0521293) , 
1, 4.37451, 1, 0, 0.727426,0.143383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467758,-0.00280014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154263,-0.0472206) , 
5, 11.5376, 1, 0, 0.347435,-0.0926621) , 
2, 0.0277762, 1, 0, 0.516269,0.0122151)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678286,0.0228823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150774,-0.0492446) , 
5, 21.4935, 1, 0, 0.624389,0.0749753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347624,-0.0211931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108559,-0.0551036) , 
5, 9.23122, 1, 0, 0.22946,-0.177099) , 
2, 0.0629081, 1, 0, 0.496163,-0.00686887)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486789,-0.0152452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797522,0.0419406) , 
1, 3.78643, 1, 0, 0.705951,0.117603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426181,-0.00668924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0998322,-0.0518039) , 
5, 11.185, 1, 0, 0.289504,-0.113852) , 
2, 0.0407384, 1, 0, 0.510975,0.00923796)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790634,0.0377431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484861,-0.0263512) , 
3, 0.277725, 1, 0, 0.715351,0.101156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268679,-0.0297282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486202,0.0129331) , 
1, 5.07758, 1, 0, 0.316294,-0.0949259) , 
2, 0.0314797, 1, 0, 0.498235,-0.0055271)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461663,-0.0154896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711626,0.0298277) , 
1, 4.01872, 1, 0, 0.620818,0.0617075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553758,0.0079872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208468,-0.0357765) , 
2, 0.00925872, 1, 0, 0.249693,-0.133118) , 
5, 11.3722, 1, 0, 0.49734,-0.0031136)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704637,0.0234309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294152,-0.0218779) , 
2, 0.0648007, 1, 0, 0.589301,0.049054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147832,-0.0395624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0438046,-0.0623523) , 
5, 28.2338, 1, 0, 0.10528,-0.202025) , 
5, 18.1951, 1, 0, 0.503077,0.00432661)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417119,-0.0190549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664324,0.0243429) , 
0, 996.551, 1, 0, 0.587787,0.0487853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295904,-0.0246043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.070545,-0.0534428) , 
5, 8.27293, 1, 0, 0.163107,-0.173883) , 
2, 0.087032, 1, 0, 0.500464,0.00300005)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701962,0.0224363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401517,-0.0332143) , 
3, 0.339456, 1, 0, 0.662092,0.0670692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284354,-0.0145101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167125,-0.0514495) , 
4, 1.04315, 1, 0, 0.261989,-0.0971155) , 
2, 0.0499971, 1, 0, 0.50704,0.00344245)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725736,0.0293153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427465,-0.0227121) , 
4, 0.97929, 1, 0, 0.646389,0.0696528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244523,-0.0337094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489945,0.00260139) , 
0, 1557.02, 1, 0, 0.311516,-0.099996) , 
5, 7.96905, 1, 0, 0.49074,-0.00920002)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66923,0.0166528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23268,-0.0272506) , 
2, 0.0907355, 1, 0, 0.589133,0.0390445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276503,-0.0197259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0366867,-0.0537203) , 
2, 0.0519011, 1, 0, 0.139095,-0.142732) , 
5, 16.6436, 1, 0, 0.495703,0.00130682)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25577,-0.0394415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385764,-0.016242) , 
0, 879.03, 1, 0, 0.339627,-0.107792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173205,-0.03787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622516,0.0145359) , 
4, 0.065915, 1, 0, 0.565048,0.0366444) , 
1, 3.85744, 1, 0, 0.492034,-0.0101386)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782206,0.0280364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365786,-0.0471558) , 
3, 0.388819, 1, 0, 0.74083,0.0855176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237875,-0.0297701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417047,0.00095912) , 
1, 4.2835, 1, 0, 0.325237,-0.0633962) , 
2, 0.0277762, 1, 0, 0.497173,-0.0017889)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621102,0.0114216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132286,-0.0354413) , 
5, 19.0203, 1, 0, 0.54702,0.0225363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333404,-0.0203595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285218,-0.0507009) , 
4, 0.731031, 1, 0, 0.31515,-0.143024) , 
3, 0.296289, 1, 0, 0.495642,-0.0141487)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689808,0.0245963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212315,-0.0216449) , 
2, 0.0869712, 1, 0, 0.596755,0.0681774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391395,-0.0202805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77572,0.0393144) , 
0, 2541.59, 1, 0, 0.41474,-0.0713127) , 
3, 0.148152, 1, 0, 0.496035,-0.00901122)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414822,-0.0169887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676872,0.0185239) , 
1, 3.78654, 1, 0, 0.60259,0.0346924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212215,-0.0173053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114647,-0.0501968) , 
4, 0.954547, 1, 0, 0.187782,-0.103796) , 
2, 0.0777733, 1, 0, 0.499939,0.000421329)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644034,0.00738944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312412,-0.0201368) , 
2, 0.0129622, 1, 0, 0.379904,-0.0605234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811928,0.0377068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526685,0.00281439) , 
5, 4.62737, 1, 0, 0.633485,0.0657335) , 
1, 4.35476, 1, 0, 0.502946,0.000738874)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573088,-0.00854867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784489,0.0234296) , 
0, 911.603, 1, 0, 0.744721,0.0692327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340773,-0.0153022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63884,0.0202459) , 
1, 5.72664, 1, 0, 0.374062,-0.0471309) , 
2, 0.0185174, 1, 0, 0.491545,-0.0102485)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332847,-0.0292884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625136,0.0142929) , 
1, 3.10329, 1, 0, 0.59149,0.0381388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209003,-0.0161371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0747009,-0.0461153) , 
5, 23.2613, 1, 0, 0.110569,-0.127125) , 
5, 19.6135, 1, 0, 0.516139,0.0122453)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779305,0.0225549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431699,-0.0266523) , 
3, 0.364133, 1, 0, 0.736868,0.0636116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402657,0.00149129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282583,-0.0196431) , 
3, 0.141958, 1, 0, 0.334309,-0.0434255) , 
2, 0.0277717, 1, 0, 0.502552,0.00130886)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678468,0.0173107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308315,-0.0153264) , 
5, 10.2352, 1, 0, 0.545491,0.025512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333922,-0.0193874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193677,-0.0591958) , 
4, 0.841191, 1, 0, 0.284817,-0.146092) , 
3, 0.351845, 1, 0, 0.509522,0.00183312)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695858,0.0174289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38469,-0.0266034) , 
4, 1.0459, 1, 0, 0.642204,0.0397842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320615,-0.0104739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214688,-0.0490113) , 
4, 0.488195, 1, 0, 0.306013,-0.0612635) , 
5, 9.23028, 1, 0, 0.50866,-0.000354833)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182965,-0.0468461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336052,-0.0160576) , 
1, 2.44187, 1, 0, 0.319406,-0.0790153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664797,0.0129822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191652,-0.0221741) , 
2, 0.090721, 1, 0, 0.573569,0.0262189) , 
1, 3.78791, 1, 0, 0.495429,-0.00613431)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709007,0.0191821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436594,-0.0154173) , 
4, 0.9997, 1, 0, 0.65163,0.0485365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318113,-0.00807315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0492791,-0.048953) , 
5, 28.8464, 1, 0, 0.269193,-0.0509125) , 
5, 10.3839, 1, 0, 0.509036,0.0114563)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0925484,-0.0441657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223253,-0.0236582) , 
4, 0.00403627, 1, 0, 0.153254,-0.111013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688156,0.0119137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266408,-0.0149018) , 
2, 0.0648111, 1, 0, 0.557588,0.0145334) , 
4, 0.111428, 1, 0, 0.486515,-0.00753477)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341867,-0.0226587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608069,0.0123697) , 
0, 914.409, 1, 0, 0.550728,0.0185557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308438,-0.0157027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332717,-0.0379141) , 
4, 0.666364, 1, 0, 0.319772,-0.108573) , 
3, 0.283851, 1, 0, 0.495201,-0.012009)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645759,-0.000675172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92355,0.0459021) , 
1, 4.74582, 1, 0, 0.746828,0.0536879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365996,-0.0118935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182982,-0.0411559) , 
3, 0.370301, 1, 0, 0.344386,-0.0610888) , 
2, 0.020359, 1, 0, 0.474694,-0.0239248)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605621,0.00745821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125729,-0.0280262) , 
5, 19.3533, 1, 0, 0.521737,0.0101452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496379,-0.0019507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12487,-0.0528003) , 
5, 4.5421, 1, 0, 0.279583,-0.123729) , 
4, 1.08779, 1, 0, 0.500012,-0.00186578)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187608,-0.0540732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396137,-0.00984055) , 
0, 775.374, 1, 0, 0.377426,-0.0539114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740041,0.0349699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556506,0.00365415) , 
3, 0.0741059, 1, 0, 0.601098,0.0423431) , 
0, 1160.91, 1, 0, 0.496042,-0.00286626)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302016,-0.0248866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593773,0.0108453) , 
1, 3.29962, 1, 0, 0.552066,0.020651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316656,-0.0108449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304676,-0.0393175) , 
1, 4.5974, 1, 0, 0.312719,-0.0798109) , 
3, 0.2901, 1, 0, 0.493499,-0.00393155)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689574,0.0096926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314798,-0.0114845) , 
2, 0.020355, 1, 0, 0.433965,-0.0177053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730732,0.0333578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625265,-0.00314268) , 
4, 0.863997, 1, 0, 0.700327,0.0831738) , 
1, 5.08564, 1, 0, 0.499249,0.00701972)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742118,0.0255867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598409,0.0010382) , 
4, 0.688874, 1, 0, 0.644931,0.0354639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314437,-0.0100416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130469,-0.0533736) , 
4, 0.576992, 1, 0, 0.295436,-0.0513836) , 
5, 8.94794, 1, 0, 0.500112,-0.000522902)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664005,0.0194183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10192,-0.0313092) , 
5, 23.6141, 1, 0, 0.601436,0.0561637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464146,-0.001676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232914,-0.0335509) , 
4, 1.04315, 1, 0, 0.434483,-0.0222445) , 
3, 0.16048, 1, 0, 0.513744,0.0149798)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713049,0.0173872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388377,-0.00742158) , 
5, 7.18737, 1, 0, 0.556575,0.0218551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295834,-0.00347235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311663,-0.030759) , 
4, 0.616188, 1, 0, 0.30397,-0.0732085) , 
3, 0.320982, 1, 0, 0.505625,0.00268088)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635086,0.0103224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122613,-0.0270903) , 
5, 17.4541, 1, 0, 0.528986,0.0165034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430918,-0.0127672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0966122,-0.0531162) , 
5, 4.84631, 1, 0, 0.301067,-0.107171) , 
4, 1.04264, 1, 0, 0.503105,0.00245993)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876764,0.0303112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504994,-0.000949106) , 
2, 0.0239794, 1, 0, 0.67372,0.0422583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401535,-0.00705416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165184,-0.0483564) , 
4, 0.732644, 1, 0, 0.37781,-0.0411175) , 
5, 5.76935, 1, 0, 0.503688,-0.00565007)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258254,-0.0377497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0967981,-0.0258897) , 
5, 18.6933, 1, 0, 0.140237,-0.0862845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610967,0.00926085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330658,-0.0157645) , 
3, 0.314789, 1, 0, 0.555182,0.0153636) , 
4, 0.0664082, 1, 0, 0.499512,0.0017263)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195247,-0.0429392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446802,-0.00533042) , 
1, 2.5058, 1, 0, 0.433921,-0.0271442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778055,0.0341934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586841,-0.00123996) , 
3, 0.140544, 1, 0, 0.685849,0.0572138) , 
1, 5.14917, 1, 0, 0.493283,-0.00726689)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525085,-0.00236175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876288,0.0444118) , 
1, 4.34324, 1, 0, 0.70307,0.0722443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538168,0.00053675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15061,-0.0243522) , 
2, 0.0925725, 1, 0, 0.459544,-0.0141392) , 
5, 2.27517, 1, 0, 0.499204,-7.102e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813802,0.0553181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830256,0.0198314) , 
4, 0.399313, 1, 0, 0.825497,0.109288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585352,0.00966078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413272,-0.00849859) , 
3, 0.111132, 1, 0, 0.470487,-0.00923806) , 
2, 0.0074058, 1, 0, 0.507643,0.00316712)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724754,0.0145879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424145,-0.0132988) , 
3, 0.295974, 1, 0, 0.66422,0.0314675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416231,-0.00478672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260201,-0.0400495) , 
4, 0.732644, 1, 0, 0.394617,-0.0350571) , 
5, 4.75553, 1, 0, 0.489087,-0.0117465)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732671,0.0154025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358875,-0.0126226) , 
2, 0.0111014, 1, 0, 0.413105,-0.0309227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831473,0.0290473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511834,0.000159999) , 
5, 5.7745, 1, 0, 0.648184,0.041242) , 
0, 1464.88, 1, 0, 0.495337,-0.00567902)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129245,-0.0286283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594027,0.00654715) , 
4, 0.0666957, 1, 0, 0.522244,0.00894469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397637,-0.0300959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344457,-0.00765756) , 
3, 0.178769, 1, 0, 0.371724,-0.0729406) , 
4, 0.99821, 1, 0, 0.499952,-0.00318237)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640307,0.00905354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.913404,0.04512) , 
0, 1795.15, 1, 0, 0.711432,0.0618003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472594,0.00441215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406031,-0.0249062) , 
4, 0.798637, 1, 0, 0.459096,-0.00652412) , 
5, 2.30826, 1, 0, 0.505002,0.0059057)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657094,0.00434934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329982,-0.0102765) , 
5, 7.96092, 1, 0, 0.50865,-0.00711746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305492,-0.0400795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166047,-0.016469) , 
2, 0.0352825, 1, 0, 0.235838,-0.117963) , 
3, 0.419669, 1, 0, 0.489969,-0.0147078)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723921,0.0162492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350077,-0.00558527) , 
5, 7.83139, 1, 0, 0.509794,0.0151937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661282,0.00317719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363601,-0.024794) , 
5, 1.37765, 1, 0, 0.474995,-0.0521702) , 
4, 0.88797, 1, 0, 0.501597,-0.000674852)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155914,-0.0515001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385712,-0.00784915) , 
0, 772.224, 1, 0, 0.364452,-0.0428011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661549,0.013571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183869,-0.0200782) , 
2, 0.0980933, 1, 0, 0.599614,0.0330565) , 
0, 1107.59, 1, 0, 0.498053,0.00029534)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280785,-0.032429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560623,0.00552746) , 
1, 2.64616, 1, 0, 0.547404,0.0125769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363582,-0.0362171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224567,-0.00451607) , 
2, 0.0202795, 1, 0, 0.270538,-0.0637553) , 
3, 0.339456, 1, 0, 0.504105,0.000639325)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711465,0.013451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.01197,0.0673474) , 
1, 4.64501, 1, 0, 0.825215,0.0944221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690091,0.0140631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409407,-0.00656226) , 
5, 3.07082, 1, 0, 0.471215,-0.00663407) , 
2, 0.00740326, 1, 0, 0.506812,0.00352778)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392581,-0.00402562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421339,-0.0324839) , 
1, 4.25468, 1, 0, 0.394682,-0.0227897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659818,0.0144523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350002,-0.024031) , 
3, 0.36413, 1, 0, 0.637718,0.0378192) , 
1, 4.34167, 1, 0, 0.515161,0.00725574)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471595,-0.0181854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790474,0.0145581) , 
1, 3.37371, 1, 0, 0.738346,0.0257977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475035,0.0135692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320055,-0.0116879) , 
3, 0.0370661, 1, 0, 0.338069,-0.0310794) , 
2, 0.0240688, 1, 0, 0.493935,-0.00893167)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601919,0.001435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413669,0.0318663) , 
2, 0.0693023, 1, 0, 0.589887,0.0121414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151518,-0.00599762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214831,-0.0223159) , 
4, 0.529322, 1, 0, 0.181392,-0.0475743) , 
2, 0.0814127, 1, 0, 0.492694,-0.00206686)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444473,-0.0200629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32602,-0.00243722) , 
5, 4.55423, 1, 0, 0.365113,-0.0327042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911973,0.0583929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5793,0.00429116) , 
5, 1.15544, 1, 0, 0.604108,0.026787) , 
1, 4.13665, 1, 0, 0.501136,0.00115503)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0916068,-0.0367793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165995,-0.0182205) , 
4, -0.0402719, 1, 0, 0.127848,-0.0696516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574068,0.006276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49577,-0.0100881) , 
4, 0.907559, 1, 0, 0.554161,0.00792234) , 
4, 0.0442089, 1, 0, 0.501625,-0.0016373)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440032,-0.0120198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241609,0.0165972) , 
2, 0.0740181, 1, 0, 0.379465,-0.0190978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700633,0.0130544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258443,-0.00829472) , 
2, 0.0666522, 1, 0, 0.588319,0.0257246) , 
0, 1078.73, 1, 0, 0.504261,0.00768479)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0757815,-0.0377644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543202,0.0049135) , 
4, -0.0794023, 1, 0, 0.516553,0.011474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276096,-0.0252998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561734,-0.000766986) , 
1, 4.74003, 1, 0, 0.366839,-0.0633205) , 
4, 1.02098, 1, 0, 0.496039,0.00122553)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721078,0.0183142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584,-0.00219443) , 
4, 0.711904, 1, 0, 0.638154,0.0215766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162165,-0.0253811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407225,0.00275215) , 
0, 1325.28, 1, 0, 0.261936,-0.038196) , 
5, 10.2458, 1, 0, 0.49774,-0.000732113)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698219,0.0101884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292478,-0.0268876) , 
3, 0.413496, 1, 0, 0.669881,0.0248661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319507,0.000411494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39366,-0.0208872) , 
4, 0.37736, 1, 0, 0.346226,-0.0265548) , 
5, 6.92288, 1, 0, 0.504917,-0.00134272)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509183,-0.00820567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.09124,0.110982) , 
1, 4.30947, 1, 0, 0.762517,0.106228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501471,-0.000904727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373867,-0.0197402) , 
4, 0.910269, 1, 0, 0.481983,-0.0135898) , 
5, 1.13786, 1, 0, 0.501315,-0.00533303)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19774,-0.0311437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837784,0.0300448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490003,0.000329516) , 
2, 0.00555245, 1, 0, 0.514469,0.00774988) , 
1, 2.47312, 1, 0, 0.502432,0.00339423)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452374,0.00141638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53189,-0.0326198) , 
1, 5.29956, 1, 0, 0.464865,-0.0124762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859084,0.0526387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731464,0.000272719) , 
4, 0.775342, 1, 0, 0.81202,0.099501) , 
0, 2537.25, 1, 0, 0.493748,-0.00316)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714979,0.0292956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.828263,0.0127723) , 
4, 0.393931, 1, 0, 0.795569,0.0582148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206591,-0.0233719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479371,-0.00105335) , 
1, 2.97477, 1, 0, 0.451985,-0.0109183) , 
2, 0.00925872, 1, 0, 0.502724,-0.000708958)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759166,0.0200596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595081,-0.00265547) , 
4, 0.846377, 1, 0, 0.67043,0.0263412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375111,-0.00330695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360178,-0.0237534) , 
4, 0.599034, 1, 0, 0.372451,-0.0237566) , 
5, 5.94425, 1, 0, 0.49734,-0.00275972)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782876,0.00753298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457064,0.0271412) , 
5, 19.0236, 1, 0, 0.749451,0.0323386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481475,-0.00152974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893141,-0.0262107) , 
5, 14.5402, 1, 0, 0.367289,-0.021863) , 
2, 0.0185017, 1, 0, 0.488564,-0.00466269)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168132,-0.0146032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614742,0.0110005) , 
4, 0.0670668, 1, 0, 0.546675,0.0269547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289163,-0.0254069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24628,0.00835243) , 
5, 7.12402, 1, 0, 0.268322,-0.0427968) , 
3, 0.370357, 1, 0, 0.511833,0.0182239)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513576,0.000455502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805785,0.0221877) , 
0, 2298.91, 1, 0, 0.550949,0.00965316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134228,-0.023888) , 
2, 0.112899, 1, 0, 0.509822,0.00205399)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580928,0.00530665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463622,-0.00811014) , 
4, 0.90758, 1, 0, 0.551035,0.00692034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0621735,-0.022278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111767,-0.0317596) , 
0, 1355.42, 1, 0, 0.0813148,-0.0553628) , 
5, 23.9058, 1, 0, 0.500498,0.000219347)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833356,0.0315964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679162,0.0038128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429314,-0.0100476) , 
5, 2.27734, 1, 0, 0.470079,-0.0262371) , 
2, 0.00370163, 1, 0, 0.481572,-0.0223927)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610284,0.0178763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569507,-0.00170566) , 
4, 0.687168, 1, 0, 0.589946,0.0297312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.078688,-0.016176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158079,-0.0284282) , 
0, 1345.75, 1, 0, 0.108122,-0.0505333) , 
5, 19.0202, 1, 0, 0.506749,0.0158718)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475298,-0.00516732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769913,0.0194709) , 
0, 982.395, 1, 0, 0.679174,0.0375332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309841,0.0038776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492328,-0.0115092) , 
4, 0.332732, 1, 0, 0.406768,-0.0169763) , 
5, 4.75553, 1, 0, 0.499994,0.00167846)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711245,0.0156546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219043,-0.0253129) , 
2, 0.111087, 1, 0, 0.670682,0.0411403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282833,-0.00285083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30969,-0.021507) , 
4, 0.376998, 1, 0, 0.288939,-0.0229023) , 
5, 9.24071, 1, 0, 0.509692,0.0141321)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811957,0.0306852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430104,0.000518684) , 
2, 0.00555239, 1, 0, 0.455877,0.00880117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820119,0.00640542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525705,-0.020224) , 
5, 4.49555, 1, 0, 0.641578,-0.0341341) , 
1, 4.98759, 1, 0, 0.51201,-0.00417709)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494663,-0.0193559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429994,-0.000615175) , 
5, 1.14331, 1, 0, 0.434811,-0.00738677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782732,0.0171504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306543,-0.00485535) , 
2, 0.0703065, 1, 0, 0.685198,0.0361277) , 
0, 1563.82, 1, 0, 0.510876,0.0058325)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40192,-0.0012255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450964,-0.0162293) , 
0, 1191.26, 1, 0, 0.414573,-0.0176092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659048,0.0221043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699334,0.00303039) , 
0, 2016.5, 1, 0, 0.679589,0.0400183) , 
0, 1464.89, 1, 0, 0.503444,0.00171575)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617442,0.0171782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571973,-0.0101555) , 
4, 0.909578, 1, 0, 0.607447,0.0345024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406065,0.00307057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488128,-0.0292072) , 
1, 4.97534, 1, 0, 0.428324,-0.0201017) , 
3, 0.154302, 1, 0, 0.512844,0.00566346)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555496,0.00983611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105348,-0.0188924) , 
5, 21.6375, 1, 0, 0.45002,0.0168917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684614,0.00795447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484406,-0.0201093) , 
5, 2.38604, 1, 0, 0.559922,-0.0325464) , 
4, 0.643874, 1, 0, 0.500593,-0.00585781)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493022,3.60244e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834258,0.0302863) , 
0, 2298.9, 1, 0, 0.534742,0.0100008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24398,-0.00328224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234715,-0.0372913) , 
4, 0.489824, 1, 0, 0.238645,-0.0912109) , 
3, 0.407391, 1, 0, 0.512537,0.00241083)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540606,0.00526617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459198,-0.0101681) , 
4, 0.932157, 1, 0, 0.523209,0.00626399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26042,-0.0378664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121422,-0.0245561) , 
2, 0.0331268, 1, 0, 0.190616,-0.115006) , 
3, 0.432019, 1, 0, 0.502854,-0.00115781)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520256,-0.00436944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374203,0.0157431) , 
3, 0.332675, 1, 0, 0.502032,-0.00557436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165773,-0.0338995) , 
3, 0.456745, 1, 0, 0.48946,-0.00949884)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661207,-0.0391961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399787,-0.00315099) , 
2, 0.0314484, 1, 0, 0.51699,-0.0552635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526844,0.0026207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104983,-0.028248) , 
2, 0.120344, 1, 0, 0.489585,0.00157977) , 
3, 0.0493913, 1, 0, 0.493901,-0.0073737)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735863,0.00830697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435766,-0.00643517) , 
5, 4.75574, 1, 0, 0.538113,-0.00469744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430371,0.0281422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270785,-0.0042751) , 
3, 0.416026, 1, 0, 0.36464,0.0480525) , 
3, 0.320984, 1, 0, 0.510526,0.0036911)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586542,0.00252304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670139,0.0345466) , 
3, 0.135239, 1, 0, 0.594568,0.0173114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396817,-0.00058269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431478,-0.0194159) , 
4, 0.686751, 1, 0, 0.411568,-0.0299849) , 
3, 0.154307, 1, 0, 0.493993,-0.00868199)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549223,-0.0116246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.884807,0.0215583) , 
0, 2557.96, 1, 0, 0.579135,-0.032375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436086,0.0484096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208115,0.00029428) , 
2, 0.0765675, 1, 0, 0.236491,0.0195157) , 
2, 0.0685145, 1, 0, 0.483079,-0.0178281)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582015,0.00158937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645155,0.0390382) , 
3, 0.197349, 1, 0, 0.58656,0.0144374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378613,-0.00114007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4808,-0.0283424) , 
0, 1906.96, 1, 0, 0.396278,-0.0211471) , 
3, 0.216018, 1, 0, 0.511306,0.00036432)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718524,-0.00819762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769561,0.0570661) , 
3, 0.148137, 1, 0, 0.743737,0.0838241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582578,0.00558918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387257,-0.0103803) , 
3, 0.160516, 1, 0, 0.477457,-0.0105206) , 
5, 1.19128, 1, 0, 0.497414,-0.00344983)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488345,-0.00152027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423521,-0.0164513) , 
4, 0.92927, 1, 0, 0.474256,-0.0154949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612334,-0.0430591) , 
1, 6.54699, 1, 0, 0.48033,-0.0203402)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422189,-0.0240541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404072,-0.00238705) , 
3, 0.0309041, 1, 0, 0.405745,-0.0149979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702209,0.0035064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6198,0.0230568) , 
3, 0.190981, 1, 0, 0.672953,0.0335623) , 
1, 4.74546, 1, 0, 0.498717,0.00189805)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187061,-0.0288094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671321,0.0101412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328984,-0.00247472) , 
5, 8.32174, 1, 0, 0.515875,0.015211) , 
1, 2.4733, 1, 0, 0.504711,0.0114434)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261637,-0.0244184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486634,0.0079212) , 
0, 798.719, 1, 0, 0.462833,0.0148208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632285,0.00383946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645095,-0.0273191) , 
4, 0.710594, 1, 0, 0.637969,-0.0284185) , 
0, 1736.19, 1, 0, 0.509469,0.00330691)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302552,-0.0118397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488791,0.00813342) , 
0, 811.793, 1, 0, 0.463481,0.0182155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703282,0.000625382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470238,-0.0221081) , 
3, 0.222199, 1, 0, 0.631697,-0.0235683) , 
0, 1584.05, 1, 0, 0.518559,0.00453449)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348233,-0.0303847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369722,-0.00744391) , 
3, 0.0370464, 1, 0, 0.367191,-0.0349466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.871044,0.0202302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448309,-0.00469) , 
2, 0.0240688, 1, 0, 0.619581,0.00982974) , 
1, 4.34167, 1, 0, 0.490041,-0.0131518)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148087,-0.0189502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613255,0.0133166) , 
4, 0.0717913, 1, 0, 0.513824,0.0269981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807959,0.0111902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362681,-0.0131695) , 
2, 0.0240516, 1, 0, 0.521344,-0.0192152) , 
4, 0.799222, 1, 0, 0.516292,0.0118287)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435951,-0.00266743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56827,-0.0234322) , 
0, 1982.71, 1, 0, 0.444669,-0.0132508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952227,0.0477683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46682,-0.00606906) , 
2, 0.0276038, 1, 0, 0.692906,0.0350615) , 
1, 5.248, 1, 0, 0.498383,-0.00279675)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713965,-0.00311618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344247,0.00577501) , 
2, 0.0444419, 1, 0, 0.562466,0.0023291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35249,-0.027376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28808,-0.00740608) , 
3, 0.328997, 1, 0, 0.304689,-0.0437301) , 
3, 0.296288, 1, 0, 0.504159,-0.00808917)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642884,-0.0336967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458802,0.00971491) , 
2, 0.0074058, 1, 0, 0.47883,0.0170718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604381,-0.00655644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256495,-0.0361662) , 
5, 5.00832, 1, 0, 0.535723,-0.0391622) , 
4, 0.731807, 1, 0, 0.500375,-0.00422354)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641245,0.0074266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163303,-0.013167) , 
5, 15.454, 1, 0, 0.532311,0.0119588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2552,-0.00328158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27674,-0.0458834) , 
1, 4.30107, 1, 0, 0.262526,-0.0686608) , 
3, 0.364164, 1, 0, 0.498517,0.0018602)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382777,-0.0163651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715336,0.0148203) , 
1, 3.22117, 1, 0, 0.66893,0.032269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346628,-0.000153345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339379,-0.0198435) , 
4, 0.487754, 1, 0, 0.345059,-0.0142308) , 
5, 7.13302, 1, 0, 0.505755,0.0088412)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704632,0.00807806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374894,-0.00689378) , 
5, 6.92284, 1, 0, 0.540737,0.00270531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244581,0.0050683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495321,0.0598312) , 
4, 0.533049, 1, 0, 0.35543,0.0990064) , 
3, 0.382702, 1, 0, 0.524765,0.0110056)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535035,0.00189944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653957,-0.0278466) , 
0, 2804.51, 1, 0, 0.543285,0.000515687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100257,-0.0303636) , 
2, 0.118452, 1, 0, 0.505168,-0.00621912)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0620063,-0.0376407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345643,0.0171733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570882,-0.0034928) , 
4, 0.201111, 1, 0, 0.531246,-0.00117853) , 
4, -0.0660745, 1, 0, 0.504139,-0.00492035)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801173,0.015376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629565,-0.0117302) , 
2, 0.0057807, 1, 0, 0.653484,-0.0266389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428624,0.0177766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196067,-0.00733483) , 
2, 0.0770299, 1, 0, 0.298544,0.0159818) , 
2, 0.0425688, 1, 0, 0.498733,-0.00805661)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148576,0.00404695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148116,-0.0257541) , 
4, -0.0283124, 1, 0, 0.148355,-0.0288304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520178,0.0188297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590967,0.00110348) , 
4, 0.350617, 1, 0, 0.575459,0.0170181) , 
4, 0.0670481, 1, 0, 0.5186,0.0109144)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744888,0.0175489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615407,0.00138673) , 
3, 0.0802702, 1, 0, 0.648452,0.017346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202537,-0.000624302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234952,-0.0205511) , 
0, 1043.72, 1, 0, 0.220844,-0.039388) , 
2, 0.0574041, 1, 0, 0.494818,-0.00303777)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365436,-0.00353506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547987,0.0166037) , 
1, 4.11713, 1, 0, 0.424142,0.00928479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56205,-0.0152379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738712,0.0144797) , 
1, 5.88243, 1, 0, 0.604182,-0.0261734) , 
1, 4.67965, 1, 0, 0.493868,-0.00444746)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569186,-0.0050839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435869,-0.0376456) , 
3, 0.155875, 1, 0, 0.541193,-0.0379636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443308,0.0100273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276972,-0.01373) , 
4, 0.996754, 1, 0, 0.415068,0.021251) , 
3, 0.203676, 1, 0, 0.49228,-0.0149995)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690727,0.00578969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328533,-0.0205332) , 
3, 0.370306, 1, 0, 0.646981,0.00673475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712069,0.0135798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27633,-0.0120836) , 
2, 0.00740326, 1, 0, 0.317388,-0.0285698) , 
5, 8.32174, 1, 0, 0.498173,-0.0092049)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65349,-0.012884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742828,0.0231304) , 
5, 0.583574, 1, 0, 0.7172,0.0415975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662261,-0.0229144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420805,0.000602923) , 
2, 0.00925872, 1, 0, 0.454105,-0.00809938) , 
5, 2.04922, 1, 0, 0.492716,-0.000806066)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322261,0.0018263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623407,0.0300869) , 
1, 4.95036, 1, 0, 0.393982,0.0261884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638276,0.0021354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437731,-0.0175962) , 
5, 5.48887, 1, 0, 0.565354,-0.0169588) , 
4, 0.444126, 1, 0, 0.501181,-0.000801523)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83428,0.0107246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491183,-0.00539682) , 
2, 0.00925398, 1, 0, 0.538804,-0.0114745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293485,0.000300717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580545,0.0317784) , 
0, 1266.08, 1, 0, 0.39638,0.0397645) , 
3, 0.265383, 1, 0, 0.501363,0.00199523)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221481,-0.0267905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505014,0.000138915) , 
0, 780.894, 1, 0, 0.489327,-0.00424713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793962,0.0272671) , 
0, 3252.07, 1, 0, 0.499499,-0.00151827)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52935,-0.0021827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491628,0.0527053) , 
3, 0.333544, 1, 0, 0.527883,-0.000619841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342767,0.0251546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225234,-0.0414689) , 
1, 3.69869, 1, 0, 0.267154,-0.0726544) , 
3, 0.370306, 1, 0, 0.49388,-0.0100143)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618011,0.0216862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762384,-0.000790664) , 
0, 1214.78, 1, 0, 0.693958,0.0381756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575665,0.00315196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164907,-0.014499) , 
2, 0.0666522, 1, 0, 0.440826,-0.00566218) , 
5, 3.4636, 1, 0, 0.503774,0.00523915)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462398,0.00361614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585272,-0.00805802) , 
4, 0.686198, 1, 0, 0.511593,-0.00416464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334951,0.0416718) , 
4, 1.26517, 1, 0, 0.505506,-0.000597048)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788429,0.0288544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424004,-0.000537242) , 
2, 0.0037009, 1, 0, 0.440977,0.0030326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543284,-0.0203955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770105,0.0220402) , 
0, 2599.47, 1, 0, 0.587711,-0.0406515) , 
1, 4.74537, 1, 0, 0.495616,-0.0132339)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539474,-0.00133983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473326,0.0233331) , 
3, 0.294411, 1, 0, 0.534187,0.00251256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260854,-0.0298878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310866,0.0102491) , 
3, 0.418016, 1, 0, 0.282044,-0.046629) , 
3, 0.34562, 1, 0, 0.494301,-0.00526092)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679835,-0.0116395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588266,0.0208308) , 
4, 1.0171, 1, 0, 0.657901,-0.0103738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611867,0.0138798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181267,-0.00369986) , 
5, 15.4742, 1, 0, 0.479249,0.0305277) , 
5, 3.41568, 1, 0, 0.526357,0.0197426)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380739,-0.00965249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650021,0.00821139) , 
0, 1078.75, 1, 0, 0.544192,0.00252956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257245,0.000179785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297208,-0.0261634) , 
1, 3.75395, 1, 0, 0.281893,-0.0544195) , 
3, 0.290116, 1, 0, 0.481424,-0.0110983)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698836,-0.00108303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605404,0.0262298) , 
3, 0.246838, 1, 0, 0.673941,0.0236125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320188,-0.00298161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432194,-0.0153979) , 
4, 0.399898, 1, 0, 0.366912,-0.0268408) , 
5, 5.69237, 1, 0, 0.490278,-0.00656837)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653538,0.0102142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454125,-0.00616601) , 
4, 0.910265, 1, 0, 0.597249,0.019327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149373,0.00246307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138203,-0.0331023) , 
4, 0.175434, 1, 0, 0.146158,-0.0239653) , 
5, 16.1539, 1, 0, 0.508968,0.0108545)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391183,-0.00177786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396945,-0.0345464) , 
1, 4.8005, 1, 0, 0.391724,-0.0160509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643325,0.00519155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545315,0.0297705) , 
4, 1.04111, 1, 0, 0.631962,0.0243714) , 
0, 1238.29, 1, 0, 0.506433,0.00324998)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561681,-0.00155181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557765,0.0194885) , 
3, 0.175552, 1, 0, 0.560998,0.00664137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414593,-0.0146706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298494,0.00736447) , 
3, 0.352481, 1, 0, 0.372801,-0.0229922) , 
3, 0.222185, 1, 0, 0.491071,-0.00436942)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold6::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
