// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold9
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:17 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 36900
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold9Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold9Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold9Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold9Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold9Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold9Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold9Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold9Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold9Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold9Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold9Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold9Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold9Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold9Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold9Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453611,-0.00927776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808714,0.0617427) , 
1, 3.70524, 1, 0, 0.70769,0.20769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401775,-0.019645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0746851,-0.085063) , 
5, 14.9989, 1, 0, 0.306318,-0.193682) , 
2, 0.0314797, 1, 0, 0.487228,-0.0127723)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761474,0.0480112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381782,-0.0273579) , 
5, 13.6625, 1, 0, 0.697145,0.175691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423741,-0.0132928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121866,-0.0692318) , 
5, 11.5386, 1, 0, 0.299793,-0.180521) , 
2, 0.0314577, 1, 0, 0.481831,-0.017331)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743976,0.0420211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366051,-0.0252183) , 
5, 14.8008, 1, 0, 0.682785,0.154321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402334,-0.0162581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102006,-0.0670565) , 
5, 11.5378, 1, 0, 0.280787,-0.18132) , 
2, 0.0406853, 1, 0, 0.493797,-0.0034715)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662202,0.0265927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184186,-0.0534955) , 
5, 19.0203, 1, 0, 0.601391,0.0811395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291647,-0.0357638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0381986,-0.0745309) , 
5, 13.7862, 1, 0, 0.19879,-0.243109) , 
2, 0.0666522, 1, 0, 0.47929,-0.0171985)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792516,0.0443407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280445,-0.0384024) , 
5, 17.0818, 1, 0, 0.72779,0.164714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47754,-0.00292797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161555,-0.0503379) , 
5, 10.1778, 1, 0, 0.346308,-0.107522) , 
2, 0.0259203, 1, 0, 0.503478,0.00463866)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665577,0.0245423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246002,-0.0382728) , 
2, 0.0962754, 1, 0, 0.600765,0.0720793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399152,-0.0119732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108923,-0.0559252) , 
2, 0.0150176, 1, 0, 0.158487,-0.22275) , 
5, 16.1524, 1, 0, 0.512562,0.0132817)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443787,-0.0178882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73316,0.0337304) , 
1, 3.77665, 1, 0, 0.646991,0.0875371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359959,-0.0205643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0813446,-0.0567301) , 
5, 11.5378, 1, 0, 0.246331,-0.16247) , 
2, 0.0499564, 1, 0, 0.489348,-0.0108301)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447624,-0.0145727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754929,0.0356944) , 
1, 3.86762, 1, 0, 0.657426,0.0930454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440596,-0.0031026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16651,-0.0431611) , 
5, 5.08977, 1, 0, 0.240499,-0.146056) , 
2, 0.0536731, 1, 0, 0.504996,0.00562931)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777383,0.0356357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467144,-0.0252879) , 
3, 0.339389, 1, 0, 0.733691,0.126141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269275,-0.0310714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482171,0.00800968) , 
1, 4.86271, 1, 0, 0.327824,-0.0944647) , 
2, 0.0277536, 1, 0, 0.504414,0.0015195)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680474,0.0253127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380232,-0.0325977) , 
3, 0.345605, 1, 0, 0.638173,0.0807027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347205,-0.0186989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102654,-0.0701295) , 
4, 0.599331, 1, 0, 0.321234,-0.109733) , 
5, 8.32189, 1, 0, 0.495073,-0.00528006)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254124,-0.0469577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742699,0.0277962) , 
4, 0.0439358, 1, 0, 0.700596,0.0980155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232127,-0.0316942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426288,0.00579697) , 
0, 1483.73, 1, 0, 0.282135,-0.0993529) , 
2, 0.0388866, 1, 0, 0.498595,0.0027408)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481969,-0.0065756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738186,0.0359353) , 
0, 1120.95, 1, 0, 0.627647,0.0805475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126912,-0.0462498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396199,-0.000507851) , 
0, 1914.26, 1, 0, 0.168212,-0.162377) , 
5, 15.454, 1, 0, 0.509949,0.018315)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763866,0.0273815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381291,-0.0401657) , 
3, 0.364113, 1, 0, 0.723099,0.0882668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503744,-2.18664e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239522,-0.0298487) , 
5, 5.59271, 1, 0, 0.332897,-0.0841672) , 
2, 0.0259244, 1, 0, 0.489262,-0.0150678)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678898,0.0158871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145127,-0.0496677) , 
5, 21.2506, 1, 0, 0.622286,0.0408419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298879,-0.0119602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173393,-0.0383879) , 
3, 0.148048, 1, 0, 0.225331,-0.117785) , 
2, 0.057364, 1, 0, 0.475557,-0.0177923)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585937,-0.00228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246387,-0.030238) , 
2, 0.0203692, 1, 0, 0.355475,-0.0924677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770494,0.0375677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388301,-0.0103633) , 
5, 8.34638, 1, 0, 0.600837,0.0733863) , 
1, 4.11138, 1, 0, 0.494795,0.00170672)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192293,-0.037753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641975,0.0135298) , 
4, 0.0668714, 1, 0, 0.588304,0.0345913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196247,-0.0256036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132516,-0.0536072) , 
4, 0.925051, 1, 0, 0.180182,-0.138088) , 
2, 0.0869874, 1, 0, 0.508426,0.0007941)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819468,0.0302843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444794,-0.00494833) , 
2, 0.0259203, 1, 0, 0.610406,0.0431005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103649,-0.0462781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376114,-0.000578342) , 
0, 1718.68, 1, 0, 0.152689,-0.140121) , 
5, 14.2653, 1, 0, 0.49718,-0.00222348)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687403,0.0167597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230652,-0.0216467) , 
2, 0.0610763, 1, 0, 0.542775,0.0209018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328892,-0.0259862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266611,-0.0552587) , 
4, 0.837313, 1, 0, 0.310507,-0.15372) , 
3, 0.290123, 1, 0, 0.486874,-0.0211252)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711395,0.0231907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450026,-0.019332) , 
4, 0.998532, 1, 0, 0.652004,0.0579482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283681,-0.0250061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60513,0.0269077) , 
0, 2298.91, 1, 0, 0.31787,-0.0778022) , 
5, 8.32169, 1, 0, 0.497969,-0.00463244)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69421,0.0121727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328783,-0.015624) , 
2, 0.0185174, 1, 0, 0.437035,-0.030336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.920131,0.0520899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45331,0.00526227) , 
2, 0.0333261, 1, 0, 0.690796,0.115032) , 
1, 5.08556, 1, 0, 0.498099,0.00464461)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199604,-0.0457478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394119,-0.0126039) , 
1, 2.66878, 1, 0, 0.371731,-0.0689758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65636,0.0220901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336723,-0.0355764) , 
4, 1.10485, 1, 0, 0.625842,0.0659394) , 
1, 4.35476, 1, 0, 0.494456,-0.00381759)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65854,0.0206501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165488,-0.0274729) , 
5, 19.2856, 1, 0, 0.586683,0.0600151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397314,-0.0181728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787631,0.0331517) , 
0, 2466.94, 1, 0, 0.42325,-0.0618256) , 
3, 0.154315, 1, 0, 0.498639,-0.00562208)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451259,-0.0096402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704089,0.022398) , 
1, 3.73352, 1, 0, 0.634208,0.0552167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281074,-0.0124851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0829703,-0.0427913) , 
5, 23.6828, 1, 0, 0.193725,-0.0883058) , 
5, 13.845, 1, 0, 0.519053,0.0176957)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417354,-0.00878445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683021,0.0179373) , 
1, 3.86802, 1, 0, 0.593426,0.0352959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339362,-0.00813126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0668398,-0.043421) , 
5, 8.8267, 1, 0, 0.18725,-0.0921685) , 
2, 0.0870181, 1, 0, 0.512775,0.00998657)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453458,-0.00401313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292269,-0.0340406) , 
4, 1.0208, 1, 0, 0.429263,-0.0359775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739459,0.022442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282651,-0.013565) , 
2, 0.0777609, 1, 0, 0.662101,0.0638109) , 
0, 1482.44, 1, 0, 0.509138,-0.00174516)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696995,0.0164462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402949,-0.0246431) , 
3, 0.314799, 1, 0, 0.642804,0.0348538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298887,-0.00976956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303069,-0.0341266) , 
4, 0.376552, 1, 0, 0.299899,-0.0602122) , 
5, 9.23043, 1, 0, 0.503283,-0.00382645)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632848,0.00978733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185384,-0.0236804) , 
5, 14.2669, 1, 0, 0.521166,0.00995373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153612,-0.0516427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3742,-0.0186006) , 
0, 1008.21, 1, 0, 0.262389,-0.148069) , 
3, 0.370361, 1, 0, 0.490633,-0.00869176)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815433,0.0288506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503125,-0.0118374) , 
3, 0.339417, 1, 0, 0.769775,0.0851792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367698,-0.0043873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268884,-0.0333419) , 
4, 1.0212, 1, 0, 0.350854,-0.0388526) , 
2, 0.0222054, 1, 0, 0.504348,0.00659317)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108819,-0.038948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332543,-0.00959526) , 
1, 4.80997, 1, 0, 0.163261,-0.101424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603633,0.00909781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276706,-0.0349869) , 
4, 1.10179, 1, 0, 0.567191,0.0165366) , 
4, 0.111235, 1, 0, 0.494176,-0.0047862)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129876,-0.0383271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644084,0.013902) , 
4, 0.044521, 1, 0, 0.574361,0.0305963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675284,0.00388422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269782,-0.02514) , 
2, 0.0222209, 1, 0, 0.405097,-0.0608475) , 
3, 0.16049, 1, 0, 0.486323,-0.0169656)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664882,0.00432509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906998,0.0398841) , 
1, 4.74582, 1, 0, 0.755007,0.0593593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337543,-0.00640331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302994,-0.0298518) , 
4, 0.910276, 1, 0, 0.328715,-0.0514852) , 
2, 0.0240604, 1, 0, 0.48466,-0.0109364)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616035,0.00989482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136237,-0.0357308) , 
2, 0.114808, 1, 0, 0.570629,0.023549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17942,-0.0413077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0579502,-0.0365024) , 
2, 0.026281, 1, 0, 0.091494,-0.114277) , 
5, 21.3985, 1, 0, 0.504765,0.00460278)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743393,0.0250687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333225,-0.0297559) , 
3, 0.351727, 1, 0, 0.687911,0.0673408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396379,-0.00361987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197865,-0.0566029) , 
4, 0.70954, 1, 0, 0.37126,-0.0390231) , 
5, 5.59271, 1, 0, 0.495323,0.00264994)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452541,-0.0011712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6958,0.0246783) , 
1, 4.13704, 1, 0, 0.604822,0.0542787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64534,0.0091392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337435,-0.0181063) , 
5, 5.00744, 1, 0, 0.442231,-0.0310752) , 
3, 0.111105, 1, 0, 0.498131,-0.00172962)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553143,-0.00354309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.859753,0.0314395) , 
1, 3.70609, 1, 0, 0.770195,0.0696773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385575,-0.00334744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272212,-0.0263964) , 
4, 1.02119, 1, 0, 0.366806,-0.0286306) , 
2, 0.0203692, 1, 0, 0.503024,0.00456641)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226581,-0.0392646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0734052,-0.0285755) , 
2, 0.0323311, 1, 0, 0.119396,-0.0944479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383275,-0.0141166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592368,0.00855212) , 
0, 869.164, 1, 0, 0.556549,0.0171928) , 
4, 0.0220096, 1, 0, 0.507849,0.00475581)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604934,0.0110858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701287,-0.0386222) , 
5, 23.9058, 1, 0, 0.539342,0.0253603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.00237809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243498,-0.0394944) , 
3, 0.110126, 1, 0, 0.307508,-0.112243) , 
4, 1.04315, 1, 0, 0.512276,0.00929555)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647345,0.0128853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228098,-0.0142986) , 
2, 0.0851802, 1, 0, 0.562049,0.0277806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561118,0.0023867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253433,-0.0271361) , 
5, 6.01116, 1, 0, 0.362026,-0.0585406) , 
3, 0.265435, 1, 0, 0.504453,0.00292466)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629335,0.0070617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133705,-0.0242796) , 
5, 17.0774, 1, 0, 0.517921,0.00590275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27516,-0.0368886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550181,0.00152189) , 
1, 4.73335, 1, 0, 0.359544,-0.0977385) , 
4, 0.976845, 1, 0, 0.492459,-0.0107595)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754316,0.0217276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5321,-0.00876469) , 
4, 0.89104, 1, 0, 0.664374,0.034909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341011,-0.00343701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3081,-0.0416587) , 
4, 0.487899, 1, 0, 0.335628,-0.0351398) , 
5, 8.07674, 1, 0, 0.511735,0.00238479)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187249,-0.0514799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330598,-0.0163861) , 
1, 2.43362, 1, 0, 0.297456,-0.0955029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555018,0.00803943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335136,-0.0206363) , 
3, 0.357926, 1, 0, 0.530005,0.016234) , 
1, 3.21133, 1, 0, 0.496641,0.000203037)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308252,-0.0070895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406978,-0.0244277) , 
4, 0.644115, 1, 0, 0.3537,-0.0578342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723898,0.0167643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327602,-0.0113287) , 
5, 10.0665, 1, 0, 0.581108,0.0255791) , 
0, 996.63, 1, 0, 0.50361,-0.00284722)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608552,0.0063684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977904,0.0708022) , 
1, 4.74678, 1, 0, 0.730928,0.0938026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477266,-0.00222785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232205,-0.0383828) , 
4, 0.909981, 1, 0, 0.451935,-0.022197) , 
5, 2.37989, 1, 0, 0.497024,-0.00344991)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793386,-0.00039588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813547,0.0434174) , 
5, 4.76212, 1, 0, 0.804809,0.0929325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572156,0.00178103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144683,-0.0256165) , 
5, 14.2475, 1, 0, 0.465346,-0.0133674) , 
2, 0.0074058, 1, 0, 0.500925,-0.00222612)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502052,-0.00209878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.07407,-0.0309774) , 
5, 20.2089, 1, 0, 0.429054,-0.0189384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702519,0.0193608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464875,-0.016736) , 
4, 0.997318, 1, 0, 0.660338,0.041615) , 
1, 4.92318, 1, 0, 0.493677,-0.00201911)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634008,-0.000175046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877505,0.0285601) , 
4, 0.552943, 1, 0, 0.759597,0.0437584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333835,-0.0110749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557977,0.00934269) , 
0, 1662.84, 1, 0, 0.383482,-0.0233082) , 
2, 0.0185024, 1, 0, 0.496612,-0.00313551)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328044,-0.0186997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597354,0.0105793) , 
1, 3.26658, 1, 0, 0.56078,0.0217474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490751,-0.023393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233668,-0.0022978) , 
2, 0.0388445, 1, 0, 0.368347,-0.0532792) , 
3, 0.259255, 1, 0, 0.505006,1.83643e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772674,0.00312346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529132,0.0239174) , 
2, 0.0425833, 1, 0, 0.691159,0.0424157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311443,-0.00252273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284783,-0.031822) , 
4, 0.487955, 1, 0, 0.306673,-0.0271196) , 
5, 8.07674, 1, 0, 0.502669,0.00832676)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340648,-0.0221521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589238,0.0029739) , 
0, 832.49, 1, 0, 0.559817,-0.000457935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251528,-0.00407061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41506,-0.0182984) , 
4, 0.377198, 1, 0, 0.360898,-0.0535898) , 
3, 0.23454, 1, 0, 0.490538,-0.0189626)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143614,-0.0203476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570295,0.0153724) , 
4, 0.0418364, 1, 0, 0.472254,0.0320953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639918,-0.00206629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29686,-0.0410954) , 
5, 4.93296, 1, 0, 0.545206,-0.0440135) , 
4, 0.688377, 1, 0, 0.503016,1.61135e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263436,-0.0332983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467811,0.000353875) , 
0, 814.607, 1, 0, 0.439047,-0.0157838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767288,0.0194398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793135,0.0738441) , 
3, 0.206493, 1, 0, 0.773096,0.102532) , 
1, 5.24786, 1, 0, 0.504579,0.00742679)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313161,-0.0273313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61125,0.00885371) , 
1, 2.96911, 1, 0, 0.589343,0.0205981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399465,-0.00691032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528536,-0.0340438) , 
1, 5.33436, 1, 0, 0.421151,-0.040955) , 
3, 0.148135, 1, 0, 0.496944,-0.0132169)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700148,0.0170212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415277,-0.00470309) , 
5, 2.27496, 1, 0, 0.45513,-0.00500074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825658,0.0488978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691858,8.35381e-05) , 
0, 2187.27, 1, 0, 0.751777,0.0711085) , 
1, 5.26024, 1, 0, 0.514427,0.0102129)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624874,0.0098397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111219,-0.0231229) , 
5, 20.2105, 1, 0, 0.517806,0.0170293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798548,0.00450832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399051,-0.0207448) , 
2, 0.014801, 1, 0, 0.482078,-0.0606343) , 
4, 0.888063, 1, 0, 0.509337,-0.00138134)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514377,0.00733054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58716,-0.00850855) , 
4, 0.776177, 1, 0, 0.539051,0.00586622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130831,-0.0306118) , 
2, 0.120363, 1, 0, 0.502308,-0.00319515)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26285,-0.0246397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606509,0.0059485) , 
1, 2.70927, 1, 0, 0.581859,0.0129787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148084,-0.00333513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190962,-0.0262163) , 
1, 3.97848, 1, 0, 0.174189,-0.0593303) , 
2, 0.0869377, 1, 0, 0.494899,-0.00244549)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343121,-0.00617551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380406,-0.0223631) , 
4, 0.732757, 1, 0, 0.35698,-0.0464607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683638,0.0114327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192002,-0.0211333) , 
2, 0.0999783, 1, 0, 0.606829,0.0206355) , 
1, 4.14698, 1, 0, 0.49435,-0.00957025)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567519,0.0203929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674109,-0.00133099) , 
1, 4.76597, 1, 0, 0.612263,0.04065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394245,-0.0017808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541384,-0.0238491) , 
0, 1658.89, 1, 0, 0.433255,-0.0268508) , 
3, 0.148136, 1, 0, 0.514726,0.00387032)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538051,0.00464916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971207,0.0724846) , 
1, 4.42961, 1, 0, 0.701731,0.0984686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504452,0.000676055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357204,-0.0207316) , 
4, 0.909981, 1, 0, 0.481683,-0.00950071) , 
5, 1.18938, 1, 0, 0.499757,-0.000632261)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645028,-0.0222699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691563,0.0142411) , 
3, 0.0308856, 1, 0, 0.686606,0.0384829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416676,-0.00114819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382059,-0.0290128) , 
4, 0.665771, 1, 0, 0.410221,-0.0208892) , 
5, 4.61649, 1, 0, 0.504396,-0.000658909)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314118,-0.00846819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689803,0.0202499) , 
4, 0.352878, 1, 0, 0.48996,0.0215518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615967,-8.33367e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348155,-0.0312406) , 
3, 0.265063, 1, 0, 0.542595,-0.0337126) , 
4, 0.773601, 1, 0, 0.507972,0.00263934)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748465,0.0130475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393449,-0.0151064) , 
3, 0.314719, 1, 0, 0.687868,0.0252388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398105,-0.00392048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16584,-0.0410061) , 
4, 0.710242, 1, 0, 0.374957,-0.0234422) , 
5, 5.94446, 1, 0, 0.504574,-0.00327704)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793469,0.0179997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353594,-0.0108797) , 
2, 0.0610763, 1, 0, 0.677042,0.0318187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225279,-0.00432905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406517,-0.0169711) , 
4, 0.176768, 1, 0, 0.336512,-0.0424429) , 
5, 7.12417, 1, 0, 0.498573,-0.00710124)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210111,-0.0500414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374399,-0.00855426) , 
0, 775.013, 1, 0, 0.330491,-0.0702479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624416,0.00581962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166223,-0.0182028) , 
2, 0.087032, 1, 0, 0.530561,0.00511618) , 
0, 869.181, 1, 0, 0.493508,-0.0088414)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438623,0.00457507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754934,0.0531134) , 
0, 1911.19, 1, 0, 0.454084,0.0246745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562145,-0.0155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867569,0.0466188) , 
0, 3064.91, 1, 0, 0.592207,-0.03222) , 
1, 4.72026, 1, 0, 0.505466,0.00350962)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867353,0.0271059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506439,8.84345e-06) , 
2, 0.00925872, 1, 0, 0.556731,0.0106323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233564,0.00985836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394308,-0.0197478) , 
4, 0.198224, 1, 0, 0.360098,-0.0542842) , 
3, 0.265427, 1, 0, 0.502876,-0.00714729)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299505,-0.0190999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443099,0.00227543) , 
0, 1098.91, 1, 0, 0.344124,-0.0437065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660192,0.00518938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181559,-0.0173972) , 
2, 0.0980591, 1, 0, 0.574671,0.00416638) , 
1, 4.01872, 1, 0, 0.485498,-0.0143503)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735192,0.00317133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.890907,0.0517292) , 
2, 0.0135684, 1, 0, 0.757412,0.0303522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536834,-0.0133923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282219,-0.00259645) , 
2, 0.0429699, 1, 0, 0.380645,-0.0244433) , 
2, 0.0166526, 1, 0, 0.486109,-0.00910498)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76881,0.012781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649796,0.0396492) , 
3, 0.222332, 1, 0, 0.733667,0.074601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487711,0.00376983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360073,-0.029901) , 
4, 0.799298, 1, 0, 0.463146,-0.00864294) , 
5, 2.27687, 1, 0, 0.506378,0.0046604)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535476,0.0244952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591265,0.000606043) , 
4, 0.355173, 1, 0, 0.578598,0.0215712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0930631,-0.0312181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106031,-0.0153053) , 
5, 24.9124, 1, 0, 0.101306,-0.0486506) , 
5, 20.2091, 1, 0, 0.508722,0.0112906)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907571,0.0477204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650251,0.00421979) , 
3, 0.0493284, 1, 0, 0.686897,0.033857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409778,0.000416277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270668,-0.0323815) , 
4, 0.641324, 1, 0, 0.387448,-0.0148579) , 
5, 5.69237, 1, 0, 0.504292,0.0041505)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822384,0.0327589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616602,-0.0110371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291679,0.00412538) , 
2, 0.0452207, 1, 0, 0.478359,-0.0163653) , 
2, 0.00370159, 1, 0, 0.489645,-0.0125136)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625301,0.0155956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578677,-0.00213777) , 
4, 0.666094, 1, 0, 0.600477,0.0229811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215628,-0.0063657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0707411,-0.0329304) , 
5, 23.5579, 1, 0, 0.128921,-0.0495988) , 
5, 17.0638, 1, 0, 0.50571,0.00839498)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699954,0.00222423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569466,0.0188246) , 
3, 0.234498, 1, 0, 0.661385,0.0275426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293068,-0.0012603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362883,-0.026077) , 
4, 0.333342, 1, 0, 0.318799,-0.036089) , 
5, 8.07653, 1, 0, 0.498832,-0.00264975)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708443,0.0130637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215185,-0.0189586) , 
2, 0.111087, 1, 0, 0.666001,0.0352476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23522,0.00471185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31177,-0.0122362) , 
1, 4.04762, 1, 0, 0.282171,-0.0186601) , 
5, 9.51041, 1, 0, 0.504429,0.0125553)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609548,0.00597552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524549,-0.0119179) , 
3, 0.0779729, 1, 0, 0.560267,-0.0147712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535279,0.020495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328421,-0.0059756) , 
3, 0.359023, 1, 0, 0.474371,0.0420984) , 
3, 0.191366, 1, 0, 0.525367,0.00833542)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457772,-0.00352718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447632,-0.0380443) , 
0, 2068.4, 1, 0, 0.457326,-0.0172339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839896,0.0491824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691999,-0.00457231) , 
0, 2799.18, 1, 0, 0.754248,0.053198) , 
0, 2298.97, 1, 0, 0.493659,-0.00861559)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493074,0.00198127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243592,-0.0244652) , 
3, 0.425851, 1, 0, 0.475725,0.000385092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863671,-0.0169051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776258,0.0456949) , 
2, 0.0164222, 1, 0, 0.805463,0.089576) , 
1, 5.71917, 1, 0, 0.51183,0.0101513)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553655,0.0161692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658648,-0.00250478) , 
1, 4.67952, 1, 0, 0.600951,0.0279731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388911,-0.00501773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50185,-0.0497063) , 
1, 5.65078, 1, 0, 0.400509,-0.0323756) , 
3, 0.191325, 1, 0, 0.510291,0.000677203)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613921,0.00991867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286272,-0.00535927) , 
5, 7.13297, 1, 0, 0.438093,0.00895624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83006,0.0100922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539557,-0.0127558) , 
5, 2.77742, 1, 0, 0.600048,-0.0268454) , 
1, 4.69062, 1, 0, 0.497802,-0.00424295)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510967,-0.00920112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411623,0.00688901) , 
3, 0.203704, 1, 0, 0.472526,-0.0100921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687086,0.00839876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.921942,0.0565067) , 
4, 0.685555, 1, 0, 0.783302,0.0709357) , 
0, 2229.26, 1, 0, 0.51254,0.00034078)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567683,-0.00388404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502991,0.0137549) , 
3, 0.144006, 1, 0, 0.534056,0.0184979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269918,-0.0433011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13312,-0.00960982) , 
2, 0.0331268, 1, 0, 0.201981,-0.107435) , 
3, 0.432009, 1, 0, 0.51363,0.0107518)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386164,-0.00471506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576567,0.0505126) , 
1, 4.14953, 1, 0, 0.399412,-0.00390327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578865,-0.0100157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280784,-0.0361143) , 
3, 0.369656, 1, 0, 0.554465,-0.0397871) , 
1, 4.2612, 1, 0, 0.482635,-0.0231635)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56322,-0.00264281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457538,-0.0252946) , 
3, 0.158251, 1, 0, 0.546558,-0.0207305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43403,0.0108124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54577,-0.01879) , 
0, 2093.69, 1, 0, 0.447914,0.0240748) , 
3, 0.191337, 1, 0, 0.506186,-0.00239302)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461742,-0.000652189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587057,-0.0216338) , 
0, 1943.28, 1, 0, 0.476566,-0.0100552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591861,-0.00188127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887044,0.0526064) , 
1, 5.78895, 1, 0, 0.766896,0.0733245) , 
0, 2540.38, 1, 0, 0.503272,-0.00238562)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173548,-0.0328016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465809,0.00618196) , 
1, 2.65002, 1, 0, 0.449457,0.0134519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824663,0.00502143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379843,-0.0170087) , 
2, 0.0240688, 1, 0, 0.549945,-0.0343817) , 
4, 0.663356, 1, 0, 0.493668,-0.00759318)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609426,-0.0111426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271391,0.00305953) , 
2, 0.0462936, 1, 0, 0.468424,-0.0187166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900988,0.0688595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75807,-0.00279202) , 
1, 6.28637, 1, 0, 0.825657,0.0797987) , 
0, 2557.96, 1, 0, 0.497957,-0.0105723)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442583,0.00154624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546387,-0.0115446) , 
0, 1354.33, 1, 0, 0.481597,-0.0111573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833057,0.0661482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797793,-0.00311629) , 
4, 0.48855, 1, 0, 0.810295,0.0733722) , 
0, 2564.02, 1, 0, 0.509474,-0.00398824)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342521,-0.0136496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591798,0.00591615) , 
0, 988.602, 1, 0, 0.514445,-0.000870042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192923,-0.0563279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250198,0.00694211) , 
5, 7.73653, 1, 0, 0.218139,-0.123543) , 
3, 0.425914, 1, 0, 0.493089,-0.00971154)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500944,0.00246349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446159,-0.0140397) , 
4, 0.930837, 1, 0, 0.489558,-0.0031121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623249,-0.0398147) , 
1, 6.54702, 1, 0, 0.495005,-0.00782004)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435941,-0.00193486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584357,-0.0251385) , 
1, 5.26803, 1, 0, 0.458742,-0.0177653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837808,-0.0161895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753969,0.0336908) , 
2, 0.0128642, 1, 0, 0.784021,0.055601) , 
0, 2418.06, 1, 0, 0.492816,-0.0100802)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167694,-0.0354863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366189,-0.00486338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629703,0.0087594) , 
4, 0.48818, 1, 0, 0.513021,0.0098427) , 
1, 2.4733, 1, 0, 0.500135,0.0050854)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539785,-0.00312095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436542,-0.0270046) , 
3, 0.231313, 1, 0, 0.52615,-0.0209538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345206,0.00692658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722785,0.0557627) , 
1, 4.85157, 1, 0, 0.405925,0.0546007) , 
3, 0.283919, 1, 0, 0.499577,-0.00425411)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47211,0.0085097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410157,-0.00583957) , 
4, 0.909578, 1, 0, 0.45844,0.0179054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855135,0.00536762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46483,-0.0223212) , 
2, 0.0203532, 1, 0, 0.6089,-0.0465728) , 
1, 4.82619, 1, 0, 0.509487,-0.00397025)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277061,-0.00403501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372025,-0.0233641) , 
4, 0.596752, 1, 0, 0.32254,-0.0494161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651905,0.00888714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47834,-0.00678416) , 
3, 0.166696, 1, 0, 0.567944,0.00284218) , 
0, 997.399, 1, 0, 0.484454,-0.0149369)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637797,-0.000487762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319123,0.017648) , 
2, 0.0528206, 1, 0, 0.539159,0.0159208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100992,-0.0286106) , 
2, 0.125854, 1, 0, 0.509631,0.0098849)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771379,0.00471824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681593,0.0341944) , 
3, 0.27156, 1, 0, 0.750972,0.0419444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311951,0.000264457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42277,-0.0219885) , 
1, 5.38529, 1, 0, 0.331258,-0.0136276) , 
2, 0.0277762, 1, 0, 0.502711,0.00907344)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769076,0.00310452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953555,0.0586438) , 
2, 0.0053035, 1, 0, 0.824923,0.0597088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615363,-0.00991543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30208,0.00303725) , 
2, 0.0443785, 1, 0, 0.464551,-0.0128476) , 
2, 0.00740698, 1, 0, 0.501921,-0.00532354)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487754,0.00524163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466288,-0.0114286) , 
4, 0.886564, 1, 0, 0.482772,0.00441055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719056,-0.00497339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533814,-0.0445755) , 
3, 0.138376, 1, 0, 0.626743,-0.0774802) , 
1, 6.03567, 1, 0, 0.496222,-0.0032396)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525563,9.97632e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522154,0.0524882) , 
3, 0.319981, 1, 0, 0.525355,0.0109423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274166,0.00534761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302241,-0.0370371) , 
1, 3.94121, 1, 0, 0.2875,-0.0568732) , 
3, 0.370295, 1, 0, 0.49703,0.00286639)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691808,0.00677542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.842029,0.0511923) , 
5, 3.34716, 1, 0, 0.729255,0.0613209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472101,-0.000977501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307828,-0.0175396) , 
3, 0.166681, 1, 0, 0.384986,-0.0319726) , 
5, 4.75658, 1, 0, 0.495184,-0.0021101)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384995,-0.0193243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404653,0.000145397) , 
3, 0.0864799, 1, 0, 0.398579,-0.0189252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892768,0.0280977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430594,-0.00202454) , 
2, 0.0240537, 1, 0, 0.610901,0.0242937) , 
4, 0.59815, 1, 0, 0.499124,0.00154115)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672769,0.00552406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1.04762,0.094878) , 
1, 5.71933, 1, 0, 0.718948,0.0421018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427727,-0.003878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571356,-0.0419377) , 
1, 6.22235, 1, 0, 0.436895,-0.0199421) , 
5, 3.56858, 1, 0, 0.508101,-0.00427872)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305172,-0.023854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461569,-0.00164526) , 
0, 806.873, 1, 0, 0.44307,-0.0148426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656095,0.0337398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733701,-0.0049264) , 
4, 0.442191, 1, 0, 0.708574,0.0272422) , 
1, 5.15153, 1, 0, 0.505113,-0.00500824)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497595,0.00438559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686055,-0.0265644) , 
1, 5.95962, 1, 0, 0.517038,0.00492414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501933,-0.0228565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307181,0.0096292) , 
4, 1.16408, 1, 0, 0.452606,-0.0537566) , 
4, 0.909477, 1, 0, 0.502556,-0.00826515)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204645,-0.0279944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582245,0.00767527) , 
1, 2.63632, 1, 0, 0.564997,0.0194411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580905,0.00481873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184158,-0.0229226) , 
2, 0.0296838, 1, 0, 0.346667,-0.0344594) , 
3, 0.290065, 1, 0, 0.512718,0.00653472)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724805,-0.00187023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545868,0.0186331) , 
2, 0.0248023, 1, 0, 0.657334,0.0234185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217093,-0.0188096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183625,0.0128085) , 
3, 0.308408, 1, 0, 0.210554,-0.0428371) , 
2, 0.0574041, 1, 0, 0.499862,6.60952e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446704,-0.000825687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514724,-0.030666) , 
0, 1886.15, 1, 0, 0.450598,-0.00844777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781783,0.04128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69418,-0.0145173) , 
0, 2856.63, 1, 0, 0.740293,0.0449505) , 
0, 2064.89, 1, 0, 0.493933,-0.000459987)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44655,-0.00411967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55457,-0.0351739) , 
0, 2048.81, 1, 0, 0.456048,-0.0210907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726114,-0.00768543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901321,0.0742546) , 
3, 0.129005, 1, 0, 0.792852,0.0567373) , 
0, 2564.13, 1, 0, 0.48266,-0.0149413)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468734,-0.00309317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604566,-0.0404868) , 
0, 2616.23, 1, 0, 0.473854,-0.0141071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51489,-0.0437341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789482,0.00505262) , 
0, 2872.52, 1, 0, 0.637892,-0.0704685) , 
1, 6.05986, 1, 0, 0.488398,-0.0191044)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636208,-0.0112819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836553,0.0449519) , 
5, 0.409359, 1, 0, 0.750359,0.0670634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439062,0.00460061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537985,-0.0128866) , 
4, 0.644132, 1, 0, 0.478575,-0.00815772) , 
5, 1.14081, 1, 0, 0.499571,-0.00234689)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427394,-0.00131465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49779,-0.0214939) , 
0, 1717.66, 1, 0, 0.435708,-0.0123625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713411,0.00638474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776428,0.0548804) , 
3, 0.257188, 1, 0, 0.721836,0.0422462) , 
1, 5.10548, 1, 0, 0.502782,0.000438905)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786689,0.0228078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44268,-0.00427932) , 
2, 0.00555523, 1, 0, 0.46754,-0.00781692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888181,0.0665647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.83229,0.019006) , 
0, 2807.37, 1, 0, 0.860844,0.124807) , 
1, 5.81667, 1, 0, 0.503288,0.00423758)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467946,-0.00217068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732793,0.0122303) , 
4, 0.806372, 1, 0, 0.512328,0.00104373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482329,0.00671005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32641,-0.021865) , 
3, 0.0805972, 1, 0, 0.368666,-0.0477458) , 
4, 0.998778, 1, 0, 0.491883,-0.00589966)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701895,-0.00657613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354982,0.00865466) , 
2, 0.0333143, 1, 0, 0.523185,0.00506179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264123,-0.0463921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220992,-0.0117155) , 
5, 7.27437, 1, 0, 0.241059,-0.109606) , 
3, 0.413495, 1, 0, 0.502302,-0.00342625)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551908,0.00439359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323559,-0.0128026) , 
4, 1.04274, 1, 0, 0.523408,0.00713589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161258,-0.0297308) , 
3, 0.444365, 1, 0, 0.504629,0.00166966)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458317,0.00292157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743819,0.0394174) , 
1, 5.13619, 1, 0, 0.488725,0.0210357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83724,0.00244569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444313,-0.0175808) , 
2, 0.0277107, 1, 0, 0.649407,-0.0293023) , 
0, 1941.47, 1, 0, 0.521531,0.0107582)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230156,-0.0347055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563361,0.00102269) , 
1, 2.7269, 1, 0, 0.547697,-0.00229461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338677,-0.0288971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31911,0.00393666) , 
3, 0.379344, 1, 0, 0.330276,-0.0530439) , 
3, 0.296288, 1, 0, 0.495747,-0.0144205)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355945,0.00133724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46791,0.0446028) , 
0, 917.606, 1, 0, 0.38323,0.0343781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54293,-0.0105368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439122,0.0140903) , 
3, 0.407339, 1, 0, 0.537214,-0.0292436) , 
0, 988.31, 1, 0, 0.491792,-0.0104763)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67553,0.0102955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301683,-0.00147897) , 
5, 10.0138, 1, 0, 0.537283,0.0202062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142994,-0.0320729) , 
3, 0.469119, 1, 0, 0.524359,0.0163773)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33866,-0.0044331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332031,-0.0381033) , 
1, 4.47799, 1, 0, 0.337493,-0.0343731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625426,0.00726607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268888,-0.0310232) , 
3, 0.345673, 1, 0, 0.578557,0.00541017) , 
0, 1107.46, 1, 0, 0.472589,-0.0120779)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537637,8.58417e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819117,0.0245329) , 
1, 4.26144, 1, 0, 0.686276,0.0373586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346847,0.000863785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392293,-0.0215936) , 
4, 0.466237, 1, 0, 0.362742,-0.0234646) , 
5, 5.94425, 1, 0, 0.494967,0.00139332)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752503,-0.0200983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591234,0.0140497) , 
2, 0.0111087, 1, 0, 0.627231,0.0266718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17667,-0.0172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185003,0.0247029) , 
3, 0.376411, 1, 0, 0.177665,-0.0352014) , 
5, 13.8452, 1, 0, 0.510674,0.0106302)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813066,0.0262073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319051,-0.000841715) , 
5, 10.107, 1, 0, 0.623679,0.0465256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487312,-0.00579896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406594,0.0159103) , 
4, 1.02122, 1, 0, 0.477337,-0.0105904) , 
3, 0.0555588, 1, 0, 0.504433,-1.52414e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481941,-0.0179547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200332,-0.00246984) , 
2, 0.0388595, 1, 0, 0.327147,-0.035349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633058,0.00975047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371188,-0.0113803) , 
3, 0.308596, 1, 0, 0.587685,0.0179456) , 
0, 988.303, 1, 0, 0.499487,-9.57221e-05)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold9::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
