// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CrossValidation::BDT_NewCuts_NewQCD_NoRegSplits
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:20 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 43118
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
EncapsulatedMethodName: "BDT_NewCuts_NewQCD_NoRegSplits" []
EncapsulatedMethodTypeName: "BDT" []
NumFolds: "10" [Number of folds to generate]
OutputEnsembling: "None" [Combines output from contained methods. If None, no combination is performed. (default None)]
SplitExpr: "int([eventNumber])%int(10)" [The expression used to assign events to folds]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
inline double ReadBDT_NewCuts_NewQCD_NoRegSplits::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
