// Class: ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_NewCuts_NewQCD_NoRegSplits_fold8
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.38/04       [402948]
Creator        : b78499db
Date           : Fri Apr 10 16:02:16 2026
Host           : Darwin sat12-bq151-c9e4e291-cebf-421f-a4bb-9c6e9893d24e-B204E9FB7EFE.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jan 19 22:02:01 PST 2026; root:xnu-11417.140.69.708.3~1/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis-BU
Training events: 40813
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.009277344,10400.8095703]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.0002477169,8.57665538788]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [0,0.149991288781]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [1.51442191054e-05,0.499976217747]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.5981593132]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000655489217024,96.2869567871]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [127,1245521280]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_NewCuts_NewQCD_NoRegSplits_fold8Node

#ifndef BDT_NewCuts_NewQCD_NoRegSplits_fold8Node__def
#define BDT_NewCuts_NewQCD_NoRegSplits_fold8Node__def

class BDT_NewCuts_NewQCD_NoRegSplits_fold8Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node ( BDT_NewCuts_NewQCD_NoRegSplits_fold8Node* left,BDT_NewCuts_NewQCD_NoRegSplits_fold8Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_NewCuts_NewQCD_NoRegSplits_fold8Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node*   fLeft;     // pointer to the left daughter node
   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_NewCuts_NewQCD_NoRegSplits_fold8Node::~BDT_NewCuts_NewQCD_NoRegSplits_fold8Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold8Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_NewCuts_NewQCD_NoRegSplits_fold8Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8 : public IClassifierReader {

 public:

   // constructor
   ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_NewCuts_NewQCD_NoRegSplits_fold8Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_NewCuts_NewQCD_NoRegSplits_fold8Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_NewCuts_NewQCD_NoRegSplits_fold8Node*)current->GetRight();
         else current=(BDT_NewCuts_NewQCD_NoRegSplits_fold8Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488434,-0.0023131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810728,0.0621456) , 
1, 3.86762, 1, 0, 0.711205,0.211205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409702,-0.0180596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0813967,-0.0837207) , 
5, 15.0004, 1, 0, 0.313656,-0.186344) , 
2, 0.0314797, 1, 0, 0.493083,-0.00691723)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781903,0.0520967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429197,-0.0178402) , 
5, 12.2831, 1, 0, 0.711311,0.189957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42231,-0.0137382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100322,-0.0727112) , 
5, 13.846, 1, 0, 0.31472,-0.166439) , 
2, 0.0314577, 1, 0, 0.495349,-0.00411699)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.751723,0.0433471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359885,-0.026878) , 
5, 15.0221, 1, 0, 0.686613,0.156992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41275,-0.0142858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116465,-0.0650171) , 
5, 11.5378, 1, 0, 0.294684,-0.170005) , 
2, 0.040718, 1, 0, 0.503462,0.00418407)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692119,0.0305223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181082,-0.057541) , 
5, 19.0202, 1, 0, 0.629544,0.0972617) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311807,-0.030903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0345384,-0.0748566) , 
5, 17.4541, 1, 0, 0.239265,-0.206508) , 
2, 0.0518406, 1, 0, 0.482645,-0.0170758)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781196,0.0417096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22332,-0.0495643) , 
5, 18.1967, 1, 0, 0.720379,0.154049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45499,-0.00610207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16793,-0.0489754) , 
5, 10.1778, 1, 0, 0.334402,-0.115116) , 
2, 0.0277717, 1, 0, 0.500595,0.000780458)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677336,0.0265522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237479,-0.0416539) , 
2, 0.0925725, 1, 0, 0.604505,0.0737115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302203,-0.0308474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0546872,-0.0636436) , 
2, 0.0334848, 1, 0, 0.140044,-0.239306) , 
5, 16.1524, 1, 0, 0.511694,0.0111624)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430827,-0.019412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712274,0.0309233) , 
1, 3.77665, 1, 0, 0.633384,0.0799621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175812,-0.0477493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360308,-0.0103434) , 
0, 1441.43, 1, 0, 0.225217,-0.178042) , 
2, 0.0573753, 1, 0, 0.48989,-0.0107415)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504721,-0.012159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770739,0.0365121) , 
0, 988.301, 1, 0, 0.701148,0.112083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437758,-0.00445437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133715,-0.0463454) , 
5, 10.0673, 1, 0, 0.298703,-0.105414) , 
2, 0.0388671, 1, 0, 0.505801,0.00651013)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780415,0.0352989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473922,-0.0258432) , 
3, 0.320947, 1, 0, 0.733012,0.120074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459934,-0.00368569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140211,-0.0444016) , 
5, 11.5376, 1, 0, 0.33902,-0.0838611) , 
2, 0.0277622, 1, 0, 0.507501,0.00334688)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701854,0.0225127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271521,-0.0308447) , 
5, 14.2655, 1, 0, 0.614473,0.0553439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383428,-0.00975684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154514,-0.0426061) , 
5, 5.00929, 1, 0, 0.217929,-0.147955) , 
2, 0.0666085, 1, 0, 0.496534,-0.00512101)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547844,-0.0056597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.8011,0.0364853) , 
1, 4.19238, 1, 0, 0.698268,0.0867587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235247,-0.0305531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409153,0.00312383) , 
0, 1483.73, 1, 0, 0.281491,-0.0967876) , 
2, 0.0388866, 1, 0, 0.495619,-0.0024867)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494694,-0.00549724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753474,0.0376095) , 
0, 1269.33, 1, 0, 0.618035,0.0679228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256308,-0.0213954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0959176,-0.0502444) , 
5, 22.4412, 1, 0, 0.168904,-0.150719) , 
5, 15.454, 1, 0, 0.506594,0.0136719)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647412,0.0170777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323502,-0.0449399) , 
3, 0.376486, 1, 0, 0.608961,0.0440148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532562,0.00198366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171589,-0.0397212) , 
2, 0.0111105, 1, 0, 0.220007,-0.138544) , 
5, 11.8879, 1, 0, 0.492273,-0.010754)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666261,0.0175518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392728,-0.032424) , 
3, 0.314764, 1, 0, 0.612534,0.0334436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231344,-0.0234687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135156,-0.0553764) , 
4, 1.08758, 1, 0, 0.215817,-0.12459) , 
2, 0.0610649, 1, 0, 0.47773,-0.0202563)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438122,-0.0122194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713052,0.0281479) , 
1, 4.11138, 1, 0, 0.599122,0.0488701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197697,-0.0277539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141059,-0.0492645) , 
4, 0.97617, 1, 0, 0.184924,-0.13881) , 
2, 0.079625, 1, 0, 0.497041,0.00261553)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0476913,-0.0653802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19647,-0.033494) , 
4, -0.0718263, 1, 0, 0.137323,-0.174553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598452,0.013172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383648,-0.0278333) , 
4, 0.992208, 1, 0, 0.562093,0.02712) , 
4, 0.0662166, 1, 0, 0.506017,0.000495981)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857656,0.0399464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495778,-0.000162411) , 
2, 0.0240688, 1, 0, 0.649125,0.0708048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243844,-0.029633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575746,0.0213034) , 
1, 5.50109, 1, 0, 0.283421,-0.0926374) , 
5, 9.51041, 1, 0, 0.506214,0.00693436)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394008,-0.0158628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631591,0.0172294) , 
1, 4.02083, 1, 0, 0.55209,0.0245805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313813,-0.0219631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295132,-0.048231) , 
4, 0.61987, 1, 0, 0.304932,-0.154564) , 
3, 0.290121, 1, 0, 0.494031,-0.0175017)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709635,0.023881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437628,-0.0169519) , 
4, 0.998532, 1, 0, 0.648094,0.0636347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21311,-0.034873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443533,-0.00381473) , 
0, 1243.09, 1, 0, 0.314749,-0.0839135) , 
5, 8.32169, 1, 0, 0.497193,-0.00315842)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.821307,0.0347851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496207,-0.0164273) , 
3, 0.308534, 1, 0, 0.755814,0.0978635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242552,-0.0288775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438923,-0.00253677) , 
1, 3.78788, 1, 0, 0.379996,-0.0434642) , 
2, 0.0185174, 1, 0, 0.492257,-0.00124794)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476942,-0.0108458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204337,-0.034685) , 
5, 6.82587, 1, 0, 0.325205,-0.0967028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682788,0.0194495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215562,-0.023448) , 
2, 0.0758597, 1, 0, 0.573223,0.0404073) , 
0, 988.301, 1, 0, 0.493269,-0.0037935)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653105,0.0196565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174316,-0.0248323) , 
5, 19.2856, 1, 0, 0.58571,0.0590191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403286,-0.0167729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740572,0.0247617) , 
0, 2466.93, 1, 0, 0.427363,-0.0583585) , 
3, 0.154315, 1, 0, 0.501176,-0.00364306)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433011,-0.0220412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793076,0.0278196) , 
1, 3.26085, 1, 0, 0.736402,0.0787744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36386,6.06751e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243132,-0.0222969) , 
3, 0.179019, 1, 0, 0.304322,-0.0445979) , 
2, 0.0351586, 1, 0, 0.514321,0.0153634)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669653,0.0131375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235038,-0.0194881) , 
2, 0.0870181, 1, 0, 0.590461,0.0308813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0988329,-0.0382047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308159,-0.00924034) , 
0, 1634.65, 1, 0, 0.148467,-0.1018) , 
5, 17.058, 1, 0, 0.511694,0.00723646)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342676,-0.0236186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616763,0.0101563) , 
1, 3.18714, 1, 0, 0.579729,0.0220658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210009,-0.0157855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11455,-0.0406584) , 
2, 0.120816, 1, 0, 0.163307,-0.104516) , 
2, 0.0962754, 1, 0, 0.51053,0.00103135)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680771,0.0146787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378038,-0.0280146) , 
3, 0.345637, 1, 0, 0.638761,0.0348327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256161,-0.0225889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600037,0.0183045) , 
0, 2060.62, 1, 0, 0.296444,-0.0650269) , 
5, 9.23227, 1, 0, 0.499339,-0.00583888)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372584,-0.0127055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146374,-0.0529777) , 
3, 0.45052, 1, 0, 0.355971,-0.0635695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684369,0.0159235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189019,-0.0237156) , 
2, 0.0870181, 1, 0, 0.59331,0.0356745) , 
0, 1107.45, 1, 0, 0.489526,-0.0077229)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843864,0.0318065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312632,-0.0212652) , 
5, 18.2174, 1, 0, 0.783446,0.0958387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499998,0.00126384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151412,-0.0280334) , 
5, 10.3839, 1, 0, 0.350188,-0.0354592) , 
2, 0.0222054, 1, 0, 0.50979,0.0129078)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165359,-0.0310746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596134,0.00753999) , 
4, 0.118331, 1, 0, 0.507341,0.00362893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534144,-0.000709885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145374,-0.0544484) , 
5, 3.39935, 1, 0, 0.275111,-0.151119) , 
4, 1.08699, 1, 0, 0.48522,-0.0111118)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143331,-0.0331173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615659,0.010677) , 
4, 0.044601, 1, 0, 0.555076,0.0237215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690262,0.0122089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327759,-0.0243639) , 
2, 0.00740698, 1, 0, 0.366547,-0.0809901) , 
3, 0.22842, 1, 0, 0.488013,-0.0135259)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649938,0.000880566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899914,0.0370688) , 
1, 4.74582, 1, 0, 0.74487,0.0481628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352319,-0.00286712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306428,-0.0289839) , 
4, 0.910276, 1, 0, 0.34078,-0.0399449) , 
2, 0.0240604, 1, 0, 0.49211,-0.00694898)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608824,0.0112666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0945215,-0.0374016) , 
5, 21.3976, 1, 0, 0.531065,0.0217764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440661,-0.016642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.095595,-0.0580514) , 
5, 4.62957, 1, 0, 0.252749,-0.153341) , 
4, 1.08642, 1, 0, 0.504787,0.00524175)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724233,0.0233997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3308,-0.0313946) , 
3, 0.351727, 1, 0, 0.670197,0.0610115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392145,-0.00584611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207922,-0.0522475) , 
4, 0.70954, 1, 0, 0.368617,-0.0442533) , 
5, 5.59271, 1, 0, 0.487495,-0.00275972)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438723,-0.00612648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690077,0.0252385) , 
0, 1107.45, 1, 0, 0.595394,0.048309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615619,0.00393427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339394,-0.0183494) , 
5, 5.11944, 1, 0, 0.439677,-0.0364359) , 
3, 0.111105, 1, 0, 0.492743,-0.00755644)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468827,-0.0165348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797021,0.0219279) , 
1, 2.9755, 1, 0, 0.762742,0.0624923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324934,-0.0114395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540615,0.0115457) , 
1, 5.18325, 1, 0, 0.370701,-0.0242889) , 
2, 0.0203692, 1, 0, 0.498497,0.00399968)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241637,-0.0402678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0570149,-0.0339246) , 
2, 0.0340115, 1, 0, 0.108969,-0.100104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359456,-0.0163908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591099,0.00871165) , 
0, 869.155, 1, 0, 0.552882,0.0167664) , 
4, 0.0220096, 1, 0, 0.504959,0.00414965)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595599,0.009243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701703,-0.0375015) , 
5, 23.4873, 1, 0, 0.528435,0.0194914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326481,-0.0393188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301266,-0.0180381) , 
4, 1.12543, 1, 0, 0.309567,-0.101434) , 
4, 1.04315, 1, 0, 0.501744,0.00474481)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811287,0.0231525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414479,0.000276555) , 
2, 0.0185174, 1, 0, 0.534168,0.0248765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374453,-0.0372971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177856,-0.0166204) , 
2, 0.0276057, 1, 0, 0.268256,-0.107736) , 
3, 0.407391, 1, 0, 0.512829,0.0142346)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336251,-0.00958972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309274,-0.0357563) , 
4, 0.777137, 1, 0, 0.32714,-0.0737363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652099,0.0111039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165058,-0.0224529) , 
2, 0.0962123, 1, 0, 0.560634,0.0191992) , 
1, 3.78658, 1, 0, 0.493568,-0.00749459)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761926,0.0282877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586849,-0.000864367) , 
4, 0.780728, 1, 0, 0.661615,0.0447843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335518,-0.00460987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289111,-0.046427) , 
4, 0.487899, 1, 0, 0.328004,-0.0410535) , 
5, 8.07658, 1, 0, 0.512037,0.00629798)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378361,-0.0166845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634097,0.0102356) , 
1, 3.21133, 1, 0, 0.597065,0.0228472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159778,-0.00976761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125346,-0.0415055) , 
4, 0.171298, 1, 0, 0.15021,-0.056576) , 
5, 16.1526, 1, 0, 0.505258,0.0065296)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210547,-0.0412678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452314,-0.00363744) , 
1, 2.4929, 1, 0, 0.439936,-0.020722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.915408,0.0529341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.632029,0.010425) , 
5, 2.77798, 1, 0, 0.694983,0.0680285) , 
1, 5.06847, 1, 0, 0.50585,0.00221469)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635863,0.00721362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326822,-0.0231265) , 
4, 1.04287, 1, 0, 0.59173,0.0110868) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147643,-0.0200856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143524,-0.0403101) , 
4, 0.244003, 1, 0, 0.146819,-0.0698437) , 
5, 15.4542, 1, 0, 0.491183,-0.00720291)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201329,-0.0279745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688327,0.0193917) , 
4, 0.108462, 1, 0, 0.614055,0.0463022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836326,0.0434247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416663,-0.011112) , 
2, 0.00555087, 1, 0, 0.441539,-0.0289355) , 
3, 0.104947, 1, 0, 0.496025,-0.00517321)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375346,-0.00252826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391018,-0.01677) , 
4, 0.77703, 1, 0, 0.380266,-0.0274718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733684,0.0134783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334335,-0.00733273) , 
5, 10.0701, 1, 0, 0.597542,0.0232003) , 
1, 4.19248, 1, 0, 0.499738,0.000390915)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695308,0.0127948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339755,-0.00932957) , 
5, 8.32169, 1, 0, 0.534796,0.012332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324558,0.0102836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2836,-0.0316247) , 
1, 3.51622, 1, 0, 0.295828,-0.0758216) , 
3, 0.357993, 1, 0, 0.501425,2.17087e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590315,0.0114818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410907,-0.0189647) , 
4, 0.99632, 1, 0, 0.564351,0.023259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475416,-0.0244424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243631,-0.000496374) , 
2, 0.0388445, 1, 0, 0.361307,-0.0522471) , 
3, 0.259255, 1, 0, 0.505445,0.00135373)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515495,-0.00510318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777407,0.0213392) , 
1, 3.98818, 1, 0, 0.685947,0.0396565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329844,-0.00117789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205897,-0.043318) , 
4, 0.55453, 1, 0, 0.315432,-0.0212941) , 
5, 8.07754, 1, 0, 0.507317,0.0102714)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207437,-0.0435783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471608,-0.00602055) , 
0, 771.406, 1, 0, 0.461527,-0.0266657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839039,0.0385788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599562,-0.00921542) , 
3, 0.159563, 1, 0, 0.740435,0.0594394) , 
0, 2481.58, 1, 0, 0.487792,-0.0185572)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148697,-0.0200934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609737,0.0147276) , 
4, 0.0779762, 1, 0, 0.499503,0.0294039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623838,-0.00105108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16691,-0.0542845) , 
5, 5.0058, 1, 0, 0.528611,-0.0382738) , 
4, 0.777137, 1, 0, 0.509416,0.00635517)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164818,-0.053773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361421,-0.00765234) , 
0, 773.538, 1, 0, 0.311519,-0.0703748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686217,0.0117524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308469,-0.0067712) , 
5, 10.1769, 1, 0, 0.540631,0.0178033) , 
0, 869.155, 1, 0, 0.49956,0.00199623)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164458,-0.0260034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656882,0.00988203) , 
4, 0.0445047, 1, 0, 0.595375,0.0215433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589647,0.0073881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382957,-0.0144437) , 
5, 2.23752, 1, 0, 0.41686,-0.0378109) , 
3, 0.154307, 1, 0, 0.501136,-0.00978983)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474063,0.00126461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751821,0.0273575) , 
1, 5.23037, 1, 0, 0.532043,0.0214873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589761,-0.00375363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211618,-0.0305219) , 
5, 2.50323, 1, 0, 0.374069,-0.0690295) , 
4, 0.99821, 1, 0, 0.509297,0.00845402)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652328,0.0107647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137301,-0.0172738) , 
5, 16.6444, 1, 0, 0.513458,0.0175512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806093,0.00861983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381494,-0.0211846) , 
2, 0.014801, 1, 0, 0.470477,-0.0582457) , 
4, 0.888063, 1, 0, 0.503399,-0.000187013)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330263,-0.0347857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203848,-0.00906391) , 
2, 0.0355077, 1, 0, 0.261654,-0.0844199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57265,0.00503599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137739,-0.023739) , 
2, 0.116641, 1, 0, 0.528498,0.00855072) , 
1, 2.96929, 1, 0, 0.503615,-0.000118827)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454584,-0.00845644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.824058,0.0200429) , 
1, 3.18195, 1, 0, 0.767369,0.0452258) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603314,0.00976507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339795,-0.00830962) , 
5, 3.04224, 1, 0, 0.388971,-0.0153684) , 
2, 0.0184974, 1, 0, 0.499453,0.00232343)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423441,-0.00188348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436251,-0.0191363) , 
4, 0.798985, 1, 0, 0.427565,-0.027335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729349,0.0195624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448979,-0.0273528) , 
3, 0.283805, 1, 0, 0.68214,0.0334272) , 
0, 1703.17, 1, 0, 0.493886,-0.0115054)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741004,0.0186079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292604,-0.00562275) , 
2, 0.0647786, 1, 0, 0.610917,0.0366517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410972,0.000829018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549407,-0.0211073) , 
0, 1658.89, 1, 0, 0.44756,-0.017204) , 
3, 0.129629, 1, 0, 0.512774,0.0042957)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452706,-0.0210669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23946,-0.000297997) , 
2, 0.0428096, 1, 0, 0.349038,-0.0443845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681541,0.0116911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225736,-0.0133966) , 
2, 0.0703551, 1, 0, 0.56995,0.0191807) , 
0, 988.301, 1, 0, 0.49934,-0.00113671)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4558,-0.0348365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539302,0.00553787) , 
3, 0.0132714, 1, 0, 0.535354,0.0122831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273007,-0.00952366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375531,-0.0368829) , 
1, 4.49803, 1, 0, 0.299994,-0.0648253) , 
3, 0.357992, 1, 0, 0.504118,0.0020495)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412684,-0.00501648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640923,0.0108225) , 
1, 4.30626, 1, 0, 0.53587,0.0107721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316859,-0.0422671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195789,-0.000761865) , 
2, 0.0349733, 1, 0, 0.255176,-0.0922718) , 
3, 0.388874, 1, 0, 0.508986,0.000902762)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84027,0.03162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541163,0.000608241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301832,-0.0156079) , 
3, 0.308633, 1, 0, 0.492263,-0.00978164) , 
2, 0.00370163, 1, 0, 0.506861,-0.0052748)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529863,-0.00374926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.809969,0.0257602) , 
1, 4.34193, 1, 0, 0.674149,0.0351129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42101,-0.00285562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248933,-0.0396092) , 
4, 0.732625, 1, 0, 0.39863,-0.024491) , 
5, 5.08977, 1, 0, 0.494729,-0.00370153)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567026,0.00923658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628218,-0.00599976) , 
4, 0.732177, 1, 0, 0.590776,0.0114066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249451,0.000277305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107735,-0.0295796) , 
3, 0.117161, 1, 0, 0.154565,-0.0535279) , 
2, 0.087032, 1, 0, 0.498822,-0.00228173)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459851,0.00147009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589392,-0.0216665) , 
1, 5.33378, 1, 0, 0.48192,-0.0072641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906215,0.054592) , 
0, 3252.07, 1, 0, 0.496425,-0.00207455)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726848,0.0121753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444171,-0.00514496) , 
5, 4.61565, 1, 0, 0.545182,0.00405376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254457,0.0296237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347514,-0.0211245) , 
4, 0.198224, 1, 0, 0.328547,-0.0515565) , 
3, 0.296288, 1, 0, 0.496298,-0.00849478)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647627,-0.00131996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718446,0.0325115) , 
5, 4.28039, 1, 0, 0.663599,0.0219724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320776,-0.00143382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439956,-0.0182261) , 
4, 0.377728, 1, 0, 0.370867,-0.030302) , 
5, 5.68641, 1, 0, 0.489944,-0.00903792)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758738,0.0104503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875394,0.0424624) , 
2, 0.0135684, 1, 0, 0.775955,0.0463167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569198,0.00379026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317535,-0.00955837) , 
5, 4.47534, 1, 0, 0.39371,-0.017029) , 
2, 0.0166526, 1, 0, 0.500307,0.000636265)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774779,0.0163595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66642,0.0406568) , 
3, 0.222332, 1, 0, 0.743937,0.0829043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474756,0.00528315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444106,-0.022919) , 
4, 0.732625, 1, 0, 0.466471,-0.00831292) , 
5, 2.05405, 1, 0, 0.505189,0.00441583)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583645,0.0153315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56236,-0.00412094) , 
4, 0.643463, 1, 0, 0.572343,0.0181737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236741,-0.0237659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0556546,-0.0245818) , 
2, 0.0297404, 1, 0, 0.101047,-0.0545451) , 
5, 20.2089, 1, 0, 0.505875,0.00791791)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854658,0.0364949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629224,0.00136711) , 
3, 0.0493411, 1, 0, 0.661285,0.020409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4069,-0.000938098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269658,-0.0327774) , 
4, 0.642525, 1, 0, 0.385359,-0.0185111) , 
5, 5.68641, 1, 0, 0.493572,-0.0032473)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84214,0.0199603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445741,-0.00852702) , 
2, 0.035292, 1, 0, 0.686651,0.021308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58337,-0.0124421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258104,0.00123287) , 
2, 0.0462699, 1, 0, 0.440658,-0.0227567) , 
5, 2.37809, 1, 0, 0.483048,-0.0151635)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603973,0.0171125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5716,-0.00323386) , 
4, 0.666633, 1, 0, 0.587312,0.0237723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189612,-0.0248795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0459099,-0.0247665) , 
2, 0.0408193, 1, 0, 0.0980878,-0.0556193) , 
5, 19.3323, 1, 0, 0.507537,0.0108263)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391382,-0.0193311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679141,0.00844334) , 
0, 827.471, 1, 0, 0.645036,0.0163784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301158,-0.000508226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359511,-0.0291371) , 
4, 0.355368, 1, 0, 0.320918,-0.0345729) , 
5, 8.07653, 1, 0, 0.493652,-0.00741915)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715083,0.0148394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207893,-0.0213381) , 
2, 0.111087, 1, 0, 0.669909,0.0394045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366713,-0.00161695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0816407,-0.0273294) , 
5, 23.4394, 1, 0, 0.282006,-0.0207423) , 
5, 9.51041, 1, 0, 0.507282,0.0141882)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548292,-0.00467413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853768,0.0275234) , 
0, 3013.8, 1, 0, 0.566284,-0.0104361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467504,0.0189662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462762,-0.00300489) , 
4, 0.863842, 1, 0, 0.466145,0.0414989) , 
3, 0.197532, 1, 0, 0.526744,0.0100706)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43696,-0.0233439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233082,0.00691227) , 
2, 0.0428323, 1, 0, 0.335432,-0.0362935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636796,0.00555426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142428,-0.0236779) , 
2, 0.0999942, 1, 0, 0.564481,0.00540101) , 
0, 988.301, 1, 0, 0.492669,-0.0076712)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419264,-0.0020157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393797,-0.0391497) , 
0, 1326.16, 1, 0, 0.417332,-0.0162363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.894285,0.0424026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605751,0.00391791) , 
5, 2.30993, 1, 0, 0.65466,0.0290688) , 
0, 1407.45, 1, 0, 0.507405,0.00095838)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61628,0.0145049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582355,-0.00492318) , 
4, 0.886512, 1, 0, 0.6079,0.0303118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397365,-0.0034768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475472,-0.034064) , 
0, 2168.37, 1, 0, 0.40647,-0.0239133) , 
3, 0.172817, 1, 0, 0.506089,0.00290403)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368087,-0.00327731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706528,0.0238258) , 
4, 0.479829, 1, 0, 0.454922,0.0139628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541757,-0.00136208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661742,-0.0358029) , 
1, 5.40273, 1, 0, 0.566497,-0.0234434) , 
4, 0.688259, 1, 0, 0.50249,-0.00198468)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44991,0.00357243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530691,-0.00799791) , 
4, 0.732367, 1, 0, 0.47968,-0.00300788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696214,-0.00348941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955889,0.0792756) , 
4, 0.758678, 1, 0, 0.794594,0.0636409) , 
1, 5.81635, 1, 0, 0.512452,0.0039282)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576144,-0.00342921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525938,0.0140819) , 
3, 0.145834, 1, 0, 0.552721,0.0169576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351615,-0.0267684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185533,0.00430221) , 
2, 0.0349672, 1, 0, 0.267523,-0.0511483) , 
3, 0.357992, 1, 0, 0.511848,0.00719715)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703917,0.00425143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424077,-0.00797556) , 
5, 4.75736, 1, 0, 0.515127,-0.0125743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248576,-0.00718068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279689,-0.0314738) , 
1, 4.18552, 1, 0, 0.260884,-0.060779) , 
3, 0.364133, 1, 0, 0.482914,-0.0186818)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337057,5.54563e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51221,-0.0240881) , 
4, 0.378132, 1, 0, 0.386386,-0.0243132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600608,0.0102943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702428,-0.0199633) , 
0, 2151.74, 1, 0, 0.618147,0.0208046) , 
4, 0.555239, 1, 0, 0.503886,-0.00143906)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471993,0.00205458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572572,-0.0233103) , 
0, 1954.38, 1, 0, 0.47967,0.000702735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652213,0.00447621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840966,0.0425078) , 
1, 5.8611, 1, 0, 0.753654,0.0627164) , 
0, 2298.9, 1, 0, 0.516477,0.00903358)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229053,-0.0288687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547922,0.00587703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357035,-0.0165009) , 
4, 0.996125, 1, 0, 0.518956,0.00815401) , 
1, 2.64977, 1, 0, 0.504298,0.00273455)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465883,-0.00158649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593035,-0.0338228) , 
1, 5.82007, 1, 0, 0.473263,-0.0106616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88763,0.0631985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774259,-0.00433752) , 
1, 6.28552, 1, 0, 0.829609,0.074064) , 
0, 2557.96, 1, 0, 0.50325,-0.00353178)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618232,0.00708535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418172,-0.00578368) , 
3, 0.216058, 1, 0, 0.539803,0.00566797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483685,-0.0449276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209758,-0.00598746) , 
2, 0.037341, 1, 0, 0.289741,-0.0613072) , 
4, 1.04341, 1, 0, 0.510617,-0.00214907)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679661,-0.0156594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84797,0.063941) , 
3, 0.148137, 1, 0, 0.756794,0.0761919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36933,0.00901262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501964,-0.0087197) , 
1, 3.51091, 1, 0, 0.47513,-0.0163048) , 
5, 1.18959, 1, 0, 0.495286,-0.0096855)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68067,-0.00466971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487174,-0.0343346) , 
5, 2.35861, 1, 0, 0.614807,-0.0517307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343532,0.0163529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480419,-0.00354349) , 
1, 3.62447, 1, 0, 0.447521,0.00365703) , 
5, 3.41216, 1, 0, 0.491978,-0.0110625)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671816,-0.0140866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397136,-0.000917117) , 
2, 0.0166657, 1, 0, 0.471858,-0.01439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859781,-0.00939405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736757,0.0347548) , 
2, 0.0147019, 1, 0, 0.785797,0.0549602) , 
0, 2537.19, 1, 0, 0.501608,-0.00781816)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159918,-0.0383946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474235,-0.0241663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510823,0.00350468) , 
3, 0.0123766, 1, 0, 0.509146,0.00732663) , 
1, 2.4733, 1, 0, 0.496255,0.00216867)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319186,-0.0228607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567001,-0.00227979) , 
0, 832.214, 1, 0, 0.537563,-0.015935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719746,0.0405551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292318,0.00554968) , 
2, 0.0166511, 1, 0, 0.390969,0.0517532) , 
3, 0.283919, 1, 0, 0.504736,-0.00077766)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68475,0.00818301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277853,-0.00326327) , 
2, 0.0351651, 1, 0, 0.471902,0.00797514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742838,-0.000250733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487774,-0.0401375) , 
3, 0.156301, 1, 0, 0.62272,-0.0639283) , 
1, 5.39135, 1, 0, 0.501866,-0.00631013)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520895,-0.00534662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761074,0.0110146) , 
0, 1739.49, 1, 0, 0.583737,-0.00575922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253784,-0.00181384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136436,-0.0215958) , 
3, 0.147387, 1, 0, 0.183305,-0.0390045) , 
2, 0.0851802, 1, 0, 0.493302,-0.0132674)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647671,3.5936e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325229,0.0187811) , 
2, 0.05356, 1, 0, 0.548553,0.0180793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.098229,-0.0287831) , 
2, 0.124003, 1, 0, 0.515347,0.0113506)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529592,-0.00602976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844701,0.0199712) , 
1, 3.78658, 1, 0, 0.751244,0.030968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318493,0.000422776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441482,-0.0196496) , 
1, 5.41277, 1, 0, 0.338952,-0.0110938) , 
2, 0.0277762, 1, 0, 0.507168,0.00606748)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673554,0.00277731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.988173,0.0576442) , 
1, 4.42392, 1, 0, 0.817928,0.0567482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453021,-0.000721343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449466,-0.0136379) , 
4, 0.820881, 1, 0, 0.451904,-0.0164446) , 
2, 0.00925872, 1, 0, 0.501015,-0.00662405)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133757,-0.0223799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57289,0.00372044) , 
4, 0.0548423, 1, 0, 0.49329,0.00152304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502154,-0.0194802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298833,0.0252509) , 
4, 1.24577, 1, 0, 0.465934,-0.044621) , 
4, 0.886564, 1, 0, 0.486868,-0.00931033)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528935,-0.000113796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508824,0.0577424) , 
3, 0.319172, 1, 0, 0.527774,0.0103439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266959,-0.00266637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26752,-0.0384728) , 
1, 4.30511, 1, 0, 0.267152,-0.0542674) , 
3, 0.364133, 1, 0, 0.492742,0.00165897)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770044,0.00725729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568111,0.0344921) , 
2, 0.0499715, 1, 0, 0.712011,0.0586324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480983,-0.00119897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313439,-0.0157829) , 
3, 0.166711, 1, 0, 0.391467,-0.0287892) , 
5, 4.75558, 1, 0, 0.497681,0.000178281)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48309,-0.0146868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439181,0.00037312) , 
3, 0.104947, 1, 0, 0.454596,-0.014817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79408,0.0350622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502393,-0.0014372) , 
4, 0.866874, 1, 0, 0.580574,0.0277396) , 
4, 0.752635, 1, 0, 0.498801,0.000115688)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666625,0.00549122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.941462,0.0575852) , 
1, 5.79845, 1, 0, 0.698687,0.0321882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356095,0.0013417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507383,-0.014965) , 
4, 0.39969, 1, 0, 0.435159,-0.0247051) , 
5, 3.56867, 1, 0, 0.502871,-0.0100866)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410437,-0.00151324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764362,0.0368592) , 
4, 0.559847, 1, 0, 0.446748,0.00873154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653038,-0.00239847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349908,-0.0280784) , 
5, 5.00673, 1, 0, 0.563289,-0.0319986) , 
4, 0.643054, 1, 0, 0.500656,-0.0101088)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527053,-0.00233773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254901,-0.0232315) , 
3, 0.367975, 1, 0, 0.507871,-0.0126167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352061,0.0191923) , 
3, 0.432057, 1, 0, 0.500529,-0.00913453)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737881,0.0018624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399639,0.0167111) , 
2, 0.0444069, 1, 0, 0.602193,0.0261014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347884,0.00890391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449024,-0.00894782) , 
1, 3.40809, 1, 0, 0.428167,-0.017655) , 
3, 0.154297, 1, 0, 0.50713,0.00219914)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681726,0.0149459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569126,0.00142891) , 
3, 0.0617501, 1, 0, 0.591024,0.0130136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130477,-0.00814247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202341,-0.0193484) , 
4, 0.57774, 1, 0, 0.163683,-0.0399531) , 
2, 0.087032, 1, 0, 0.499514,0.00167144)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224172,-0.0243032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754521,0.00768577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313014,-0.00396927) , 
2, 0.0314635, 1, 0, 0.508991,0.00319613) , 
1, 2.64996, 1, 0, 0.492229,-0.00193385)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446082,-0.00523308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783178,0.0300802) , 
0, 2311.49, 1, 0, 0.464873,-0.0115829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866996,0.00430093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511137,-0.0397297) , 
5, 4.77449, 1, 0, 0.651703,-0.06745) , 
1, 5.97865, 1, 0, 0.482672,-0.0169052)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357965,-0.0034662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396895,-0.0222673) , 
0, 986.085, 1, 0, 0.370481,-0.0322299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544069,0.0138597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60071,-0.00552135) , 
0, 1386.02, 1, 0, 0.58599,7.92915e-05) , 
0, 1156.91, 1, 0, 0.488655,-0.0145133)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649648,0.0117806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193773,-0.00365833) , 
5, 14.2037, 1, 0, 0.445719,0.0194718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770342,0.0230088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530831,-0.0110984) , 
5, 1.19553, 1, 0, 0.573613,-0.017313) , 
4, 0.644132, 1, 0, 0.502418,0.00316403)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180123,-0.0323262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443353,0.00832395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573087,-0.00374597) , 
4, 0.577413, 1, 0, 0.5101,0.00593041) , 
1, 2.3884, 1, 0, 0.499353,0.00245329)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779445,0.0203322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438048,-0.00348455) , 
2, 0.00740698, 1, 0, 0.474683,-0.00353896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833825,0.057494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763159,0.00752224) , 
0, 2807.37, 1, 0, 0.800393,0.0937923) , 
1, 5.81667, 1, 0, 0.505834,0.00577001)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625521,-0.00584364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297656,0.00501414) , 
2, 0.0425688, 1, 0, 0.479126,-0.00379771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667957,-0.0259306) , 
0, 2848.78, 1, 0, 0.491459,-0.00807774)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725887,-0.00374172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360786,0.00893011) , 
2, 0.0333143, 1, 0, 0.539438,0.00976566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301342,0.0120766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244526,-0.0342064) , 
1, 3.63489, 1, 0, 0.264206,-0.0693167) , 
3, 0.370295, 1, 0, 0.503178,-0.000652939)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45858,-0.000987226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574155,-0.0266361) , 
1, 5.49218, 1, 0, 0.467498,-0.00935283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.889102,0.0117882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677602,0.0404078) , 
2, 0.0328445, 1, 0, 0.812295,0.0663203) , 
1, 5.87571, 1, 0, 0.498291,-0.00259481)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713451,0.0126631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29946,-0.00359546) , 
5, 10.2368, 1, 0, 0.531928,0.0198738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522474,-0.0243765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30176,0.018263) , 
4, 1.15268, 1, 0, 0.452361,-0.0411493) , 
4, 0.930913, 1, 0, 0.516154,0.00777608)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760149,0.0361619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80073,0.00511104) , 
4, 0.336337, 1, 0, 0.791121,0.0395023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434947,-0.0107079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386604,0.0143964) , 
4, 1.02098, 1, 0, 0.42843,-0.0245538) , 
2, 0.0111027, 1, 0, 0.495682,-0.0126762)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323541,-0.00755672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513051,0.0144618) , 
1, 3.74906, 1, 0, 0.409814,0.00768853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770665,0.00550156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525858,-0.014561) , 
5, 2.69836, 1, 0, 0.579352,-0.0322517) , 
1, 4.44256, 1, 0, 0.490233,-0.0112568)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719276,0.000843172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307658,-0.0287426) , 
3, 0.320952, 1, 0, 0.647332,-0.0169894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656766,0.0151201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293347,-0.000346604) , 
5, 9.98266, 1, 0, 0.47453,0.0253367) , 
5, 3.41211, 1, 0, 0.519821,0.0142432)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418261,-0.006708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658709,0.016233) , 
1, 5.13965, 1, 0, 0.465531,-0.008222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592467,-0.0307538) , 
1, 6.38459, 1, 0, 0.471745,-0.0121832)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762295,0.0194059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552243,-0.000124365) , 
4, 0.907382, 1, 0, 0.671657,0.0357315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341626,0.00120725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393767,-0.0232358) , 
4, 0.466237, 1, 0, 0.359647,-0.0243906) , 
5, 5.94425, 1, 0, 0.488342,0.00040803)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636621,0.0089011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201326,-0.0307303) , 
3, 0.450573, 1, 0, 0.615442,0.0232207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175371,-0.00120418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187809,-0.0218906) , 
4, 0.175605, 1, 0, 0.179487,-0.0225571) , 
5, 13.8452, 1, 0, 0.502021,0.0113108)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145436,-0.012129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563507,0.0125679) , 
4, 0.0816272, 1, 0, 0.445057,0.0229256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62974,-0.0119505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535707,0.00218388) , 
4, 0.855977, 1, 0, 0.577484,-0.0140192) , 
4, 0.643874, 1, 0, 0.504782,0.0062632)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318465,-0.0124593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589573,0.0061796) , 
0, 869.157, 1, 0, 0.54429,0.00876179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25839,0.0126159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293411,-0.0244466) , 
4, 0.444508, 1, 0, 0.279105,-0.041863) , 
3, 0.320989, 1, 0, 0.494347,-0.000772506)    );
   return;
};

// Clean up
inline void ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_NewCuts_NewQCD_NoRegSplits_fold8::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
